-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity cfu_hls_cfu_hls_Pipeline_HANN_LOOP is
port (
    ap_clk : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    frame_buf_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    frame_buf_ce0 : OUT STD_LOGIC;
    frame_buf_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    real_buf_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
    real_buf_ce1 : OUT STD_LOGIC;
    real_buf_we1 : OUT STD_LOGIC;
    real_buf_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    imag_buf_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
    imag_buf_ce1 : OUT STD_LOGIC;
    imag_buf_we1 : OUT STD_LOGIC;
    imag_buf_d1 : OUT STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of cfu_hls_cfu_hls_Pipeline_HANN_LOOP is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv12_0 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    constant ap_const_lv12_800 : STD_LOGIC_VECTOR (11 downto 0) := "100000000000";
    constant ap_const_lv12_1 : STD_LOGIC_VECTOR (11 downto 0) := "000000000001";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_2F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "auto";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "auto";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln55_fu_123_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal hann_window_fixed_address0 : STD_LOGIC_VECTOR (10 downto 0);
    signal hann_window_fixed_q0 : STD_LOGIC_VECTOR (16 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal zext_ln55_fu_135_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln55_reg_175 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln55_reg_175_pp0_iter1_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln55_reg_175_pp0_iter2_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln55_reg_175_pp0_iter3_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln55_reg_175_pp0_iter4_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln55_reg_175_pp0_iter5_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln55_reg_175_pp0_iter6_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal frame_buf_load_reg_191 : STD_LOGIC_VECTOR (31 downto 0);
    signal hann_window_fixed_load_reg_196 : STD_LOGIC_VECTOR (16 downto 0);
    signal trunc_ln1_reg_211 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal i_fu_46 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    signal add_ln55_fu_129_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_i_1 : STD_LOGIC_VECTOR (11 downto 0);
    signal frame_buf_ce0_local : STD_LOGIC;
    signal hann_window_fixed_ce0_local : STD_LOGIC;
    signal imag_buf_we1_local : STD_LOGIC;
    signal imag_buf_ce1_local : STD_LOGIC;
    signal real_buf_we1_local : STD_LOGIC;
    signal real_buf_ce1_local : STD_LOGIC;
    signal grp_fu_111_p0 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_fu_111_p2 : STD_LOGIC_VECTOR (47 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter5_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter6_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal grp_fu_111_p00 : STD_LOGIC_VECTOR (47 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component cfu_hls_mul_17ns_32s_48_5_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (16 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (47 downto 0) );
    end component;


    component cfu_hls_cfu_hls_Pipeline_HANN_LOOP_hann_window_fixed_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (10 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (16 downto 0) );
    end component;


    component cfu_hls_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    hann_window_fixed_U : component cfu_hls_cfu_hls_Pipeline_HANN_LOOP_hann_window_fixed_ROM_AUTO_1R
    generic map (
        DataWidth => 17,
        AddressRange => 2048,
        AddressWidth => 11)
    port map (
        clk => ap_clk,
        reset => ap_const_logic_0,
        address0 => hann_window_fixed_address0,
        ce0 => hann_window_fixed_ce0_local,
        q0 => hann_window_fixed_q0);

    mul_17ns_32s_48_5_1_U1 : component cfu_hls_mul_17ns_32s_48_5_1
    generic map (
        ID => 1,
        NUM_STAGE => 5,
        din0_WIDTH => 17,
        din1_WIDTH => 32,
        dout_WIDTH => 48)
    port map (
        clk => ap_clk,
        reset => ap_const_logic_0,
        din0 => grp_fu_111_p0,
        din1 => frame_buf_load_reg_191,
        ce => ap_const_logic_1,
        dout => grp_fu_111_p2);

    flow_control_loop_pipe_sequential_init_U : component cfu_hls_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_const_logic_0,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            ap_CS_fsm <= ap_NS_fsm;
        end if;
    end process;

    ap_done_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_continue_int = ap_const_logic_1)) then 
                ap_done_reg <= ap_const_logic_0;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter6_reg = ap_const_logic_1))) then 
                ap_done_reg <= ap_const_logic_1;
            end if; 
        end if;
    end process;

    ap_enable_reg_pp0_iter1_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                ap_enable_reg_pp0_iter1 <= ap_start_int;
            end if; 
        end if;
    end process;

    i_fu_46_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln55_fu_123_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    i_fu_46 <= add_ln55_fu_129_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    i_fu_46 <= ap_const_lv12_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then
                ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                frame_buf_load_reg_191 <= frame_buf_q0;
                hann_window_fixed_load_reg_196 <= hann_window_fixed_q0;
                    zext_ln55_reg_175(11 downto 0) <= zext_ln55_fu_135_p1(11 downto 0);
                    zext_ln55_reg_175_pp0_iter1_reg(11 downto 0) <= zext_ln55_reg_175(11 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
                ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
                trunc_ln1_reg_211 <= grp_fu_111_p2(47 downto 16);
                    zext_ln55_reg_175_pp0_iter2_reg(11 downto 0) <= zext_ln55_reg_175_pp0_iter1_reg(11 downto 0);
                    zext_ln55_reg_175_pp0_iter3_reg(11 downto 0) <= zext_ln55_reg_175_pp0_iter2_reg(11 downto 0);
                    zext_ln55_reg_175_pp0_iter4_reg(11 downto 0) <= zext_ln55_reg_175_pp0_iter3_reg(11 downto 0);
                    zext_ln55_reg_175_pp0_iter5_reg(11 downto 0) <= zext_ln55_reg_175_pp0_iter4_reg(11 downto 0);
                    zext_ln55_reg_175_pp0_iter6_reg(11 downto 0) <= zext_ln55_reg_175_pp0_iter5_reg(11 downto 0);
            end if;
        end if;
    end process;
    zext_ln55_reg_175(63 downto 12) <= "0000000000000000000000000000000000000000000000000000";
    zext_ln55_reg_175_pp0_iter1_reg(63 downto 12) <= "0000000000000000000000000000000000000000000000000000";
    zext_ln55_reg_175_pp0_iter2_reg(63 downto 12) <= "0000000000000000000000000000000000000000000000000000";
    zext_ln55_reg_175_pp0_iter3_reg(63 downto 12) <= "0000000000000000000000000000000000000000000000000000";
    zext_ln55_reg_175_pp0_iter4_reg(63 downto 12) <= "0000000000000000000000000000000000000000000000000000";
    zext_ln55_reg_175_pp0_iter5_reg(63 downto 12) <= "0000000000000000000000000000000000000000000000000000";
    zext_ln55_reg_175_pp0_iter6_reg(63 downto 12) <= "0000000000000000000000000000000000000000000000000000";

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln55_fu_129_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i_1) + unsigned(ap_const_lv12_1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln55_fu_123_p2)
    begin
        if (((icmp_ln55_fu_123_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter6_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter6_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7)
    begin
        if (((ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, i_fu_46, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_i_1 <= ap_const_lv12_0;
        else 
            ap_sig_allocacmp_i_1 <= i_fu_46;
        end if; 
    end process;

    frame_buf_address0 <= zext_ln55_fu_135_p1(11 - 1 downto 0);
    frame_buf_ce0 <= frame_buf_ce0_local;

    frame_buf_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
            frame_buf_ce0_local <= ap_const_logic_1;
        else 
            frame_buf_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_111_p0 <= grp_fu_111_p00(17 - 1 downto 0);
    grp_fu_111_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(hann_window_fixed_load_reg_196),48));
    hann_window_fixed_address0 <= zext_ln55_fu_135_p1(11 - 1 downto 0);

    hann_window_fixed_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
            hann_window_fixed_ce0_local <= ap_const_logic_1;
        else 
            hann_window_fixed_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln55_fu_123_p2 <= "1" when (ap_sig_allocacmp_i_1 = ap_const_lv12_800) else "0";
    imag_buf_address1 <= zext_ln55_reg_175(11 - 1 downto 0);
    imag_buf_ce1 <= imag_buf_ce1_local;

    imag_buf_ce1_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            imag_buf_ce1_local <= ap_const_logic_1;
        else 
            imag_buf_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    imag_buf_d1 <= ap_const_lv32_0;
    imag_buf_we1 <= imag_buf_we1_local;

    imag_buf_we1_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            imag_buf_we1_local <= ap_const_logic_1;
        else 
            imag_buf_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    real_buf_address1 <= zext_ln55_reg_175_pp0_iter6_reg(11 - 1 downto 0);
    real_buf_ce1 <= real_buf_ce1_local;

    real_buf_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter7, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter7 = ap_const_logic_1))) then 
            real_buf_ce1_local <= ap_const_logic_1;
        else 
            real_buf_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    real_buf_d1 <= trunc_ln1_reg_211;
    real_buf_we1 <= real_buf_we1_local;

    real_buf_we1_local_assign_proc : process(ap_enable_reg_pp0_iter7, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter7 = ap_const_logic_1))) then 
            real_buf_we1_local <= ap_const_logic_1;
        else 
            real_buf_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    zext_ln55_fu_135_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_i_1),64));
end behav;
