-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity cfu_hls_cfu_hls_Pipeline_POWER_LOOP is
port (
    ap_clk : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    real_buf_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    real_buf_ce0 : OUT STD_LOGIC;
    real_buf_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    imag_buf_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    imag_buf_ce0 : OUT STD_LOGIC;
    imag_buf_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    power_buf_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    power_buf_ce0 : OUT STD_LOGIC;
    power_buf_we0 : OUT STD_LOGIC;
    power_buf_d0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of cfu_hls_cfu_hls_Pipeline_POWER_LOOP is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv11_401 : STD_LOGIC_VECTOR (10 downto 0) := "10000000001";
    constant ap_const_lv11_1 : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";
    constant ap_const_lv32_1A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011010";
    constant ap_const_lv32_39 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111001";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "auto";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "auto";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter8 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln118_fu_103_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal zext_ln118_fu_115_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln118_reg_161 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln118_reg_161_pp0_iter1_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln118_reg_161_pp0_iter2_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln118_reg_161_pp0_iter3_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln118_reg_161_pp0_iter4_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln118_reg_161_pp0_iter5_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln118_reg_161_pp0_iter6_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln118_reg_161_pp0_iter7_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal r_reg_176 : STD_LOGIC_VECTOR (31 downto 0);
    signal im_reg_181 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln120_fu_126_p1 : STD_LOGIC_VECTOR (57 downto 0);
    signal sext_ln121_fu_131_p1 : STD_LOGIC_VECTOR (57 downto 0);
    signal grp_fu_87_p2 : STD_LOGIC_VECTOR (57 downto 0);
    signal mul_ln122_reg_198 : STD_LOGIC_VECTOR (57 downto 0);
    signal grp_fu_91_p2 : STD_LOGIC_VECTOR (57 downto 0);
    signal mul_ln122_1_reg_203 : STD_LOGIC_VECTOR (57 downto 0);
    signal trunc_ln8_reg_208 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal k_fu_44 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    signal add_ln118_fu_109_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_k_1 : STD_LOGIC_VECTOR (10 downto 0);
    signal real_buf_ce0_local : STD_LOGIC;
    signal imag_buf_ce0_local : STD_LOGIC;
    signal power_buf_we0_local : STD_LOGIC;
    signal power_buf_ce0_local : STD_LOGIC;
    signal grp_fu_87_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_87_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_91_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_91_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal pwr_fu_136_p2 : STD_LOGIC_VECTOR (57 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter5_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter6_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter7_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component cfu_hls_mul_32s_32s_58_5_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (57 downto 0) );
    end component;


    component cfu_hls_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    mul_32s_32s_58_5_1_U21 : component cfu_hls_mul_32s_32s_58_5_1
    generic map (
        ID => 1,
        NUM_STAGE => 5,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 58)
    port map (
        clk => ap_clk,
        reset => ap_const_logic_0,
        din0 => grp_fu_87_p0,
        din1 => grp_fu_87_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_87_p2);

    mul_32s_32s_58_5_1_U22 : component cfu_hls_mul_32s_32s_58_5_1
    generic map (
        ID => 1,
        NUM_STAGE => 5,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 58)
    port map (
        clk => ap_clk,
        reset => ap_const_logic_0,
        din0 => grp_fu_91_p0,
        din1 => grp_fu_91_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_91_p2);

    flow_control_loop_pipe_sequential_init_U : component cfu_hls_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_const_logic_0,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            ap_CS_fsm <= ap_NS_fsm;
        end if;
    end process;

    ap_done_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_continue_int = ap_const_logic_1)) then 
                ap_done_reg <= ap_const_logic_0;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter7_reg = ap_const_logic_1))) then 
                ap_done_reg <= ap_const_logic_1;
            end if; 
        end if;
    end process;

    ap_enable_reg_pp0_iter1_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                ap_enable_reg_pp0_iter1 <= ap_start_int;
            end if; 
        end if;
    end process;

    k_fu_44_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln118_fu_103_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    k_fu_44 <= add_ln118_fu_109_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    k_fu_44 <= ap_const_lv11_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then
                ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                im_reg_181 <= imag_buf_q0;
                r_reg_176 <= real_buf_q0;
                    zext_ln118_reg_161(10 downto 0) <= zext_ln118_fu_115_p1(10 downto 0);
                    zext_ln118_reg_161_pp0_iter1_reg(10 downto 0) <= zext_ln118_reg_161(10 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
                ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
                ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
                mul_ln122_1_reg_203 <= grp_fu_91_p2;
                mul_ln122_reg_198 <= grp_fu_87_p2;
                trunc_ln8_reg_208 <= pwr_fu_136_p2(57 downto 26);
                    zext_ln118_reg_161_pp0_iter2_reg(10 downto 0) <= zext_ln118_reg_161_pp0_iter1_reg(10 downto 0);
                    zext_ln118_reg_161_pp0_iter3_reg(10 downto 0) <= zext_ln118_reg_161_pp0_iter2_reg(10 downto 0);
                    zext_ln118_reg_161_pp0_iter4_reg(10 downto 0) <= zext_ln118_reg_161_pp0_iter3_reg(10 downto 0);
                    zext_ln118_reg_161_pp0_iter5_reg(10 downto 0) <= zext_ln118_reg_161_pp0_iter4_reg(10 downto 0);
                    zext_ln118_reg_161_pp0_iter6_reg(10 downto 0) <= zext_ln118_reg_161_pp0_iter5_reg(10 downto 0);
                    zext_ln118_reg_161_pp0_iter7_reg(10 downto 0) <= zext_ln118_reg_161_pp0_iter6_reg(10 downto 0);
            end if;
        end if;
    end process;
    zext_ln118_reg_161(63 downto 11) <= "00000000000000000000000000000000000000000000000000000";
    zext_ln118_reg_161_pp0_iter1_reg(63 downto 11) <= "00000000000000000000000000000000000000000000000000000";
    zext_ln118_reg_161_pp0_iter2_reg(63 downto 11) <= "00000000000000000000000000000000000000000000000000000";
    zext_ln118_reg_161_pp0_iter3_reg(63 downto 11) <= "00000000000000000000000000000000000000000000000000000";
    zext_ln118_reg_161_pp0_iter4_reg(63 downto 11) <= "00000000000000000000000000000000000000000000000000000";
    zext_ln118_reg_161_pp0_iter5_reg(63 downto 11) <= "00000000000000000000000000000000000000000000000000000";
    zext_ln118_reg_161_pp0_iter6_reg(63 downto 11) <= "00000000000000000000000000000000000000000000000000000";
    zext_ln118_reg_161_pp0_iter7_reg(63 downto 11) <= "00000000000000000000000000000000000000000000000000000";

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln118_fu_109_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_k_1) + unsigned(ap_const_lv11_1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln118_fu_103_p2)
    begin
        if (((icmp_ln118_fu_103_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter7_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter7_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8)
    begin
        if (((ap_enable_reg_pp0_iter8 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_k_1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, k_fu_44, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_k_1 <= ap_const_lv11_0;
        else 
            ap_sig_allocacmp_k_1 <= k_fu_44;
        end if; 
    end process;

    grp_fu_87_p0 <= sext_ln120_fu_126_p1(32 - 1 downto 0);
    grp_fu_87_p1 <= sext_ln120_fu_126_p1(32 - 1 downto 0);
    grp_fu_91_p0 <= sext_ln121_fu_131_p1(32 - 1 downto 0);
    grp_fu_91_p1 <= sext_ln121_fu_131_p1(32 - 1 downto 0);
    icmp_ln118_fu_103_p2 <= "1" when (ap_sig_allocacmp_k_1 = ap_const_lv11_401) else "0";
    imag_buf_address0 <= zext_ln118_fu_115_p1(11 - 1 downto 0);
    imag_buf_ce0 <= imag_buf_ce0_local;

    imag_buf_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
            imag_buf_ce0_local <= ap_const_logic_1;
        else 
            imag_buf_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    power_buf_address0 <= zext_ln118_reg_161_pp0_iter7_reg(11 - 1 downto 0);
    power_buf_ce0 <= power_buf_ce0_local;

    power_buf_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter8, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter8 = ap_const_logic_1))) then 
            power_buf_ce0_local <= ap_const_logic_1;
        else 
            power_buf_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    power_buf_d0 <= trunc_ln8_reg_208;
    power_buf_we0 <= power_buf_we0_local;

    power_buf_we0_local_assign_proc : process(ap_enable_reg_pp0_iter8, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter8 = ap_const_logic_1))) then 
            power_buf_we0_local <= ap_const_logic_1;
        else 
            power_buf_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    pwr_fu_136_p2 <= std_logic_vector(unsigned(mul_ln122_1_reg_203) + unsigned(mul_ln122_reg_198));
    real_buf_address0 <= zext_ln118_fu_115_p1(11 - 1 downto 0);
    real_buf_ce0 <= real_buf_ce0_local;

    real_buf_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
            real_buf_ce0_local <= ap_const_logic_1;
        else 
            real_buf_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

        sext_ln120_fu_126_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(r_reg_176),58));

        sext_ln121_fu_131_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(im_reg_181),58));

    zext_ln118_fu_115_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_k_1),64));
end behav;
