-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity cfu_hls_cfu_hls_Pipeline_BITREV_LOOP is
port (
    ap_clk : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    real_buf_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    real_buf_ce0 : OUT STD_LOGIC;
    real_buf_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    real_buf_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
    real_buf_ce1 : OUT STD_LOGIC;
    real_buf_we1 : OUT STD_LOGIC;
    real_buf_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    real_buf_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    imag_buf_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    imag_buf_ce0 : OUT STD_LOGIC;
    imag_buf_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    imag_buf_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
    imag_buf_ce1 : OUT STD_LOGIC;
    imag_buf_we1 : OUT STD_LOGIC;
    imag_buf_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    imag_buf_q1 : IN STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of cfu_hls_cfu_hls_Pipeline_BITREV_LOOP is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv12_0 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    constant ap_const_lv12_800 : STD_LOGIC_VECTOR (11 downto 0) := "100000000000";
    constant ap_const_lv12_1 : STD_LOGIC_VECTOR (11 downto 0) := "000000000001";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (2 downto 0) := "001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "auto";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "auto";
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal icmp_ln63_fu_104_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "auto";
    signal icmp_ln63_reg_159 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln63_fu_110_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln63_reg_163 : STD_LOGIC_VECTOR (11 downto 0);
    signal icmp_ln79_fu_142_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln79_reg_168 : STD_LOGIC_VECTOR (0 downto 0);
    signal real_buf_addr_1_reg_172 : STD_LOGIC_VECTOR (10 downto 0);
    signal real_buf_addr_reg_177 : STD_LOGIC_VECTOR (10 downto 0);
    signal imag_buf_addr_1_reg_183 : STD_LOGIC_VECTOR (10 downto 0);
    signal imag_buf_addr_reg_188 : STD_LOGIC_VECTOR (10 downto 0);
    signal tr_reg_194 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "auto";
    signal ti_reg_199 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln63_fu_116_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln79_fu_136_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal i_fu_40 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_x : STD_LOGIC_VECTOR (11 downto 0);
    signal real_buf_ce1_local : STD_LOGIC;
    signal real_buf_address1_local : STD_LOGIC_VECTOR (10 downto 0);
    signal real_buf_ce0_local : STD_LOGIC;
    signal real_buf_we1_local : STD_LOGIC;
    signal real_buf_d1_local : STD_LOGIC_VECTOR (31 downto 0);
    signal imag_buf_ce1_local : STD_LOGIC;
    signal imag_buf_address1_local : STD_LOGIC_VECTOR (10 downto 0);
    signal imag_buf_ce0_local : STD_LOGIC;
    signal imag_buf_we1_local : STD_LOGIC;
    signal imag_buf_d1_local : STD_LOGIC_VECTOR (31 downto 0);
    signal r_fu_126_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal trunc_ln64_fu_122_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component cfu_hls_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component cfu_hls_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_const_logic_0,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            ap_CS_fsm <= ap_NS_fsm;
        end if;
    end process;

    ap_done_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_continue_int = ap_const_logic_1)) then 
                ap_done_reg <= ap_const_logic_0;
            elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                ap_done_reg <= ap_const_logic_1;
            end if; 
        end if;
    end process;

    i_fu_40_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_loop_init = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                i_fu_40 <= ap_const_lv12_0;
            elsif (((icmp_ln63_reg_159 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                i_fu_40 <= add_ln63_reg_163;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                add_ln63_reg_163 <= add_ln63_fu_110_p2;
                icmp_ln63_reg_159 <= icmp_ln63_fu_104_p2;
                icmp_ln79_reg_168 <= icmp_ln79_fu_142_p2;
                imag_buf_addr_1_reg_183 <= zext_ln63_fu_116_p1(11 - 1 downto 0);
                imag_buf_addr_reg_188 <= zext_ln79_fu_136_p1(11 - 1 downto 0);
                real_buf_addr_1_reg_172 <= zext_ln63_fu_116_p1(11 - 1 downto 0);
                real_buf_addr_reg_177 <= zext_ln79_fu_136_p1(11 - 1 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                ti_reg_199 <= imag_buf_q1;
                tr_reg_194 <= real_buf_q1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln63_fu_104_p2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((icmp_ln63_fu_104_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                elsif (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXX";
        end case;
    end process;
    add_ln63_fu_110_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_x) + unsigned(ap_const_lv12_1));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1_pp0_stage0_iter0)
    begin
        if ((ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;

    ap_block_state1_pp0_stage0_iter0_assign_proc : process(ap_start_int)
    begin
                ap_block_state1_pp0_stage0_iter0 <= (ap_start_int = ap_const_logic_0);
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln63_fu_104_p2)
    begin
        if (((icmp_ln63_fu_104_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_state1, ap_start_int)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_x_assign_proc : process(ap_CS_fsm_state1, i_fu_40, ap_loop_init)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_sig_allocacmp_x <= ap_const_lv12_0;
        else 
            ap_sig_allocacmp_x <= i_fu_40;
        end if; 
    end process;

    icmp_ln63_fu_104_p2 <= "1" when (ap_sig_allocacmp_x = ap_const_lv12_800) else "0";
    icmp_ln79_fu_142_p2 <= "1" when (unsigned(trunc_ln64_fu_122_p1) < unsigned(r_fu_126_p4)) else "0";
    imag_buf_address0 <= zext_ln79_fu_136_p1(11 - 1 downto 0);
    imag_buf_address1 <= imag_buf_address1_local;

    imag_buf_address1_local_assign_proc : process(ap_CS_fsm_state1, icmp_ln63_fu_104_p2, ap_CS_fsm_state3, icmp_ln63_reg_159, icmp_ln79_fu_142_p2, icmp_ln79_reg_168, imag_buf_addr_1_reg_183, imag_buf_addr_reg_188, ap_CS_fsm_state2, zext_ln63_fu_116_p1)
    begin
        if (((icmp_ln79_reg_168 = ap_const_lv1_1) and (icmp_ln63_reg_159 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            imag_buf_address1_local <= imag_buf_addr_reg_188;
        elsif (((icmp_ln79_reg_168 = ap_const_lv1_1) and (icmp_ln63_reg_159 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            imag_buf_address1_local <= imag_buf_addr_1_reg_183;
        elsif (((icmp_ln79_fu_142_p2 = ap_const_lv1_1) and (icmp_ln63_fu_104_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            imag_buf_address1_local <= zext_ln63_fu_116_p1(11 - 1 downto 0);
        else 
            imag_buf_address1_local <= "XXXXXXXXXXX";
        end if; 
    end process;

    imag_buf_ce0 <= imag_buf_ce0_local;

    imag_buf_ce0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0)
    begin
        if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            imag_buf_ce0_local <= ap_const_logic_1;
        else 
            imag_buf_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    imag_buf_ce1 <= imag_buf_ce1_local;

    imag_buf_ce1_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln63_fu_104_p2, ap_CS_fsm_state3, icmp_ln63_reg_159, icmp_ln79_fu_142_p2, icmp_ln79_reg_168, ap_CS_fsm_state2)
    begin
        if ((((icmp_ln79_fu_142_p2 = ap_const_lv1_1) and (icmp_ln63_fu_104_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((icmp_ln79_reg_168 = ap_const_lv1_1) and (icmp_ln63_reg_159 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2)) or ((icmp_ln79_reg_168 = ap_const_lv1_1) and (icmp_ln63_reg_159 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3)))) then 
            imag_buf_ce1_local <= ap_const_logic_1;
        else 
            imag_buf_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    imag_buf_d1 <= imag_buf_d1_local;

    imag_buf_d1_local_assign_proc : process(ap_CS_fsm_state3, imag_buf_q0, icmp_ln63_reg_159, icmp_ln79_reg_168, ap_CS_fsm_state2, ti_reg_199)
    begin
        if (((icmp_ln79_reg_168 = ap_const_lv1_1) and (icmp_ln63_reg_159 = ap_const_lv1_0))) then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                imag_buf_d1_local <= ti_reg_199;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
                imag_buf_d1_local <= imag_buf_q0;
            else 
                imag_buf_d1_local <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
            end if;
        else 
            imag_buf_d1_local <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    imag_buf_we1 <= imag_buf_we1_local;

    imag_buf_we1_local_assign_proc : process(ap_CS_fsm_state3, icmp_ln63_reg_159, icmp_ln79_reg_168, ap_CS_fsm_state2)
    begin
        if ((((icmp_ln79_reg_168 = ap_const_lv1_1) and (icmp_ln63_reg_159 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2)) or ((icmp_ln79_reg_168 = ap_const_lv1_1) and (icmp_ln63_reg_159 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3)))) then 
            imag_buf_we1_local <= ap_const_logic_1;
        else 
            imag_buf_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    
    r_fu_126_p4_proc : process(ap_sig_allocacmp_x)
    variable vlo_cpy : STD_LOGIC_VECTOR(12+32 - 1 downto 0);
    variable vhi_cpy : STD_LOGIC_VECTOR(12+32 - 1 downto 0);
    variable v0_cpy : STD_LOGIC_VECTOR(12 - 1 downto 0);
    variable r_fu_126_p4_i : integer;
    variable section : STD_LOGIC_VECTOR(12 - 1 downto 0);
    variable tmp_mask : STD_LOGIC_VECTOR(12 - 1 downto 0);
    variable resvalue, res_value, res_mask : STD_LOGIC_VECTOR(12 - 1 downto 0);
    begin
        vlo_cpy := (others => '0');
        vlo_cpy(4 - 1 downto 0) := ap_const_lv32_A(4 - 1 downto 0);
        vhi_cpy := (others => '0');
        vhi_cpy(4 - 1 downto 0) := ap_const_lv32_0(4 - 1 downto 0);
        v0_cpy := ap_sig_allocacmp_x;
        if (vlo_cpy(4 - 1 downto 0) > vhi_cpy(4 - 1 downto 0)) then
            vhi_cpy(4-1 downto 0) := std_logic_vector(12-1-unsigned(ap_const_lv32_0(4-1 downto 0)));
            vlo_cpy(4-1 downto 0) := std_logic_vector(12-1-unsigned(ap_const_lv32_A(4-1 downto 0)));
            for r_fu_126_p4_i in 0 to 12-1 loop
                v0_cpy(r_fu_126_p4_i) := ap_sig_allocacmp_x(12-1-r_fu_126_p4_i);
            end loop;
        end if;
        res_value := std_logic_vector(shift_right(unsigned(v0_cpy), to_integer(unsigned('0' & vlo_cpy(4-1 downto 0)))));

        section := (others=>'0');
        section(4-1 downto 0) := std_logic_vector(unsigned(vhi_cpy(4-1 downto 0)) - unsigned(vlo_cpy(4-1 downto 0)));
        tmp_mask := (others => '1');
        res_mask := std_logic_vector(shift_left(unsigned(tmp_mask),to_integer(unsigned('0' & section(12-1 downto 0)))));
        res_mask := res_mask(12-2 downto 0) & '0';
        resvalue := res_value and not res_mask;
        r_fu_126_p4 <= resvalue(11-1 downto 0);
    end process;

    real_buf_address0 <= zext_ln79_fu_136_p1(11 - 1 downto 0);
    real_buf_address1 <= real_buf_address1_local;

    real_buf_address1_local_assign_proc : process(ap_CS_fsm_state1, icmp_ln63_fu_104_p2, ap_CS_fsm_state3, icmp_ln63_reg_159, icmp_ln79_fu_142_p2, icmp_ln79_reg_168, real_buf_addr_1_reg_172, real_buf_addr_reg_177, ap_CS_fsm_state2, zext_ln63_fu_116_p1)
    begin
        if (((icmp_ln79_reg_168 = ap_const_lv1_1) and (icmp_ln63_reg_159 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            real_buf_address1_local <= real_buf_addr_reg_177;
        elsif (((icmp_ln79_reg_168 = ap_const_lv1_1) and (icmp_ln63_reg_159 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            real_buf_address1_local <= real_buf_addr_1_reg_172;
        elsif (((icmp_ln79_fu_142_p2 = ap_const_lv1_1) and (icmp_ln63_fu_104_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            real_buf_address1_local <= zext_ln63_fu_116_p1(11 - 1 downto 0);
        else 
            real_buf_address1_local <= "XXXXXXXXXXX";
        end if; 
    end process;

    real_buf_ce0 <= real_buf_ce0_local;

    real_buf_ce0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0)
    begin
        if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            real_buf_ce0_local <= ap_const_logic_1;
        else 
            real_buf_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    real_buf_ce1 <= real_buf_ce1_local;

    real_buf_ce1_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln63_fu_104_p2, ap_CS_fsm_state3, icmp_ln63_reg_159, icmp_ln79_fu_142_p2, icmp_ln79_reg_168, ap_CS_fsm_state2)
    begin
        if ((((icmp_ln79_fu_142_p2 = ap_const_lv1_1) and (icmp_ln63_fu_104_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((icmp_ln79_reg_168 = ap_const_lv1_1) and (icmp_ln63_reg_159 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2)) or ((icmp_ln79_reg_168 = ap_const_lv1_1) and (icmp_ln63_reg_159 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3)))) then 
            real_buf_ce1_local <= ap_const_logic_1;
        else 
            real_buf_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    real_buf_d1 <= real_buf_d1_local;

    real_buf_d1_local_assign_proc : process(ap_CS_fsm_state3, real_buf_q0, icmp_ln63_reg_159, icmp_ln79_reg_168, tr_reg_194, ap_CS_fsm_state2)
    begin
        if (((icmp_ln79_reg_168 = ap_const_lv1_1) and (icmp_ln63_reg_159 = ap_const_lv1_0))) then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                real_buf_d1_local <= tr_reg_194;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
                real_buf_d1_local <= real_buf_q0;
            else 
                real_buf_d1_local <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
            end if;
        else 
            real_buf_d1_local <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    real_buf_we1 <= real_buf_we1_local;

    real_buf_we1_local_assign_proc : process(ap_CS_fsm_state3, icmp_ln63_reg_159, icmp_ln79_reg_168, ap_CS_fsm_state2)
    begin
        if ((((icmp_ln79_reg_168 = ap_const_lv1_1) and (icmp_ln63_reg_159 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2)) or ((icmp_ln79_reg_168 = ap_const_lv1_1) and (icmp_ln63_reg_159 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3)))) then 
            real_buf_we1_local <= ap_const_logic_1;
        else 
            real_buf_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    trunc_ln64_fu_122_p1 <= ap_sig_allocacmp_x(11 - 1 downto 0);
    zext_ln63_fu_116_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_x),64));
    zext_ln79_fu_136_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(r_fu_126_p4),64));
end behav;
