-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity cfu_hls_mel_k_len_fixed_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 8; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of cfu_hls_mel_k_len_fixed_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00001110", 1 => "00010000", 2 => "00010010", 3 => "00010010", 
    4 => "00010100", 5 => "00010110", 6 => "00010111", 7 => "00011001", 
    8 => "00011011", 9 => "00011101", 10 => "00100000", 11 => "00100011", 
    12 => "00100101", 13 => "00101000", 14 => "00101011", 15 => "00101110", 
    16 => "00110010", 17 => "00110110", 18 => "00111011", 19 => "00111111", 
    20 => "01000100", 21 => "01001010", 22 => "01001111", 23 => "01010101", 
    24 => "01011100", 25 => "01100100", 26 => "01101100", 27 => "01110100", 
    28 => "01111101", 29 => "10001000", 30 => "10010011", 31 => "10011101");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

