// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module cfu_hls_cfu_hls_Pipeline_FFT_STAGE_FFT_BUTTERFLY (
        ap_clk,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        real_buf_address0,
        real_buf_ce0,
        real_buf_q0,
        real_buf_address1,
        real_buf_ce1,
        real_buf_we1,
        real_buf_d1,
        imag_buf_address0,
        imag_buf_ce0,
        imag_buf_q0,
        imag_buf_address1,
        imag_buf_ce1,
        imag_buf_we1,
        imag_buf_d1
);

parameter    ap_ST_fsm_pp0_stage0 = 2'd1;
parameter    ap_ST_fsm_pp0_stage1 = 2'd2;

input   ap_clk;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [10:0] real_buf_address0;
output   real_buf_ce0;
input  [31:0] real_buf_q0;
output  [10:0] real_buf_address1;
output   real_buf_ce1;
output   real_buf_we1;
output  [31:0] real_buf_d1;
output  [10:0] imag_buf_address0;
output   imag_buf_ce0;
input  [31:0] imag_buf_q0;
output  [10:0] imag_buf_address1;
output   imag_buf_ce1;
output   imag_buf_we1;
output  [31:0] imag_buf_d1;

reg ap_idle;

(* fsm_encoding = "auto" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_pp0_stage1_subdone;
reg    ap_enable_reg_pp0_iter0_reg;
reg   [0:0] icmp_ln88_reg_498;
reg    ap_condition_exit_pp0_iter0_stage1;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [9:0] cos_table_fixed_address0;
wire   [17:0] cos_table_fixed_q0;
wire   [9:0] sin_table_fixed_address0;
wire   [16:0] sin_table_fixed_q0;
reg  signed [31:0] reg_172;
wire    ap_block_pp0_stage0_11001;
wire    ap_block_pp0_stage1_11001;
reg  signed [31:0] reg_176;
wire   [0:0] icmp_ln88_fu_198_p2;
wire   [13:0] add_ln88_fu_204_p2;
reg   [13:0] add_ln88_reg_502;
reg   [10:0] k_1_load_reg_507;
reg   [3:0] stage_load_reg_512;
wire   [0:0] icmp_ln92_fu_216_p2;
reg   [0:0] icmp_ln92_reg_518;
wire   [3:0] stage_13_fu_222_p2;
reg   [3:0] stage_13_reg_525;
wire   [10:0] select_ln88_fu_228_p3;
reg   [10:0] select_ln88_reg_531;
wire   [3:0] stage_1_mid1_fu_234_p2;
reg   [3:0] stage_1_mid1_reg_536;
wire   [3:0] select_ln88_2_fu_239_p3;
reg   [3:0] select_ln88_2_reg_541;
wire   [10:0] half_size_fu_252_p2;
reg   [10:0] half_size_reg_546;
reg   [10:0] half_size_reg_546_pp0_iter1_reg;
reg   [10:0] half_size_reg_546_pp0_iter2_reg;
wire  signed [9:0] trunc_ln101_fu_274_p1;
reg  signed [9:0] trunc_ln101_reg_551;
wire  signed [9:0] jj_fu_282_p2;
reg  signed [9:0] jj_reg_556;
wire   [9:0] trunc_ln98_fu_335_p1;
reg   [9:0] trunc_ln98_reg_562;
reg   [0:0] tmp_reg_567;
wire   [10:0] idx_fu_355_p3;
reg   [10:0] idx_reg_572;
reg   [10:0] idx_reg_572_pp0_iter2_reg;
reg   [10:0] idx_reg_572_pp0_iter3_reg;
reg   [10:0] idx_reg_572_pp0_iter4_reg;
reg   [10:0] idx_reg_572_pp0_iter5_reg;
wire   [10:0] idx2_fu_362_p2;
reg   [10:0] idx2_reg_578;
wire   [9:0] grp_fu_347_p2;
reg   [9:0] mul_ln101_reg_583;
reg   [10:0] real_buf_addr_reg_598;
reg   [10:0] real_buf_addr_reg_598_pp0_iter4_reg;
reg   [10:0] real_buf_addr_reg_598_pp0_iter5_reg;
reg   [10:0] real_buf_addr_reg_598_pp0_iter6_reg;
reg   [10:0] imag_buf_addr_reg_604;
reg   [10:0] imag_buf_addr_reg_604_pp0_iter4_reg;
reg   [10:0] imag_buf_addr_reg_604_pp0_iter5_reg;
reg   [10:0] imag_buf_addr_reg_604_pp0_iter6_reg;
reg   [17:0] wr_reg_610;
reg   [16:0] wi_reg_615;
wire  signed [47:0] sext_ln107_fu_376_p1;
wire  signed [47:0] sext_ln107_1_fu_382_p1;
wire  signed [47:0] sext_ln107_2_fu_387_p1;
wire  signed [47:0] sext_ln107_3_fu_393_p1;
reg   [10:0] real_buf_addr_1_reg_644;
reg   [10:0] real_buf_addr_1_reg_644_pp0_iter7_reg;
reg   [10:0] imag_buf_addr_1_reg_650;
reg   [10:0] imag_buf_addr_1_reg_650_pp0_iter7_reg;
wire   [31:0] tr_fu_423_p2;
reg   [31:0] tr_reg_656;
wire   [31:0] ti_fu_449_p2;
reg   [31:0] ti_reg_662;
wire   [31:0] add_ln111_fu_467_p2;
reg   [31:0] add_ln111_reg_668;
wire   [31:0] add_ln112_fu_472_p2;
reg   [31:0] add_ln112_reg_673;
wire   [63:0] zext_ln101_fu_366_p1;
wire    ap_block_pp0_stage1;
wire   [63:0] zext_ln103_fu_371_p1;
wire   [63:0] zext_ln105_fu_398_p1;
wire    ap_block_pp0_stage0;
reg   [10:0] k_1_fu_68;
wire   [10:0] k_fu_288_p2;
wire    ap_loop_init;
reg   [10:0] ap_sig_allocacmp_k_1_load;
reg   [3:0] stage_fu_72;
reg   [3:0] ap_sig_allocacmp_stage_load;
reg   [13:0] indvar_flatten_fu_76;
reg   [13:0] ap_sig_allocacmp_indvar_flatten_load;
reg    cos_table_fixed_ce0_local;
reg    sin_table_fixed_ce0_local;
reg    real_buf_ce0_local;
reg   [10:0] real_buf_address0_local;
reg    real_buf_we1_local;
reg   [31:0] real_buf_d1_local;
wire   [31:0] sub_ln109_fu_455_p2;
reg    real_buf_ce1_local;
reg   [10:0] real_buf_address1_local;
reg    imag_buf_ce0_local;
reg   [10:0] imag_buf_address0_local;
reg    imag_buf_we1_local;
reg   [31:0] imag_buf_d1_local;
wire   [31:0] sub_ln110_fu_461_p2;
reg    imag_buf_ce1_local;
reg   [10:0] imag_buf_address1_local;
wire  signed [31:0] grp_fu_156_p0;
wire  signed [16:0] grp_fu_156_p1;
wire  signed [31:0] grp_fu_160_p0;
wire  signed [16:0] grp_fu_160_p1;
wire  signed [31:0] grp_fu_164_p0;
wire  signed [17:0] grp_fu_164_p1;
wire  signed [31:0] grp_fu_168_p0;
wire  signed [17:0] grp_fu_168_p1;
wire   [10:0] zext_ln88_2_fu_248_p1;
wire   [20:0] zext_ln88_1_fu_244_p1;
wire   [9:0] trunc_ln89_fu_258_p1;
wire   [20:0] table_step_fu_262_p2;
wire   [9:0] trunc_ln92_fu_278_p1;
wire   [9:0] sub_fu_268_p2;
wire   [3:0] select_ln88_1_fu_308_p3;
wire   [11:0] zext_ln92_1_fu_320_p1;
wire   [11:0] zext_ln88_fu_313_p1;
wire   [11:0] group_fu_323_p2;
wire   [11:0] zext_ln92_fu_316_p1;
wire   [11:0] shl_ln98_fu_329_p2;
wire   [9:0] or_ln98_fu_351_p2;
wire   [47:0] grp_fu_164_p2;
wire   [47:0] grp_fu_156_p2;
wire   [31:0] trunc_ln6_fu_403_p4;
wire   [31:0] trunc_ln107_1_fu_413_p4;
wire   [47:0] grp_fu_168_p2;
wire   [47:0] grp_fu_160_p2;
wire   [31:0] trunc_ln7_fu_429_p4;
wire   [31:0] trunc_ln108_1_fu_439_p4;
wire   [31:0] sub_ln109_fu_455_p0;
wire   [31:0] sub_ln110_fu_461_p0;
wire   [31:0] add_ln111_fu_467_p0;
wire   [31:0] add_ln112_fu_472_p0;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg   [1:0] ap_NS_fsm;
wire    ap_block_pp0_stage0_subdone;
reg    ap_idle_pp0_1to7;
reg    ap_block_pp0;
wire    ap_enable_operation_75;
reg    ap_enable_state8_pp0_iter3_stage1;
wire    ap_enable_operation_80;
reg    ap_enable_state9_pp0_iter4_stage0;
wire    ap_enable_operation_120;
reg    ap_enable_state15_pp0_iter7_stage0;
wire    ap_enable_operation_128;
reg    ap_enable_state16_pp0_iter7_stage1;
wire    ap_enable_operation_77;
wire    ap_enable_operation_81;
wire    ap_enable_operation_122;
wire    ap_enable_operation_129;
wire    ap_enable_operation_100;
reg    ap_enable_state13_pp0_iter6_stage0;
wire    ap_enable_operation_107;
reg    ap_enable_state14_pp0_iter6_stage1;
wire    ap_enable_operation_102;
wire    ap_enable_operation_108;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 k_1_fu_68 = 11'd0;
#0 stage_fu_72 = 4'd0;
#0 indvar_flatten_fu_76 = 14'd0;
#0 ap_done_reg = 1'b0;
end

cfu_hls_cfu_hls_Pipeline_FFT_STAGE_FFT_BUTTERFLY_cos_table_fixed_ROM_AUTO_1R #(
    .DataWidth( 18 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
cos_table_fixed_U(
    .clk(ap_clk),
    .reset(1'b0),
    .address0(cos_table_fixed_address0),
    .ce0(cos_table_fixed_ce0_local),
    .q0(cos_table_fixed_q0)
);

cfu_hls_cfu_hls_Pipeline_FFT_STAGE_FFT_BUTTERFLY_sin_table_fixed_ROM_AUTO_1R #(
    .DataWidth( 17 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
sin_table_fixed_U(
    .clk(ap_clk),
    .reset(1'b0),
    .address0(sin_table_fixed_address0),
    .ce0(sin_table_fixed_ce0_local),
    .q0(sin_table_fixed_q0)
);

cfu_hls_mul_32s_17s_48_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 17 ),
    .dout_WIDTH( 48 ))
mul_32s_17s_48_5_1_U9(
    .clk(ap_clk),
    .reset(1'b0),
    .din0(grp_fu_156_p0),
    .din1(grp_fu_156_p1),
    .ce(1'b1),
    .dout(grp_fu_156_p2)
);

cfu_hls_mul_32s_17s_48_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 17 ),
    .dout_WIDTH( 48 ))
mul_32s_17s_48_5_1_U10(
    .clk(ap_clk),
    .reset(1'b0),
    .din0(grp_fu_160_p0),
    .din1(grp_fu_160_p1),
    .ce(1'b1),
    .dout(grp_fu_160_p2)
);

cfu_hls_mul_32s_18s_48_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 18 ),
    .dout_WIDTH( 48 ))
mul_32s_18s_48_5_1_U11(
    .clk(ap_clk),
    .reset(1'b0),
    .din0(grp_fu_164_p0),
    .din1(grp_fu_164_p1),
    .ce(1'b1),
    .dout(grp_fu_164_p2)
);

cfu_hls_mul_32s_18s_48_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 18 ),
    .dout_WIDTH( 48 ))
mul_32s_18s_48_5_1_U12(
    .clk(ap_clk),
    .reset(1'b0),
    .din0(grp_fu_168_p0),
    .din1(grp_fu_168_p1),
    .ce(1'b1),
    .dout(grp_fu_168_p2)
);

cfu_hls_mul_10s_10s_10_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 10 ))
mul_10s_10s_10_5_1_U13(
    .clk(ap_clk),
    .reset(1'b0),
    .din0(jj_reg_556),
    .din1(trunc_ln101_reg_551),
    .ce(1'b1),
    .dout(grp_fu_347_p2)
);

cfu_hls_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(1'b0),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage1),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    ap_CS_fsm <= ap_NS_fsm;
end

always @ (posedge ap_clk) begin
    if ((ap_continue_int == 1'b1)) begin
        ap_done_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_subdone) & (ap_loop_exit_ready_pp0_iter6_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_done_reg <= 1'b1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_exit_pp0_iter0_stage1)) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        indvar_flatten_fu_76 <= 14'd0;
    end else if (((icmp_ln88_reg_498 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        indvar_flatten_fu_76 <= add_ln88_reg_502;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        k_1_fu_68 <= 11'd0;
    end else if (((icmp_ln88_reg_498 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        k_1_fu_68 <= k_fu_288_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        stage_fu_72 <= 4'd0;
    end else if (((icmp_ln88_reg_498 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        stage_fu_72 <= select_ln88_2_fu_239_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln111_reg_668 <= add_ln111_fu_467_p2;
        add_ln112_reg_673 <= add_ln112_fu_472_p2;
        add_ln88_reg_502 <= add_ln88_fu_204_p2;
        icmp_ln88_reg_498 <= icmp_ln88_fu_198_p2;
        icmp_ln92_reg_518 <= icmp_ln92_fu_216_p2;
        idx2_reg_578 <= idx2_fu_362_p2;
        imag_buf_addr_1_reg_650 <= zext_ln105_fu_398_p1;
        imag_buf_addr_1_reg_650_pp0_iter7_reg <= imag_buf_addr_1_reg_650;
        k_1_load_reg_507 <= ap_sig_allocacmp_k_1_load;
        mul_ln101_reg_583 <= grp_fu_347_p2;
        real_buf_addr_1_reg_644 <= zext_ln105_fu_398_p1;
        real_buf_addr_1_reg_644_pp0_iter7_reg <= real_buf_addr_1_reg_644;
        stage_13_reg_525 <= stage_13_fu_222_p2;
        stage_load_reg_512 <= ap_sig_allocacmp_stage_load;
        tmp_reg_567 <= shl_ln98_fu_329_p2[32'd10];
        trunc_ln98_reg_562 <= trunc_ln98_fu_335_p1;
        wi_reg_615 <= sin_table_fixed_q0;
        wr_reg_610 <= cos_table_fixed_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0_reg <= ap_start_int;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        half_size_reg_546 <= half_size_fu_252_p2;
        half_size_reg_546_pp0_iter1_reg <= half_size_reg_546;
        half_size_reg_546_pp0_iter2_reg <= half_size_reg_546_pp0_iter1_reg;
        idx_reg_572 <= idx_fu_355_p3;
        idx_reg_572_pp0_iter2_reg <= idx_reg_572;
        idx_reg_572_pp0_iter3_reg <= idx_reg_572_pp0_iter2_reg;
        idx_reg_572_pp0_iter4_reg <= idx_reg_572_pp0_iter3_reg;
        idx_reg_572_pp0_iter5_reg <= idx_reg_572_pp0_iter4_reg;
        imag_buf_addr_reg_604 <= zext_ln103_fu_371_p1;
        imag_buf_addr_reg_604_pp0_iter4_reg <= imag_buf_addr_reg_604;
        imag_buf_addr_reg_604_pp0_iter5_reg <= imag_buf_addr_reg_604_pp0_iter4_reg;
        imag_buf_addr_reg_604_pp0_iter6_reg <= imag_buf_addr_reg_604_pp0_iter5_reg;
        jj_reg_556 <= jj_fu_282_p2;
        real_buf_addr_reg_598 <= zext_ln103_fu_371_p1;
        real_buf_addr_reg_598_pp0_iter4_reg <= real_buf_addr_reg_598;
        real_buf_addr_reg_598_pp0_iter5_reg <= real_buf_addr_reg_598_pp0_iter4_reg;
        real_buf_addr_reg_598_pp0_iter6_reg <= real_buf_addr_reg_598_pp0_iter5_reg;
        select_ln88_2_reg_541 <= select_ln88_2_fu_239_p3;
        select_ln88_reg_531 <= select_ln88_fu_228_p3;
        stage_1_mid1_reg_536 <= stage_1_mid1_fu_234_p2;
        ti_reg_662 <= ti_fu_449_p2;
        tr_reg_656 <= tr_fu_423_p2;
        trunc_ln101_reg_551 <= trunc_ln101_fu_274_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter6 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        reg_172 <= real_buf_q0;
        reg_176 <= imag_buf_q0;
    end
end

always @ (*) begin
    if (((icmp_ln88_reg_498 == 1'd1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_subdone) & (ap_loop_exit_ready_pp0_iter6_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0_1to7 = 1'b1;
    end else begin
        ap_idle_pp0_1to7 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten_load = 14'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten_load = indvar_flatten_fu_76;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_k_1_load = 11'd0;
    end else begin
        ap_sig_allocacmp_k_1_load = k_1_fu_68;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_stage_load = 4'd0;
    end else begin
        ap_sig_allocacmp_stage_load = stage_fu_72;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        cos_table_fixed_ce0_local = 1'b1;
    end else begin
        cos_table_fixed_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter6 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        imag_buf_address0_local = zext_ln105_fu_398_p1;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        imag_buf_address0_local = zext_ln103_fu_371_p1;
    end else begin
        imag_buf_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter7 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            imag_buf_address1_local = imag_buf_addr_1_reg_650_pp0_iter7_reg;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            imag_buf_address1_local = imag_buf_addr_reg_604_pp0_iter6_reg;
        end else begin
            imag_buf_address1_local = 'bx;
        end
    end else begin
        imag_buf_address1_local = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter6 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        imag_buf_ce0_local = 1'b1;
    end else begin
        imag_buf_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter7 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter7 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        imag_buf_ce1_local = 1'b1;
    end else begin
        imag_buf_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter7 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            imag_buf_d1_local = add_ln112_reg_673;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            imag_buf_d1_local = sub_ln110_fu_461_p2;
        end else begin
            imag_buf_d1_local = 'bx;
        end
    end else begin
        imag_buf_d1_local = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter7 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter7 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        imag_buf_we1_local = 1'b1;
    end else begin
        imag_buf_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter6 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        real_buf_address0_local = zext_ln105_fu_398_p1;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        real_buf_address0_local = zext_ln103_fu_371_p1;
    end else begin
        real_buf_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter7 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            real_buf_address1_local = real_buf_addr_1_reg_644_pp0_iter7_reg;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            real_buf_address1_local = real_buf_addr_reg_598_pp0_iter6_reg;
        end else begin
            real_buf_address1_local = 'bx;
        end
    end else begin
        real_buf_address1_local = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter6 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        real_buf_ce0_local = 1'b1;
    end else begin
        real_buf_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter7 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter7 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        real_buf_ce1_local = 1'b1;
    end else begin
        real_buf_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter7 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            real_buf_d1_local = add_ln111_reg_668;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            real_buf_d1_local = sub_ln109_fu_455_p2;
        end else begin
            real_buf_d1_local = 'bx;
        end
    end else begin
        real_buf_d1_local = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter7 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter7 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        real_buf_we1_local = 1'b1;
    end else begin
        real_buf_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        sin_table_fixed_ce0_local = 1'b1;
    end else begin
        sin_table_fixed_ce0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_start_int == 1'b0) & (ap_idle_pp0_1to7 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln111_fu_467_p0 = reg_172;

assign add_ln111_fu_467_p2 = (add_ln111_fu_467_p0 + tr_reg_656);

assign add_ln112_fu_472_p0 = reg_176;

assign add_ln112_fu_472_p2 = (add_ln112_fu_472_p0 + ti_reg_662);

assign add_ln88_fu_204_p2 = (ap_sig_allocacmp_indvar_flatten_load + 14'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

always @ (*) begin
    ap_block_pp0 = (((ap_ST_fsm_pp0_stage1 == ap_CS_fsm) & (1'b1 == ap_block_pp0_stage1_subdone)) | ((ap_ST_fsm_pp0_stage0 == ap_CS_fsm) & (1'b1 == ap_block_pp0_stage0_subdone)));
end

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_operation_100 = (1'b1 == 1'b1);

assign ap_enable_operation_102 = (1'b1 == 1'b1);

assign ap_enable_operation_107 = (1'b1 == 1'b1);

assign ap_enable_operation_108 = (1'b1 == 1'b1);

assign ap_enable_operation_120 = (1'b1 == 1'b1);

assign ap_enable_operation_122 = (1'b1 == 1'b1);

assign ap_enable_operation_128 = (1'b1 == 1'b1);

assign ap_enable_operation_129 = (1'b1 == 1'b1);

assign ap_enable_operation_75 = (1'b1 == 1'b1);

assign ap_enable_operation_77 = (1'b1 == 1'b1);

assign ap_enable_operation_80 = (1'b1 == 1'b1);

assign ap_enable_operation_81 = (1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

always @ (*) begin
    ap_enable_state13_pp0_iter6_stage0 = ((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_enable_state14_pp0_iter6_stage1 = ((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1));
end

always @ (*) begin
    ap_enable_state15_pp0_iter7_stage0 = ((ap_enable_reg_pp0_iter7 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_enable_state16_pp0_iter7_stage1 = ((ap_enable_reg_pp0_iter7 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1));
end

always @ (*) begin
    ap_enable_state8_pp0_iter3_stage1 = ((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1));
end

always @ (*) begin
    ap_enable_state9_pp0_iter4_stage0 = ((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage1;

assign ap_ready = ap_ready_sig;

assign cos_table_fixed_address0 = zext_ln101_fu_366_p1;

assign group_fu_323_p2 = zext_ln92_1_fu_320_p1 >> zext_ln88_fu_313_p1;

assign grp_fu_156_p0 = sext_ln107_2_fu_387_p1;

assign grp_fu_156_p1 = sext_ln107_3_fu_393_p1;

assign grp_fu_160_p0 = sext_ln107_fu_376_p1;

assign grp_fu_160_p1 = sext_ln107_3_fu_393_p1;

assign grp_fu_164_p0 = sext_ln107_fu_376_p1;

assign grp_fu_164_p1 = sext_ln107_1_fu_382_p1;

assign grp_fu_168_p0 = sext_ln107_2_fu_387_p1;

assign grp_fu_168_p1 = sext_ln107_1_fu_382_p1;

assign half_size_fu_252_p2 = 11'd1 << zext_ln88_2_fu_248_p1;

assign icmp_ln88_fu_198_p2 = ((ap_sig_allocacmp_indvar_flatten_load == 14'd11264) ? 1'b1 : 1'b0);

assign icmp_ln92_fu_216_p2 = ((ap_sig_allocacmp_k_1_load == 11'd1024) ? 1'b1 : 1'b0);

assign idx2_fu_362_p2 = (idx_reg_572_pp0_iter2_reg + half_size_reg_546_pp0_iter2_reg);

assign idx_fu_355_p3 = {{tmp_reg_567}, {or_ln98_fu_351_p2}};

assign imag_buf_address0 = imag_buf_address0_local;

assign imag_buf_address1 = imag_buf_address1_local;

assign imag_buf_ce0 = imag_buf_ce0_local;

assign imag_buf_ce1 = imag_buf_ce1_local;

assign imag_buf_d1 = imag_buf_d1_local;

assign imag_buf_we1 = imag_buf_we1_local;

assign jj_fu_282_p2 = (trunc_ln92_fu_278_p1 & sub_fu_268_p2);

assign k_fu_288_p2 = (select_ln88_fu_228_p3 + 11'd1);

assign or_ln98_fu_351_p2 = (trunc_ln98_reg_562 | jj_reg_556);

assign real_buf_address0 = real_buf_address0_local;

assign real_buf_address1 = real_buf_address1_local;

assign real_buf_ce0 = real_buf_ce0_local;

assign real_buf_ce1 = real_buf_ce1_local;

assign real_buf_d1 = real_buf_d1_local;

assign real_buf_we1 = real_buf_we1_local;

assign select_ln88_1_fu_308_p3 = ((icmp_ln92_reg_518[0:0] == 1'b1) ? stage_1_mid1_reg_536 : stage_13_reg_525);

assign select_ln88_2_fu_239_p3 = ((icmp_ln92_reg_518[0:0] == 1'b1) ? stage_13_reg_525 : stage_load_reg_512);

assign select_ln88_fu_228_p3 = ((icmp_ln92_reg_518[0:0] == 1'b1) ? 11'd0 : k_1_load_reg_507);

assign sext_ln107_1_fu_382_p1 = $signed(wr_reg_610);

assign sext_ln107_2_fu_387_p1 = reg_176;

assign sext_ln107_3_fu_393_p1 = $signed(wi_reg_615);

assign sext_ln107_fu_376_p1 = reg_172;

assign shl_ln98_fu_329_p2 = group_fu_323_p2 << zext_ln92_fu_316_p1;

assign sin_table_fixed_address0 = zext_ln101_fu_366_p1;

assign stage_13_fu_222_p2 = (ap_sig_allocacmp_stage_load + 4'd1);

assign stage_1_mid1_fu_234_p2 = (stage_load_reg_512 + 4'd2);

assign sub_fu_268_p2 = ($signed(trunc_ln89_fu_258_p1) + $signed(10'd1023));

assign sub_ln109_fu_455_p0 = reg_172;

assign sub_ln109_fu_455_p2 = (sub_ln109_fu_455_p0 - tr_reg_656);

assign sub_ln110_fu_461_p0 = reg_176;

assign sub_ln110_fu_461_p2 = (sub_ln110_fu_461_p0 - ti_reg_662);

assign table_step_fu_262_p2 = 21'd1024 >> zext_ln88_1_fu_244_p1;

assign ti_fu_449_p2 = (trunc_ln7_fu_429_p4 + trunc_ln108_1_fu_439_p4);

assign tr_fu_423_p2 = (trunc_ln6_fu_403_p4 - trunc_ln107_1_fu_413_p4);

assign trunc_ln101_fu_274_p1 = table_step_fu_262_p2[9:0];

assign trunc_ln107_1_fu_413_p4 = {{grp_fu_156_p2[47:16]}};

assign trunc_ln108_1_fu_439_p4 = {{grp_fu_160_p2[47:16]}};

assign trunc_ln6_fu_403_p4 = {{grp_fu_164_p2[47:16]}};

assign trunc_ln7_fu_429_p4 = {{grp_fu_168_p2[47:16]}};

assign trunc_ln89_fu_258_p1 = half_size_fu_252_p2[9:0];

assign trunc_ln92_fu_278_p1 = select_ln88_fu_228_p3[9:0];

assign trunc_ln98_fu_335_p1 = shl_ln98_fu_329_p2[9:0];

assign zext_ln101_fu_366_p1 = mul_ln101_reg_583;

assign zext_ln103_fu_371_p1 = idx2_reg_578;

assign zext_ln105_fu_398_p1 = idx_reg_572_pp0_iter5_reg;

assign zext_ln88_1_fu_244_p1 = select_ln88_2_fu_239_p3;

assign zext_ln88_2_fu_248_p1 = select_ln88_2_fu_239_p3;

assign zext_ln88_fu_313_p1 = select_ln88_2_reg_541;

assign zext_ln92_1_fu_320_p1 = select_ln88_reg_531;

assign zext_ln92_fu_316_p1 = select_ln88_1_fu_308_p3;

endmodule //cfu_hls_cfu_hls_Pipeline_FFT_STAGE_FFT_BUTTERFLY
