// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module cfu_hls_cfu_hls_Pipeline_HANN_LOOP (
        ap_clk,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        frame_buf_address0,
        frame_buf_ce0,
        frame_buf_q0,
        real_buf_address1,
        real_buf_ce1,
        real_buf_we1,
        real_buf_d1,
        imag_buf_address1,
        imag_buf_ce1,
        imag_buf_we1,
        imag_buf_d1
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [10:0] frame_buf_address0;
output   frame_buf_ce0;
input  [31:0] frame_buf_q0;
output  [10:0] real_buf_address1;
output   real_buf_ce1;
output   real_buf_we1;
output  [31:0] real_buf_d1;
output  [10:0] imag_buf_address1;
output   imag_buf_ce1;
output   imag_buf_we1;
output  [31:0] imag_buf_d1;

reg ap_idle;

(* fsm_encoding = "auto" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln55_fu_123_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [10:0] hann_window_fixed_address0;
wire   [16:0] hann_window_fixed_q0;
wire    ap_block_pp0_stage0_11001;
wire   [63:0] zext_ln55_fu_135_p1;
reg   [63:0] zext_ln55_reg_175;
reg   [63:0] zext_ln55_reg_175_pp0_iter1_reg;
reg   [63:0] zext_ln55_reg_175_pp0_iter2_reg;
reg   [63:0] zext_ln55_reg_175_pp0_iter3_reg;
reg   [63:0] zext_ln55_reg_175_pp0_iter4_reg;
reg   [63:0] zext_ln55_reg_175_pp0_iter5_reg;
reg   [63:0] zext_ln55_reg_175_pp0_iter6_reg;
reg  signed [31:0] frame_buf_load_reg_191;
reg   [16:0] hann_window_fixed_load_reg_196;
reg   [31:0] trunc_ln1_reg_211;
wire    ap_block_pp0_stage0;
reg   [11:0] i_fu_46;
wire   [11:0] add_ln55_fu_129_p2;
wire    ap_loop_init;
reg   [11:0] ap_sig_allocacmp_i_1;
reg    frame_buf_ce0_local;
reg    hann_window_fixed_ce0_local;
reg    imag_buf_we1_local;
reg    imag_buf_ce1_local;
reg    real_buf_we1_local;
reg    real_buf_ce1_local;
wire   [16:0] grp_fu_111_p0;
wire   [47:0] grp_fu_111_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [47:0] grp_fu_111_p00;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 i_fu_46 = 12'd0;
#0 ap_done_reg = 1'b0;
end

cfu_hls_cfu_hls_Pipeline_HANN_LOOP_hann_window_fixed_ROM_AUTO_1R #(
    .DataWidth( 17 ),
    .AddressRange( 2048 ),
    .AddressWidth( 11 ))
hann_window_fixed_U(
    .clk(ap_clk),
    .reset(1'b0),
    .address0(hann_window_fixed_address0),
    .ce0(hann_window_fixed_ce0_local),
    .q0(hann_window_fixed_q0)
);

cfu_hls_mul_17ns_32s_48_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 17 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 48 ))
mul_17ns_32s_48_5_1_U1(
    .clk(ap_clk),
    .reset(1'b0),
    .din0(grp_fu_111_p0),
    .din1(frame_buf_load_reg_191),
    .ce(1'b1),
    .dout(grp_fu_111_p2)
);

cfu_hls_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(1'b0),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    ap_CS_fsm <= ap_NS_fsm;
end

always @ (posedge ap_clk) begin
    if ((ap_continue_int == 1'b1)) begin
        ap_done_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter6_reg == 1'b1))) begin
        ap_done_reg <= 1'b1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_enable_reg_pp0_iter1 <= ap_start_int;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln55_fu_123_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_fu_46 <= add_ln55_fu_129_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_46 <= 12'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
        ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        frame_buf_load_reg_191 <= frame_buf_q0;
        hann_window_fixed_load_reg_196 <= hann_window_fixed_q0;
        zext_ln55_reg_175[11 : 0] <= zext_ln55_fu_135_p1[11 : 0];
        zext_ln55_reg_175_pp0_iter1_reg[11 : 0] <= zext_ln55_reg_175[11 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        trunc_ln1_reg_211 <= {{grp_fu_111_p2[47:16]}};
        zext_ln55_reg_175_pp0_iter2_reg[11 : 0] <= zext_ln55_reg_175_pp0_iter1_reg[11 : 0];
        zext_ln55_reg_175_pp0_iter3_reg[11 : 0] <= zext_ln55_reg_175_pp0_iter2_reg[11 : 0];
        zext_ln55_reg_175_pp0_iter4_reg[11 : 0] <= zext_ln55_reg_175_pp0_iter3_reg[11 : 0];
        zext_ln55_reg_175_pp0_iter5_reg[11 : 0] <= zext_ln55_reg_175_pp0_iter4_reg[11 : 0];
        zext_ln55_reg_175_pp0_iter6_reg[11 : 0] <= zext_ln55_reg_175_pp0_iter5_reg[11 : 0];
    end
end

always @ (*) begin
    if (((icmp_ln55_fu_123_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter6_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_1 = 12'd0;
    end else begin
        ap_sig_allocacmp_i_1 = i_fu_46;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        frame_buf_ce0_local = 1'b1;
    end else begin
        frame_buf_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        hann_window_fixed_ce0_local = 1'b1;
    end else begin
        hann_window_fixed_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        imag_buf_ce1_local = 1'b1;
    end else begin
        imag_buf_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        imag_buf_we1_local = 1'b1;
    end else begin
        imag_buf_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
        real_buf_ce1_local = 1'b1;
    end else begin
        real_buf_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
        real_buf_we1_local = 1'b1;
    end else begin
        real_buf_we1_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln55_fu_129_p2 = (ap_sig_allocacmp_i_1 + 12'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign frame_buf_address0 = zext_ln55_fu_135_p1;

assign frame_buf_ce0 = frame_buf_ce0_local;

assign grp_fu_111_p0 = grp_fu_111_p00;

assign grp_fu_111_p00 = hann_window_fixed_load_reg_196;

assign hann_window_fixed_address0 = zext_ln55_fu_135_p1;

assign icmp_ln55_fu_123_p2 = ((ap_sig_allocacmp_i_1 == 12'd2048) ? 1'b1 : 1'b0);

assign imag_buf_address1 = zext_ln55_reg_175;

assign imag_buf_ce1 = imag_buf_ce1_local;

assign imag_buf_d1 = 32'd0;

assign imag_buf_we1 = imag_buf_we1_local;

assign real_buf_address1 = zext_ln55_reg_175_pp0_iter6_reg;

assign real_buf_ce1 = real_buf_ce1_local;

assign real_buf_d1 = trunc_ln1_reg_211;

assign real_buf_we1 = real_buf_we1_local;

assign zext_ln55_fu_135_p1 = ap_sig_allocacmp_i_1;

always @ (posedge ap_clk) begin
    zext_ln55_reg_175[63:12] <= 52'b0000000000000000000000000000000000000000000000000000;
    zext_ln55_reg_175_pp0_iter1_reg[63:12] <= 52'b0000000000000000000000000000000000000000000000000000;
    zext_ln55_reg_175_pp0_iter2_reg[63:12] <= 52'b0000000000000000000000000000000000000000000000000000;
    zext_ln55_reg_175_pp0_iter3_reg[63:12] <= 52'b0000000000000000000000000000000000000000000000000000;
    zext_ln55_reg_175_pp0_iter4_reg[63:12] <= 52'b0000000000000000000000000000000000000000000000000000;
    zext_ln55_reg_175_pp0_iter5_reg[63:12] <= 52'b0000000000000000000000000000000000000000000000000000;
    zext_ln55_reg_175_pp0_iter6_reg[63:12] <= 52'b0000000000000000000000000000000000000000000000000000;
end

endmodule //cfu_hls_cfu_hls_Pipeline_HANN_LOOP
