// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="cfu_hls_cfu_hls,hls_ip_2024_2,{HLS_INPUT_TYPE=c,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a35t-csg324-1,HLS_INPUT_CLOCK=5.556000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.604000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=23,HLS_SYN_DSP=0,HLS_SYN_FF=4537,HLS_SYN_LUT=3140,HLS_VERSION=2024_2}" *)

module cfu_hls (
        ap_clk,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        funct3_i,
        funct7_i,
        src1_i,
        src2_i,
        rslt_o
);

parameter    ap_ST_fsm_state1 = 34'd1;
parameter    ap_ST_fsm_state2 = 34'd2;
parameter    ap_ST_fsm_state3 = 34'd4;
parameter    ap_ST_fsm_state4 = 34'd8;
parameter    ap_ST_fsm_state5 = 34'd16;
parameter    ap_ST_fsm_state6 = 34'd32;
parameter    ap_ST_fsm_state7 = 34'd64;
parameter    ap_ST_fsm_state8 = 34'd128;
parameter    ap_ST_fsm_state9 = 34'd256;
parameter    ap_ST_fsm_state10 = 34'd512;
parameter    ap_ST_fsm_state11 = 34'd1024;
parameter    ap_ST_fsm_state12 = 34'd2048;
parameter    ap_ST_fsm_state13 = 34'd4096;
parameter    ap_ST_fsm_state14 = 34'd8192;
parameter    ap_ST_fsm_state15 = 34'd16384;
parameter    ap_ST_fsm_state16 = 34'd32768;
parameter    ap_ST_fsm_state17 = 34'd65536;
parameter    ap_ST_fsm_state18 = 34'd131072;
parameter    ap_ST_fsm_state19 = 34'd262144;
parameter    ap_ST_fsm_state20 = 34'd524288;
parameter    ap_ST_fsm_state21 = 34'd1048576;
parameter    ap_ST_fsm_state22 = 34'd2097152;
parameter    ap_ST_fsm_state23 = 34'd4194304;
parameter    ap_ST_fsm_state24 = 34'd8388608;
parameter    ap_ST_fsm_state25 = 34'd16777216;
parameter    ap_ST_fsm_state26 = 34'd33554432;
parameter    ap_ST_fsm_state27 = 34'd67108864;
parameter    ap_ST_fsm_state28 = 34'd134217728;
parameter    ap_ST_fsm_state29 = 34'd268435456;
parameter    ap_ST_fsm_state30 = 34'd536870912;
parameter    ap_ST_fsm_state31 = 34'd1073741824;
parameter    ap_ST_fsm_state32 = 34'd2147483648;
parameter    ap_ST_fsm_state33 = 34'd4294967296;
parameter    ap_ST_fsm_state34 = 34'd8589934592;

input   ap_clk;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [7:0] funct3_i;
input  [7:0] funct7_i;
input  [31:0] src1_i;
input  [31:0] src2_i;
output  [31:0] rslt_o;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "auto" *) reg   [33:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [7:0] funct7_i_0_data_reg;
reg    funct7_i_0_vld_reg;
reg    funct7_i_0_ack_out;
reg   [31:0] src1_i_0_data_reg;
reg    src1_i_0_vld_reg;
reg    src1_i_0_ack_out;
reg   [31:0] src2_i_0_data_reg;
reg    src2_i_0_vld_reg;
reg    src2_i_0_ack_out;
reg   [31:0] rslt_o_1_data_reg;
reg   [31:0] rslt_o_1_data_in;
reg    rslt_o_1_vld_reg;
reg    rslt_o_1_vld_in;
reg    rslt_o_1_ack_in;
reg   [10:0] frame_buf_address0;
reg    frame_buf_ce0;
wire   [31:0] frame_buf_q0;
reg   [10:0] real_buf_address0;
reg    real_buf_ce0;
wire   [31:0] real_buf_q0;
reg   [10:0] real_buf_address1;
reg    real_buf_ce1;
reg    real_buf_we1;
reg   [31:0] real_buf_d1;
wire   [31:0] real_buf_q1;
reg   [10:0] imag_buf_address0;
reg    imag_buf_ce0;
wire   [31:0] imag_buf_q0;
reg   [10:0] imag_buf_address1;
reg    imag_buf_ce1;
reg    imag_buf_we1;
reg   [31:0] imag_buf_d1;
wire   [31:0] imag_buf_q1;
reg   [10:0] power_buf_address0;
reg    power_buf_ce0;
reg    power_buf_we0;
wire   [31:0] power_buf_q0;
wire   [4:0] mel_k_start_fixed_address0;
wire   [9:0] mel_k_start_fixed_q0;
wire   [4:0] mel_k_len_fixed_address0;
wire   [7:0] mel_k_len_fixed_q0;
wire   [31:0] mel_out_q0;
reg   [31:0] src2_i_read_reg_1051;
wire    ap_CS_fsm_state2;
wire   [7:0] grp_read_fu_282_p2;
reg   [7:0] funct7_i_read_reg_1056;
wire   [10:0] trunc_ln23_1_fu_543_p1;
reg   [10:0] trunc_ln23_1_reg_1060;
wire    ap_CS_fsm_state3;
wire   [5:0] add_ln129_fu_571_p2;
reg   [5:0] add_ln129_reg_1092;
wire    ap_CS_fsm_state12;
wire   [63:0] zext_ln129_fu_577_p1;
reg   [63:0] zext_ln129_reg_1097;
wire    ap_CS_fsm_state13;
reg   [7:0] k_len_reg_1113;
reg   [9:0] k_start_reg_1121;
wire    ap_CS_fsm_state14;
wire   [12:0] weight_idx_4_fu_588_p2;
reg   [12:0] weight_idx_4_reg_1126;
wire   [31:0] mel_q16_fu_597_p4;
reg   [31:0] mel_q16_reg_1132;
wire    ap_CS_fsm_state17;
wire   [0:0] icmp_ln140_fu_607_p2;
reg   [0:0] icmp_ln140_reg_1137;
wire   [15:0] trunc_ln139_fu_619_p1;
reg   [15:0] trunc_ln139_reg_1142;
wire    ap_CS_fsm_state18;
wire   [4:0] zext_ln147_fu_871_p1;
wire   [31:0] zext_ln143_fu_875_p1;
reg   [31:0] zext_ln143_reg_1242;
wire    ap_CS_fsm_state19;
wire   [15:0] trunc_ln149_fu_885_p1;
reg   [15:0] trunc_ln149_reg_1247;
wire   [15:0] sub_ln149_fu_897_p2;
reg   [15:0] sub_ln149_reg_1252;
wire    ap_CS_fsm_state20;
wire    ap_CS_fsm_state21;
wire   [31:0] grp_fu_908_p2;
reg   [31:0] frac_reg_1262;
wire    ap_CS_fsm_state22;
wire   [31:0] add_ln151_fu_913_p2;
reg   [31:0] add_ln151_reg_1267;
wire    ap_CS_fsm_state23;
wire  signed [31:0] log2_float_fu_930_p2;
reg  signed [31:0] log2_float_reg_1272;
wire    ap_CS_fsm_state24;
wire   [29:0] trunc_ln152_fu_935_p1;
reg   [29:0] trunc_ln152_reg_1282;
wire   [47:0] sub_ln152_fu_953_p2;
reg   [47:0] sub_ln152_reg_1287;
wire    ap_CS_fsm_state25;
wire   [47:0] add_ln152_fu_970_p2;
reg   [47:0] add_ln152_reg_1292;
wire    ap_CS_fsm_state26;
wire   [47:0] add_ln152_1_fu_986_p2;
reg   [47:0] add_ln152_1_reg_1297;
wire    ap_CS_fsm_state27;
wire   [47:0] add_ln152_2_fu_1002_p2;
reg   [47:0] add_ln152_2_reg_1302;
wire    ap_CS_fsm_state28;
wire   [47:0] add_ln152_3_fu_1018_p2;
reg   [47:0] add_ln152_3_reg_1307;
wire    ap_CS_fsm_state29;
reg   [31:0] trunc_ln_reg_1312;
wire    ap_CS_fsm_state30;
wire    grp_cfu_hls_Pipeline_HANN_LOOP_fu_485_ap_start;
wire    grp_cfu_hls_Pipeline_HANN_LOOP_fu_485_ap_done;
wire    grp_cfu_hls_Pipeline_HANN_LOOP_fu_485_ap_idle;
wire    grp_cfu_hls_Pipeline_HANN_LOOP_fu_485_ap_ready;
wire   [10:0] grp_cfu_hls_Pipeline_HANN_LOOP_fu_485_frame_buf_address0;
wire    grp_cfu_hls_Pipeline_HANN_LOOP_fu_485_frame_buf_ce0;
wire   [10:0] grp_cfu_hls_Pipeline_HANN_LOOP_fu_485_real_buf_address1;
wire    grp_cfu_hls_Pipeline_HANN_LOOP_fu_485_real_buf_ce1;
wire    grp_cfu_hls_Pipeline_HANN_LOOP_fu_485_real_buf_we1;
wire   [31:0] grp_cfu_hls_Pipeline_HANN_LOOP_fu_485_real_buf_d1;
wire   [10:0] grp_cfu_hls_Pipeline_HANN_LOOP_fu_485_imag_buf_address1;
wire    grp_cfu_hls_Pipeline_HANN_LOOP_fu_485_imag_buf_ce1;
wire    grp_cfu_hls_Pipeline_HANN_LOOP_fu_485_imag_buf_we1;
wire   [31:0] grp_cfu_hls_Pipeline_HANN_LOOP_fu_485_imag_buf_d1;
wire    grp_cfu_hls_Pipeline_BITREV_LOOP_fu_497_ap_start;
wire    grp_cfu_hls_Pipeline_BITREV_LOOP_fu_497_ap_done;
wire    grp_cfu_hls_Pipeline_BITREV_LOOP_fu_497_ap_idle;
wire    grp_cfu_hls_Pipeline_BITREV_LOOP_fu_497_ap_ready;
wire   [10:0] grp_cfu_hls_Pipeline_BITREV_LOOP_fu_497_real_buf_address0;
wire    grp_cfu_hls_Pipeline_BITREV_LOOP_fu_497_real_buf_ce0;
wire   [10:0] grp_cfu_hls_Pipeline_BITREV_LOOP_fu_497_real_buf_address1;
wire    grp_cfu_hls_Pipeline_BITREV_LOOP_fu_497_real_buf_ce1;
wire    grp_cfu_hls_Pipeline_BITREV_LOOP_fu_497_real_buf_we1;
wire   [31:0] grp_cfu_hls_Pipeline_BITREV_LOOP_fu_497_real_buf_d1;
wire   [10:0] grp_cfu_hls_Pipeline_BITREV_LOOP_fu_497_imag_buf_address0;
wire    grp_cfu_hls_Pipeline_BITREV_LOOP_fu_497_imag_buf_ce0;
wire   [10:0] grp_cfu_hls_Pipeline_BITREV_LOOP_fu_497_imag_buf_address1;
wire    grp_cfu_hls_Pipeline_BITREV_LOOP_fu_497_imag_buf_ce1;
wire    grp_cfu_hls_Pipeline_BITREV_LOOP_fu_497_imag_buf_we1;
wire   [31:0] grp_cfu_hls_Pipeline_BITREV_LOOP_fu_497_imag_buf_d1;
wire    grp_cfu_hls_Pipeline_FFT_STAGE_FFT_BUTTERFLY_fu_505_ap_start;
wire    grp_cfu_hls_Pipeline_FFT_STAGE_FFT_BUTTERFLY_fu_505_ap_done;
wire    grp_cfu_hls_Pipeline_FFT_STAGE_FFT_BUTTERFLY_fu_505_ap_idle;
wire    grp_cfu_hls_Pipeline_FFT_STAGE_FFT_BUTTERFLY_fu_505_ap_ready;
wire   [10:0] grp_cfu_hls_Pipeline_FFT_STAGE_FFT_BUTTERFLY_fu_505_real_buf_address0;
wire    grp_cfu_hls_Pipeline_FFT_STAGE_FFT_BUTTERFLY_fu_505_real_buf_ce0;
wire   [10:0] grp_cfu_hls_Pipeline_FFT_STAGE_FFT_BUTTERFLY_fu_505_real_buf_address1;
wire    grp_cfu_hls_Pipeline_FFT_STAGE_FFT_BUTTERFLY_fu_505_real_buf_ce1;
wire    grp_cfu_hls_Pipeline_FFT_STAGE_FFT_BUTTERFLY_fu_505_real_buf_we1;
wire   [31:0] grp_cfu_hls_Pipeline_FFT_STAGE_FFT_BUTTERFLY_fu_505_real_buf_d1;
wire   [10:0] grp_cfu_hls_Pipeline_FFT_STAGE_FFT_BUTTERFLY_fu_505_imag_buf_address0;
wire    grp_cfu_hls_Pipeline_FFT_STAGE_FFT_BUTTERFLY_fu_505_imag_buf_ce0;
wire   [10:0] grp_cfu_hls_Pipeline_FFT_STAGE_FFT_BUTTERFLY_fu_505_imag_buf_address1;
wire    grp_cfu_hls_Pipeline_FFT_STAGE_FFT_BUTTERFLY_fu_505_imag_buf_ce1;
wire    grp_cfu_hls_Pipeline_FFT_STAGE_FFT_BUTTERFLY_fu_505_imag_buf_we1;
wire   [31:0] grp_cfu_hls_Pipeline_FFT_STAGE_FFT_BUTTERFLY_fu_505_imag_buf_d1;
wire    grp_cfu_hls_Pipeline_POWER_LOOP_fu_517_ap_start;
wire    grp_cfu_hls_Pipeline_POWER_LOOP_fu_517_ap_done;
wire    grp_cfu_hls_Pipeline_POWER_LOOP_fu_517_ap_idle;
wire    grp_cfu_hls_Pipeline_POWER_LOOP_fu_517_ap_ready;
wire   [10:0] grp_cfu_hls_Pipeline_POWER_LOOP_fu_517_real_buf_address0;
wire    grp_cfu_hls_Pipeline_POWER_LOOP_fu_517_real_buf_ce0;
wire   [10:0] grp_cfu_hls_Pipeline_POWER_LOOP_fu_517_imag_buf_address0;
wire    grp_cfu_hls_Pipeline_POWER_LOOP_fu_517_imag_buf_ce0;
wire   [10:0] grp_cfu_hls_Pipeline_POWER_LOOP_fu_517_power_buf_address0;
wire    grp_cfu_hls_Pipeline_POWER_LOOP_fu_517_power_buf_ce0;
wire    grp_cfu_hls_Pipeline_POWER_LOOP_fu_517_power_buf_we0;
wire   [31:0] grp_cfu_hls_Pipeline_POWER_LOOP_fu_517_power_buf_d0;
wire    grp_cfu_hls_Pipeline_MEL_ACCUM_fu_527_ap_start;
wire    grp_cfu_hls_Pipeline_MEL_ACCUM_fu_527_ap_done;
wire    grp_cfu_hls_Pipeline_MEL_ACCUM_fu_527_ap_idle;
wire    grp_cfu_hls_Pipeline_MEL_ACCUM_fu_527_ap_ready;
wire   [47:0] grp_cfu_hls_Pipeline_MEL_ACCUM_fu_527_mel_pwr_out;
wire    grp_cfu_hls_Pipeline_MEL_ACCUM_fu_527_mel_pwr_out_ap_vld;
wire   [10:0] grp_cfu_hls_Pipeline_MEL_ACCUM_fu_527_power_buf_address0;
wire    grp_cfu_hls_Pipeline_MEL_ACCUM_fu_527_power_buf_ce0;
reg   [4:0] msb_reg_357;
wire   [0:0] tmp_fu_623_p3;
wire   [0:0] tmp_1_fu_631_p3;
wire   [0:0] tmp_2_fu_639_p3;
wire   [0:0] tmp_3_fu_647_p3;
wire   [0:0] tmp_4_fu_655_p3;
wire   [0:0] tmp_5_fu_663_p3;
wire   [0:0] tmp_6_fu_671_p3;
wire   [0:0] tmp_7_fu_679_p3;
wire   [0:0] tmp_8_fu_687_p3;
wire   [0:0] tmp_9_fu_695_p3;
wire   [0:0] tmp_10_fu_703_p3;
wire   [0:0] tmp_11_fu_711_p3;
wire   [0:0] tmp_12_fu_719_p3;
wire   [0:0] tmp_13_fu_727_p3;
wire   [0:0] tmp_14_fu_735_p3;
wire   [0:0] tmp_15_fu_743_p3;
wire   [0:0] tmp_16_fu_751_p3;
wire   [0:0] tmp_17_fu_759_p3;
wire   [0:0] tmp_18_fu_767_p3;
wire   [0:0] tmp_19_fu_775_p3;
wire   [0:0] tmp_20_fu_783_p3;
wire   [0:0] tmp_21_fu_791_p3;
wire   [0:0] tmp_22_fu_799_p3;
wire   [0:0] tmp_23_fu_807_p3;
wire   [0:0] tmp_24_fu_815_p3;
wire   [0:0] tmp_25_fu_823_p3;
wire   [0:0] tmp_26_fu_831_p3;
wire   [0:0] tmp_27_fu_839_p3;
wire   [0:0] tmp_28_fu_847_p3;
wire   [0:0] tmp_29_fu_855_p3;
reg    grp_cfu_hls_Pipeline_HANN_LOOP_fu_485_ap_start_reg;
wire    ap_CS_fsm_state5;
reg    grp_cfu_hls_Pipeline_BITREV_LOOP_fu_497_ap_start_reg;
wire    ap_CS_fsm_state6;
wire    ap_CS_fsm_state7;
reg    grp_cfu_hls_Pipeline_FFT_STAGE_FFT_BUTTERFLY_fu_505_ap_start_reg;
wire    ap_CS_fsm_state8;
wire    ap_CS_fsm_state9;
reg    grp_cfu_hls_Pipeline_POWER_LOOP_fu_517_ap_start_reg;
wire    ap_CS_fsm_state10;
wire    ap_CS_fsm_state11;
reg    grp_cfu_hls_Pipeline_MEL_ACCUM_fu_527_ap_start_reg;
wire    ap_CS_fsm_state15;
wire    ap_CS_fsm_state16;
reg   [47:0] mel_pwr_loc_fu_258;
wire   [63:0] zext_ln161_fu_547_p1;
wire   [0:0] icmp_ln129_fu_565_p2;
wire    ap_CS_fsm_state31;
wire   [63:0] zext_ln45_fu_1041_p1;
wire    ap_CS_fsm_state33;
reg   [12:0] weight_idx_fu_262;
reg   [5:0] m_fu_266;
reg    mel_out_ce0_local;
reg   [4:0] mel_out_address0_local;
reg    mel_out_we0_local;
reg    mel_k_len_fixed_ce0_local;
reg    mel_k_start_fixed_ce0_local;
reg    frame_buf_we0_local;
reg    frame_buf_ce0_local;
wire   [4:0] trunc_ln23_fu_539_p1;
wire   [12:0] zext_ln132_fu_585_p1;
wire   [31:0] mel_q16_1_fu_613_p3;
wire   [0:0] tmp_30_fu_863_p3;
wire   [31:0] shl_ln149_fu_879_p2;
wire   [31:0] grp_fu_908_p0;
wire   [20:0] shl_ln_fu_918_p3;
wire   [31:0] zext_ln151_fu_926_p1;
wire   [47:0] p_shl_fu_939_p3;
wire   [47:0] p_shl1_fu_946_p3;
wire   [40:0] tmp_31_fu_959_p3;
wire  signed [47:0] sext_ln152_1_fu_966_p1;
wire   [38:0] tmp_32_fu_975_p3;
wire  signed [47:0] sext_ln152_2_fu_982_p1;
wire   [36:0] tmp_33_fu_991_p3;
wire  signed [47:0] sext_ln152_3_fu_998_p1;
wire   [33:0] tmp_34_fu_1007_p3;
wire  signed [47:0] sext_ln152_4_fu_1014_p1;
wire  signed [47:0] sext_ln152_fu_1023_p1;
wire   [47:0] sub_ln152_1_fu_1026_p2;
wire    ap_CS_fsm_state34;
reg   [33:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
reg    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
reg    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
reg    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
reg    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
wire    ap_ST_fsm_state19_blk;
wire    ap_ST_fsm_state20_blk;
wire    ap_ST_fsm_state21_blk;
wire    ap_ST_fsm_state22_blk;
wire    ap_ST_fsm_state23_blk;
wire    ap_ST_fsm_state24_blk;
wire    ap_ST_fsm_state25_blk;
wire    ap_ST_fsm_state26_blk;
wire    ap_ST_fsm_state27_blk;
wire    ap_ST_fsm_state28_blk;
wire    ap_ST_fsm_state29_blk;
wire    ap_ST_fsm_state30_blk;
wire    ap_ST_fsm_state31_blk;
wire    ap_ST_fsm_state32_blk;
wire    ap_ST_fsm_state33_blk;
reg    ap_ST_fsm_state34_blk;
reg    ap_condition_588;
reg    ap_condition_600;
reg    ap_condition_604;
reg    ap_condition_608;
reg    ap_condition_612;
reg    ap_condition_616;
reg    ap_condition_620;
reg    ap_condition_624;
reg    ap_condition_628;
reg    ap_condition_632;
reg    ap_condition_636;
reg    ap_condition_640;
reg    ap_condition_644;
reg    ap_condition_648;
reg    ap_condition_652;
reg    ap_condition_656;
reg    ap_condition_660;
reg    ap_condition_664;
reg    ap_condition_668;
reg    ap_condition_672;
reg    ap_condition_676;
reg    ap_condition_680;
reg    ap_condition_684;
reg    ap_condition_688;
reg    ap_condition_692;
reg    ap_condition_696;
reg    ap_condition_700;
reg    ap_condition_704;
reg    ap_condition_708;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 34'd1;
#0 funct7_i_0_data_reg = 8'd0;
#0 funct7_i_0_vld_reg = 1'b0;
#0 src1_i_0_data_reg = 32'd0;
#0 src1_i_0_vld_reg = 1'b0;
#0 src2_i_0_data_reg = 32'd0;
#0 src2_i_0_vld_reg = 1'b0;
#0 rslt_o_1_data_reg = 32'd0;
#0 rslt_o_1_vld_reg = 1'b0;
#0 grp_cfu_hls_Pipeline_HANN_LOOP_fu_485_ap_start_reg = 1'b0;
#0 grp_cfu_hls_Pipeline_BITREV_LOOP_fu_497_ap_start_reg = 1'b0;
#0 grp_cfu_hls_Pipeline_FFT_STAGE_FFT_BUTTERFLY_fu_505_ap_start_reg = 1'b0;
#0 grp_cfu_hls_Pipeline_POWER_LOOP_fu_517_ap_start_reg = 1'b0;
#0 grp_cfu_hls_Pipeline_MEL_ACCUM_fu_527_ap_start_reg = 1'b0;
#0 weight_idx_fu_262 = 13'd0;
#0 m_fu_266 = 6'd0;
end

cfu_hls_frame_buf_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 2048 ),
    .AddressWidth( 11 ))
frame_buf_U(
    .clk(ap_clk),
    .reset(1'b0),
    .address0(frame_buf_address0),
    .ce0(frame_buf_ce0),
    .we0(frame_buf_we0_local),
    .d0(src2_i_read_reg_1051),
    .q0(frame_buf_q0)
);

cfu_hls_real_buf_RAM_2P_BRAM_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 2048 ),
    .AddressWidth( 11 ))
real_buf_U(
    .clk(ap_clk),
    .reset(1'b0),
    .address0(real_buf_address0),
    .ce0(real_buf_ce0),
    .q0(real_buf_q0),
    .address1(real_buf_address1),
    .ce1(real_buf_ce1),
    .we1(real_buf_we1),
    .d1(real_buf_d1),
    .q1(real_buf_q1)
);

cfu_hls_real_buf_RAM_2P_BRAM_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 2048 ),
    .AddressWidth( 11 ))
imag_buf_U(
    .clk(ap_clk),
    .reset(1'b0),
    .address0(imag_buf_address0),
    .ce0(imag_buf_ce0),
    .q0(imag_buf_q0),
    .address1(imag_buf_address1),
    .ce1(imag_buf_ce1),
    .we1(imag_buf_we1),
    .d1(imag_buf_d1),
    .q1(imag_buf_q1)
);

cfu_hls_power_buf_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 1025 ),
    .AddressWidth( 11 ))
power_buf_U(
    .clk(ap_clk),
    .reset(1'b0),
    .address0(power_buf_address0),
    .ce0(power_buf_ce0),
    .we0(power_buf_we0),
    .d0(grp_cfu_hls_Pipeline_POWER_LOOP_fu_517_power_buf_d0),
    .q0(power_buf_q0)
);

cfu_hls_mel_k_start_fixed_ROM_AUTO_1R #(
    .DataWidth( 10 ),
    .AddressRange( 32 ),
    .AddressWidth( 5 ))
mel_k_start_fixed_U(
    .clk(ap_clk),
    .reset(1'b0),
    .address0(mel_k_start_fixed_address0),
    .ce0(mel_k_start_fixed_ce0_local),
    .q0(mel_k_start_fixed_q0)
);

cfu_hls_mel_k_len_fixed_ROM_AUTO_1R #(
    .DataWidth( 8 ),
    .AddressRange( 32 ),
    .AddressWidth( 5 ))
mel_k_len_fixed_U(
    .clk(ap_clk),
    .reset(1'b0),
    .address0(mel_k_len_fixed_address0),
    .ce0(mel_k_len_fixed_ce0_local),
    .q0(mel_k_len_fixed_q0)
);

cfu_hls_mel_out_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 32 ),
    .AddressWidth( 5 ))
mel_out_U(
    .clk(ap_clk),
    .reset(1'b0),
    .address0(mel_out_address0_local),
    .ce0(mel_out_ce0_local),
    .we0(mel_out_we0_local),
    .d0(trunc_ln_reg_1312),
    .q0(mel_out_q0)
);

cfu_hls_cfu_hls_Pipeline_HANN_LOOP grp_cfu_hls_Pipeline_HANN_LOOP_fu_485(
    .ap_clk(ap_clk),
    .ap_start(grp_cfu_hls_Pipeline_HANN_LOOP_fu_485_ap_start),
    .ap_done(grp_cfu_hls_Pipeline_HANN_LOOP_fu_485_ap_done),
    .ap_idle(grp_cfu_hls_Pipeline_HANN_LOOP_fu_485_ap_idle),
    .ap_ready(grp_cfu_hls_Pipeline_HANN_LOOP_fu_485_ap_ready),
    .frame_buf_address0(grp_cfu_hls_Pipeline_HANN_LOOP_fu_485_frame_buf_address0),
    .frame_buf_ce0(grp_cfu_hls_Pipeline_HANN_LOOP_fu_485_frame_buf_ce0),
    .frame_buf_q0(frame_buf_q0),
    .real_buf_address1(grp_cfu_hls_Pipeline_HANN_LOOP_fu_485_real_buf_address1),
    .real_buf_ce1(grp_cfu_hls_Pipeline_HANN_LOOP_fu_485_real_buf_ce1),
    .real_buf_we1(grp_cfu_hls_Pipeline_HANN_LOOP_fu_485_real_buf_we1),
    .real_buf_d1(grp_cfu_hls_Pipeline_HANN_LOOP_fu_485_real_buf_d1),
    .imag_buf_address1(grp_cfu_hls_Pipeline_HANN_LOOP_fu_485_imag_buf_address1),
    .imag_buf_ce1(grp_cfu_hls_Pipeline_HANN_LOOP_fu_485_imag_buf_ce1),
    .imag_buf_we1(grp_cfu_hls_Pipeline_HANN_LOOP_fu_485_imag_buf_we1),
    .imag_buf_d1(grp_cfu_hls_Pipeline_HANN_LOOP_fu_485_imag_buf_d1)
);

cfu_hls_cfu_hls_Pipeline_BITREV_LOOP grp_cfu_hls_Pipeline_BITREV_LOOP_fu_497(
    .ap_clk(ap_clk),
    .ap_start(grp_cfu_hls_Pipeline_BITREV_LOOP_fu_497_ap_start),
    .ap_done(grp_cfu_hls_Pipeline_BITREV_LOOP_fu_497_ap_done),
    .ap_idle(grp_cfu_hls_Pipeline_BITREV_LOOP_fu_497_ap_idle),
    .ap_ready(grp_cfu_hls_Pipeline_BITREV_LOOP_fu_497_ap_ready),
    .real_buf_address0(grp_cfu_hls_Pipeline_BITREV_LOOP_fu_497_real_buf_address0),
    .real_buf_ce0(grp_cfu_hls_Pipeline_BITREV_LOOP_fu_497_real_buf_ce0),
    .real_buf_q0(real_buf_q0),
    .real_buf_address1(grp_cfu_hls_Pipeline_BITREV_LOOP_fu_497_real_buf_address1),
    .real_buf_ce1(grp_cfu_hls_Pipeline_BITREV_LOOP_fu_497_real_buf_ce1),
    .real_buf_we1(grp_cfu_hls_Pipeline_BITREV_LOOP_fu_497_real_buf_we1),
    .real_buf_d1(grp_cfu_hls_Pipeline_BITREV_LOOP_fu_497_real_buf_d1),
    .real_buf_q1(real_buf_q1),
    .imag_buf_address0(grp_cfu_hls_Pipeline_BITREV_LOOP_fu_497_imag_buf_address0),
    .imag_buf_ce0(grp_cfu_hls_Pipeline_BITREV_LOOP_fu_497_imag_buf_ce0),
    .imag_buf_q0(imag_buf_q0),
    .imag_buf_address1(grp_cfu_hls_Pipeline_BITREV_LOOP_fu_497_imag_buf_address1),
    .imag_buf_ce1(grp_cfu_hls_Pipeline_BITREV_LOOP_fu_497_imag_buf_ce1),
    .imag_buf_we1(grp_cfu_hls_Pipeline_BITREV_LOOP_fu_497_imag_buf_we1),
    .imag_buf_d1(grp_cfu_hls_Pipeline_BITREV_LOOP_fu_497_imag_buf_d1),
    .imag_buf_q1(imag_buf_q1)
);

cfu_hls_cfu_hls_Pipeline_FFT_STAGE_FFT_BUTTERFLY grp_cfu_hls_Pipeline_FFT_STAGE_FFT_BUTTERFLY_fu_505(
    .ap_clk(ap_clk),
    .ap_start(grp_cfu_hls_Pipeline_FFT_STAGE_FFT_BUTTERFLY_fu_505_ap_start),
    .ap_done(grp_cfu_hls_Pipeline_FFT_STAGE_FFT_BUTTERFLY_fu_505_ap_done),
    .ap_idle(grp_cfu_hls_Pipeline_FFT_STAGE_FFT_BUTTERFLY_fu_505_ap_idle),
    .ap_ready(grp_cfu_hls_Pipeline_FFT_STAGE_FFT_BUTTERFLY_fu_505_ap_ready),
    .real_buf_address0(grp_cfu_hls_Pipeline_FFT_STAGE_FFT_BUTTERFLY_fu_505_real_buf_address0),
    .real_buf_ce0(grp_cfu_hls_Pipeline_FFT_STAGE_FFT_BUTTERFLY_fu_505_real_buf_ce0),
    .real_buf_q0(real_buf_q0),
    .real_buf_address1(grp_cfu_hls_Pipeline_FFT_STAGE_FFT_BUTTERFLY_fu_505_real_buf_address1),
    .real_buf_ce1(grp_cfu_hls_Pipeline_FFT_STAGE_FFT_BUTTERFLY_fu_505_real_buf_ce1),
    .real_buf_we1(grp_cfu_hls_Pipeline_FFT_STAGE_FFT_BUTTERFLY_fu_505_real_buf_we1),
    .real_buf_d1(grp_cfu_hls_Pipeline_FFT_STAGE_FFT_BUTTERFLY_fu_505_real_buf_d1),
    .imag_buf_address0(grp_cfu_hls_Pipeline_FFT_STAGE_FFT_BUTTERFLY_fu_505_imag_buf_address0),
    .imag_buf_ce0(grp_cfu_hls_Pipeline_FFT_STAGE_FFT_BUTTERFLY_fu_505_imag_buf_ce0),
    .imag_buf_q0(imag_buf_q0),
    .imag_buf_address1(grp_cfu_hls_Pipeline_FFT_STAGE_FFT_BUTTERFLY_fu_505_imag_buf_address1),
    .imag_buf_ce1(grp_cfu_hls_Pipeline_FFT_STAGE_FFT_BUTTERFLY_fu_505_imag_buf_ce1),
    .imag_buf_we1(grp_cfu_hls_Pipeline_FFT_STAGE_FFT_BUTTERFLY_fu_505_imag_buf_we1),
    .imag_buf_d1(grp_cfu_hls_Pipeline_FFT_STAGE_FFT_BUTTERFLY_fu_505_imag_buf_d1)
);

cfu_hls_cfu_hls_Pipeline_POWER_LOOP grp_cfu_hls_Pipeline_POWER_LOOP_fu_517(
    .ap_clk(ap_clk),
    .ap_start(grp_cfu_hls_Pipeline_POWER_LOOP_fu_517_ap_start),
    .ap_done(grp_cfu_hls_Pipeline_POWER_LOOP_fu_517_ap_done),
    .ap_idle(grp_cfu_hls_Pipeline_POWER_LOOP_fu_517_ap_idle),
    .ap_ready(grp_cfu_hls_Pipeline_POWER_LOOP_fu_517_ap_ready),
    .real_buf_address0(grp_cfu_hls_Pipeline_POWER_LOOP_fu_517_real_buf_address0),
    .real_buf_ce0(grp_cfu_hls_Pipeline_POWER_LOOP_fu_517_real_buf_ce0),
    .real_buf_q0(real_buf_q0),
    .imag_buf_address0(grp_cfu_hls_Pipeline_POWER_LOOP_fu_517_imag_buf_address0),
    .imag_buf_ce0(grp_cfu_hls_Pipeline_POWER_LOOP_fu_517_imag_buf_ce0),
    .imag_buf_q0(imag_buf_q0),
    .power_buf_address0(grp_cfu_hls_Pipeline_POWER_LOOP_fu_517_power_buf_address0),
    .power_buf_ce0(grp_cfu_hls_Pipeline_POWER_LOOP_fu_517_power_buf_ce0),
    .power_buf_we0(grp_cfu_hls_Pipeline_POWER_LOOP_fu_517_power_buf_we0),
    .power_buf_d0(grp_cfu_hls_Pipeline_POWER_LOOP_fu_517_power_buf_d0)
);

cfu_hls_cfu_hls_Pipeline_MEL_ACCUM grp_cfu_hls_Pipeline_MEL_ACCUM_fu_527(
    .ap_clk(ap_clk),
    .ap_start(grp_cfu_hls_Pipeline_MEL_ACCUM_fu_527_ap_start),
    .ap_done(grp_cfu_hls_Pipeline_MEL_ACCUM_fu_527_ap_done),
    .ap_idle(grp_cfu_hls_Pipeline_MEL_ACCUM_fu_527_ap_idle),
    .ap_ready(grp_cfu_hls_Pipeline_MEL_ACCUM_fu_527_ap_ready),
    .weight_idx(weight_idx_fu_262),
    .weight_idx_2(weight_idx_4_reg_1126),
    .k_start(k_start_reg_1121),
    .mel_pwr_out(grp_cfu_hls_Pipeline_MEL_ACCUM_fu_527_mel_pwr_out),
    .mel_pwr_out_ap_vld(grp_cfu_hls_Pipeline_MEL_ACCUM_fu_527_mel_pwr_out_ap_vld),
    .power_buf_address0(grp_cfu_hls_Pipeline_MEL_ACCUM_fu_527_power_buf_address0),
    .power_buf_ce0(grp_cfu_hls_Pipeline_MEL_ACCUM_fu_527_power_buf_ce0),
    .power_buf_q0(power_buf_q0)
);

cfu_hls_lshr_32ns_5ns_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .OP( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 5 ),
    .dout_WIDTH( 32 ))
lshr_32ns_5ns_32_2_1_U35(
    .clk(ap_clk),
    .reset(1'b0),
    .din0(grp_fu_908_p0),
    .din1(zext_ln143_reg_1242),
    .ce(1'b1),
    .dout(grp_fu_908_p2)
);

always @ (posedge ap_clk) begin
    ap_CS_fsm <= ap_NS_fsm;
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_cfu_hls_Pipeline_BITREV_LOOP_fu_497_ap_start_reg <= 1'b1;
    end else if ((grp_cfu_hls_Pipeline_BITREV_LOOP_fu_497_ap_ready == 1'b1)) begin
        grp_cfu_hls_Pipeline_BITREV_LOOP_fu_497_ap_start_reg <= 1'b0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        grp_cfu_hls_Pipeline_FFT_STAGE_FFT_BUTTERFLY_fu_505_ap_start_reg <= 1'b1;
    end else if ((grp_cfu_hls_Pipeline_FFT_STAGE_FFT_BUTTERFLY_fu_505_ap_ready == 1'b1)) begin
        grp_cfu_hls_Pipeline_FFT_STAGE_FFT_BUTTERFLY_fu_505_ap_start_reg <= 1'b0;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_read_fu_282_p2 == 8'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        grp_cfu_hls_Pipeline_HANN_LOOP_fu_485_ap_start_reg <= 1'b1;
    end else if ((grp_cfu_hls_Pipeline_HANN_LOOP_fu_485_ap_ready == 1'b1)) begin
        grp_cfu_hls_Pipeline_HANN_LOOP_fu_485_ap_start_reg <= 1'b0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        grp_cfu_hls_Pipeline_MEL_ACCUM_fu_527_ap_start_reg <= 1'b1;
    end else if ((grp_cfu_hls_Pipeline_MEL_ACCUM_fu_527_ap_ready == 1'b1)) begin
        grp_cfu_hls_Pipeline_MEL_ACCUM_fu_527_ap_start_reg <= 1'b0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        grp_cfu_hls_Pipeline_POWER_LOOP_fu_517_ap_start_reg <= 1'b1;
    end else if ((grp_cfu_hls_Pipeline_POWER_LOOP_fu_517_ap_ready == 1'b1)) begin
        grp_cfu_hls_Pipeline_POWER_LOOP_fu_517_ap_start_reg <= 1'b0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        m_fu_266 <= 6'd0;
    end else if ((1'b1 == ap_CS_fsm_state19)) begin
        m_fu_266 <= add_ln129_reg_1092;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        if ((1'b1 == ap_condition_708)) begin
            msb_reg_357 <= 5'd2;
        end else if ((1'b1 == ap_condition_704)) begin
            msb_reg_357 <= 5'd3;
        end else if ((1'b1 == ap_condition_700)) begin
            msb_reg_357 <= 5'd4;
        end else if ((1'b1 == ap_condition_696)) begin
            msb_reg_357 <= 5'd5;
        end else if ((1'b1 == ap_condition_692)) begin
            msb_reg_357 <= 5'd6;
        end else if ((1'b1 == ap_condition_688)) begin
            msb_reg_357 <= 5'd7;
        end else if ((1'b1 == ap_condition_684)) begin
            msb_reg_357 <= 5'd8;
        end else if ((1'b1 == ap_condition_680)) begin
            msb_reg_357 <= 5'd9;
        end else if ((1'b1 == ap_condition_676)) begin
            msb_reg_357 <= 5'd10;
        end else if ((1'b1 == ap_condition_672)) begin
            msb_reg_357 <= 5'd11;
        end else if ((1'b1 == ap_condition_668)) begin
            msb_reg_357 <= 5'd12;
        end else if ((1'b1 == ap_condition_664)) begin
            msb_reg_357 <= 5'd13;
        end else if ((1'b1 == ap_condition_660)) begin
            msb_reg_357 <= 5'd14;
        end else if ((1'b1 == ap_condition_656)) begin
            msb_reg_357 <= 5'd15;
        end else if ((1'b1 == ap_condition_652)) begin
            msb_reg_357 <= 5'd16;
        end else if ((1'b1 == ap_condition_648)) begin
            msb_reg_357 <= 5'd17;
        end else if ((1'b1 == ap_condition_644)) begin
            msb_reg_357 <= 5'd18;
        end else if ((1'b1 == ap_condition_640)) begin
            msb_reg_357 <= 5'd19;
        end else if ((1'b1 == ap_condition_636)) begin
            msb_reg_357 <= 5'd20;
        end else if ((1'b1 == ap_condition_632)) begin
            msb_reg_357 <= 5'd21;
        end else if ((1'b1 == ap_condition_628)) begin
            msb_reg_357 <= 5'd22;
        end else if ((1'b1 == ap_condition_624)) begin
            msb_reg_357 <= 5'd23;
        end else if ((1'b1 == ap_condition_620)) begin
            msb_reg_357 <= 5'd24;
        end else if ((1'b1 == ap_condition_616)) begin
            msb_reg_357 <= 5'd25;
        end else if ((1'b1 == ap_condition_612)) begin
            msb_reg_357 <= 5'd26;
        end else if ((1'b1 == ap_condition_608)) begin
            msb_reg_357 <= 5'd27;
        end else if ((1'b1 == ap_condition_604)) begin
            msb_reg_357 <= 5'd28;
        end else if ((1'b1 == ap_condition_600)) begin
            msb_reg_357 <= 5'd29;
        end else if (((tmp_1_fu_631_p3 == 1'd1) & (tmp_fu_623_p3 == 1'd0))) begin
            msb_reg_357 <= 5'd30;
        end else if ((tmp_fu_623_p3 == 1'd1)) begin
            msb_reg_357 <= 5'd31;
        end else if ((1'b1 == ap_condition_588)) begin
            msb_reg_357 <= zext_ln147_fu_871_p1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        weight_idx_fu_262 <= 13'd0;
    end else if ((1'b1 == ap_CS_fsm_state19)) begin
        weight_idx_fu_262 <= weight_idx_4_reg_1126;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        add_ln129_reg_1092 <= add_ln129_fu_571_p2;
        zext_ln129_reg_1097[5 : 0] <= zext_ln129_fu_577_p1[5 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state23)) begin
        add_ln151_reg_1267 <= add_ln151_fu_913_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state27)) begin
        add_ln152_1_reg_1297[47 : 7] <= add_ln152_1_fu_986_p2[47 : 7];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state28)) begin
        add_ln152_2_reg_1302[47 : 5] <= add_ln152_2_fu_1002_p2[47 : 5];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state29)) begin
        add_ln152_3_reg_1307[47 : 2] <= add_ln152_3_fu_1018_p2[47 : 2];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state26)) begin
        add_ln152_reg_1292[47 : 9] <= add_ln152_fu_970_p2[47 : 9];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        frac_reg_1262 <= grp_fu_908_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((~((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) & (funct7_i_0_ack_out == 1'b1) & (1'b1 == 1'b1) & (funct7_i_0_vld_reg == 1'b1)) | (~((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) & (1'b1 == 1'b1) & (funct7_i_0_vld_reg == 1'b0)))) begin
        funct7_i_0_data_reg <= funct7_i;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        funct7_i_read_reg_1056 <= funct7_i_0_data_reg;
        src2_i_read_reg_1051 <= src2_i_0_data_reg;
        trunc_ln23_1_reg_1060 <= trunc_ln23_1_fu_543_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        icmp_ln140_reg_1137 <= icmp_ln140_fu_607_p2;
        mel_q16_reg_1132 <= {{mel_pwr_loc_fu_258[47:16]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        k_len_reg_1113 <= mel_k_len_fixed_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        k_start_reg_1121 <= mel_k_start_fixed_q0;
        weight_idx_4_reg_1126 <= weight_idx_4_fu_588_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        log2_float_reg_1272 <= log2_float_fu_930_p2;
        trunc_ln152_reg_1282 <= trunc_ln152_fu_935_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_cfu_hls_Pipeline_MEL_ACCUM_fu_527_mel_pwr_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state16))) begin
        mel_pwr_loc_fu_258 <= grp_cfu_hls_Pipeline_MEL_ACCUM_fu_527_mel_pwr_out;
    end
end

always @ (posedge ap_clk) begin
    if (((~((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) & (1'b1 == 1'b1) & (rslt_o_1_vld_in == 1'b1) & (rslt_o_1_vld_reg == 1'b1)) | (~((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) & (rslt_o_1_vld_in == 1'b1) & (rslt_o_1_vld_reg == 1'b0)))) begin
        rslt_o_1_data_reg <= rslt_o_1_data_in;
    end
end

always @ (posedge ap_clk) begin
    if (((~((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) & (src1_i_0_ack_out == 1'b1) & (1'b1 == 1'b1) & (src1_i_0_vld_reg == 1'b1)) | (~((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) & (1'b1 == 1'b1) & (src1_i_0_vld_reg == 1'b0)))) begin
        src1_i_0_data_reg <= src1_i;
    end
end

always @ (posedge ap_clk) begin
    if (((~((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) & (src2_i_0_ack_out == 1'b1) & (1'b1 == 1'b1) & (src2_i_0_vld_reg == 1'b1)) | (~((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) & (1'b1 == 1'b1) & (src2_i_0_vld_reg == 1'b0)))) begin
        src2_i_0_data_reg <= src2_i;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        sub_ln149_reg_1252 <= sub_ln149_fu_897_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state25)) begin
        sub_ln152_reg_1287[47 : 16] <= sub_ln152_fu_953_p2[47 : 16];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        trunc_ln139_reg_1142 <= trunc_ln139_fu_619_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        trunc_ln149_reg_1247 <= trunc_ln149_fu_885_p1;
        zext_ln143_reg_1242[4 : 0] <= zext_ln143_fu_875_p1[4 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state30)) begin
        trunc_ln_reg_1312 <= {{sub_ln152_1_fu_1026_p2[47:16]}};
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

always @ (*) begin
    if ((grp_cfu_hls_Pipeline_POWER_LOOP_fu_517_ap_done == 1'b0)) begin
        ap_ST_fsm_state11_blk = 1'b1;
    end else begin
        ap_ST_fsm_state11_blk = 1'b0;
    end
end

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

always @ (*) begin
    if ((grp_cfu_hls_Pipeline_MEL_ACCUM_fu_527_ap_done == 1'b0)) begin
        ap_ST_fsm_state16_blk = 1'b1;
    end else begin
        ap_ST_fsm_state16_blk = 1'b0;
    end
end

assign ap_ST_fsm_state17_blk = 1'b0;

assign ap_ST_fsm_state18_blk = 1'b0;

assign ap_ST_fsm_state19_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state20_blk = 1'b0;

assign ap_ST_fsm_state21_blk = 1'b0;

assign ap_ST_fsm_state22_blk = 1'b0;

assign ap_ST_fsm_state23_blk = 1'b0;

assign ap_ST_fsm_state24_blk = 1'b0;

assign ap_ST_fsm_state25_blk = 1'b0;

assign ap_ST_fsm_state26_blk = 1'b0;

assign ap_ST_fsm_state27_blk = 1'b0;

assign ap_ST_fsm_state28_blk = 1'b0;

assign ap_ST_fsm_state29_blk = 1'b0;

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state30_blk = 1'b0;

assign ap_ST_fsm_state31_blk = 1'b0;

assign ap_ST_fsm_state32_blk = 1'b0;

assign ap_ST_fsm_state33_blk = 1'b0;

always @ (*) begin
    if ((rslt_o_1_ack_in == 1'b0)) begin
        ap_ST_fsm_state34_blk = 1'b1;
    end else begin
        ap_ST_fsm_state34_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if ((grp_cfu_hls_Pipeline_HANN_LOOP_fu_485_ap_done == 1'b0)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

assign ap_ST_fsm_state6_blk = 1'b0;

always @ (*) begin
    if ((grp_cfu_hls_Pipeline_BITREV_LOOP_fu_497_ap_done == 1'b0)) begin
        ap_ST_fsm_state7_blk = 1'b1;
    end else begin
        ap_ST_fsm_state7_blk = 1'b0;
    end
end

assign ap_ST_fsm_state8_blk = 1'b0;

always @ (*) begin
    if ((grp_cfu_hls_Pipeline_FFT_STAGE_FFT_BUTTERFLY_fu_505_ap_done == 1'b0)) begin
        ap_ST_fsm_state9_blk = 1'b1;
    end else begin
        ap_ST_fsm_state9_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state34) & (rslt_o_1_ack_in == 1'b1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state34) & (rslt_o_1_ack_in == 1'b1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        frame_buf_address0 = grp_cfu_hls_Pipeline_HANN_LOOP_fu_485_frame_buf_address0;
    end else begin
        frame_buf_address0 = zext_ln45_fu_1041_p1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        frame_buf_ce0 = grp_cfu_hls_Pipeline_HANN_LOOP_fu_485_frame_buf_ce0;
    end else begin
        frame_buf_ce0 = frame_buf_ce0_local;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state33)) begin
        frame_buf_ce0_local = 1'b1;
    end else begin
        frame_buf_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((funct7_i_read_reg_1056 == 8'd0) & (1'b1 == ap_CS_fsm_state33))) begin
        frame_buf_we0_local = 1'b1;
    end else begin
        frame_buf_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | ((1'b1 == ap_CS_fsm_state34) & (rslt_o_1_ack_in == 1'b1)))) begin
        funct7_i_0_ack_out = 1'b1;
    end else begin
        funct7_i_0_ack_out = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        imag_buf_address0 = grp_cfu_hls_Pipeline_POWER_LOOP_fu_517_imag_buf_address0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        imag_buf_address0 = grp_cfu_hls_Pipeline_FFT_STAGE_FFT_BUTTERFLY_fu_505_imag_buf_address0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        imag_buf_address0 = grp_cfu_hls_Pipeline_BITREV_LOOP_fu_497_imag_buf_address0;
    end else begin
        imag_buf_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        imag_buf_address1 = grp_cfu_hls_Pipeline_FFT_STAGE_FFT_BUTTERFLY_fu_505_imag_buf_address1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        imag_buf_address1 = grp_cfu_hls_Pipeline_BITREV_LOOP_fu_497_imag_buf_address1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        imag_buf_address1 = grp_cfu_hls_Pipeline_HANN_LOOP_fu_485_imag_buf_address1;
    end else begin
        imag_buf_address1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        imag_buf_ce0 = grp_cfu_hls_Pipeline_POWER_LOOP_fu_517_imag_buf_ce0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        imag_buf_ce0 = grp_cfu_hls_Pipeline_FFT_STAGE_FFT_BUTTERFLY_fu_505_imag_buf_ce0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        imag_buf_ce0 = grp_cfu_hls_Pipeline_BITREV_LOOP_fu_497_imag_buf_ce0;
    end else begin
        imag_buf_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        imag_buf_ce1 = grp_cfu_hls_Pipeline_FFT_STAGE_FFT_BUTTERFLY_fu_505_imag_buf_ce1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        imag_buf_ce1 = grp_cfu_hls_Pipeline_BITREV_LOOP_fu_497_imag_buf_ce1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        imag_buf_ce1 = grp_cfu_hls_Pipeline_HANN_LOOP_fu_485_imag_buf_ce1;
    end else begin
        imag_buf_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        imag_buf_d1 = grp_cfu_hls_Pipeline_FFT_STAGE_FFT_BUTTERFLY_fu_505_imag_buf_d1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        imag_buf_d1 = grp_cfu_hls_Pipeline_BITREV_LOOP_fu_497_imag_buf_d1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        imag_buf_d1 = grp_cfu_hls_Pipeline_HANN_LOOP_fu_485_imag_buf_d1;
    end else begin
        imag_buf_d1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        imag_buf_we1 = grp_cfu_hls_Pipeline_FFT_STAGE_FFT_BUTTERFLY_fu_505_imag_buf_we1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        imag_buf_we1 = grp_cfu_hls_Pipeline_BITREV_LOOP_fu_497_imag_buf_we1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        imag_buf_we1 = grp_cfu_hls_Pipeline_HANN_LOOP_fu_485_imag_buf_we1;
    end else begin
        imag_buf_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        mel_k_len_fixed_ce0_local = 1'b1;
    end else begin
        mel_k_len_fixed_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        mel_k_start_fixed_ce0_local = 1'b1;
    end else begin
        mel_k_start_fixed_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state31)) begin
        mel_out_address0_local = zext_ln129_reg_1097;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        mel_out_address0_local = zext_ln161_fu_547_p1;
    end else begin
        mel_out_address0_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state31) | (1'b1 == ap_CS_fsm_state2))) begin
        mel_out_ce0_local = 1'b1;
    end else begin
        mel_out_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state31)) begin
        mel_out_we0_local = 1'b1;
    end else begin
        mel_out_we0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        power_buf_address0 = grp_cfu_hls_Pipeline_MEL_ACCUM_fu_527_power_buf_address0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        power_buf_address0 = grp_cfu_hls_Pipeline_POWER_LOOP_fu_517_power_buf_address0;
    end else begin
        power_buf_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        power_buf_ce0 = grp_cfu_hls_Pipeline_MEL_ACCUM_fu_527_power_buf_ce0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        power_buf_ce0 = grp_cfu_hls_Pipeline_POWER_LOOP_fu_517_power_buf_ce0;
    end else begin
        power_buf_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        power_buf_we0 = grp_cfu_hls_Pipeline_POWER_LOOP_fu_517_power_buf_we0;
    end else begin
        power_buf_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        real_buf_address0 = grp_cfu_hls_Pipeline_POWER_LOOP_fu_517_real_buf_address0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        real_buf_address0 = grp_cfu_hls_Pipeline_FFT_STAGE_FFT_BUTTERFLY_fu_505_real_buf_address0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        real_buf_address0 = grp_cfu_hls_Pipeline_BITREV_LOOP_fu_497_real_buf_address0;
    end else begin
        real_buf_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        real_buf_address1 = grp_cfu_hls_Pipeline_FFT_STAGE_FFT_BUTTERFLY_fu_505_real_buf_address1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        real_buf_address1 = grp_cfu_hls_Pipeline_BITREV_LOOP_fu_497_real_buf_address1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        real_buf_address1 = grp_cfu_hls_Pipeline_HANN_LOOP_fu_485_real_buf_address1;
    end else begin
        real_buf_address1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        real_buf_ce0 = grp_cfu_hls_Pipeline_POWER_LOOP_fu_517_real_buf_ce0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        real_buf_ce0 = grp_cfu_hls_Pipeline_FFT_STAGE_FFT_BUTTERFLY_fu_505_real_buf_ce0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        real_buf_ce0 = grp_cfu_hls_Pipeline_BITREV_LOOP_fu_497_real_buf_ce0;
    end else begin
        real_buf_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        real_buf_ce1 = grp_cfu_hls_Pipeline_FFT_STAGE_FFT_BUTTERFLY_fu_505_real_buf_ce1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        real_buf_ce1 = grp_cfu_hls_Pipeline_BITREV_LOOP_fu_497_real_buf_ce1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        real_buf_ce1 = grp_cfu_hls_Pipeline_HANN_LOOP_fu_485_real_buf_ce1;
    end else begin
        real_buf_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        real_buf_d1 = grp_cfu_hls_Pipeline_FFT_STAGE_FFT_BUTTERFLY_fu_505_real_buf_d1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        real_buf_d1 = grp_cfu_hls_Pipeline_BITREV_LOOP_fu_497_real_buf_d1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        real_buf_d1 = grp_cfu_hls_Pipeline_HANN_LOOP_fu_485_real_buf_d1;
    end else begin
        real_buf_d1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        real_buf_we1 = grp_cfu_hls_Pipeline_FFT_STAGE_FFT_BUTTERFLY_fu_505_real_buf_we1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        real_buf_we1 = grp_cfu_hls_Pipeline_BITREV_LOOP_fu_497_real_buf_we1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        real_buf_we1 = grp_cfu_hls_Pipeline_HANN_LOOP_fu_485_real_buf_we1;
    end else begin
        real_buf_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((rslt_o_1_vld_reg == 1'b0) | ((1'b1 == 1'b1) & (rslt_o_1_vld_reg == 1'b1)))) begin
        rslt_o_1_ack_in = 1'b1;
    end else begin
        rslt_o_1_ack_in = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        rslt_o_1_data_in = mel_out_q0;
    end else if ((((icmp_ln129_fu_565_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state12)) | (~(grp_read_fu_282_p2 == 8'd0) & ~(grp_read_fu_282_p2 == 8'd2) & ~(grp_read_fu_282_p2 == 8'd1) & (1'b1 == ap_CS_fsm_state2)) | ((grp_read_fu_282_p2 == 8'd0) & (1'b1 == ap_CS_fsm_state2)))) begin
        rslt_o_1_data_in = 32'd0;
    end else begin
        rslt_o_1_data_in = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | ((icmp_ln129_fu_565_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state12)) | (~(grp_read_fu_282_p2 == 8'd0) & ~(grp_read_fu_282_p2 == 8'd2) & ~(grp_read_fu_282_p2 == 8'd1) & (1'b1 == ap_CS_fsm_state2)) | ((grp_read_fu_282_p2 == 8'd0) & (1'b1 == ap_CS_fsm_state2)))) begin
        rslt_o_1_vld_in = 1'b1;
    end else begin
        rslt_o_1_vld_in = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | ((1'b1 == ap_CS_fsm_state34) & (rslt_o_1_ack_in == 1'b1)))) begin
        src1_i_0_ack_out = 1'b1;
    end else begin
        src1_i_0_ack_out = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | ((1'b1 == ap_CS_fsm_state34) & (rslt_o_1_ack_in == 1'b1)))) begin
        src2_i_0_ack_out = 1'b1;
    end else begin
        src2_i_0_ack_out = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & ((grp_read_fu_282_p2 == 8'd0) | (~(grp_read_fu_282_p2 == 8'd2) & ~(grp_read_fu_282_p2 == 8'd1))))) begin
                ap_NS_fsm = ap_ST_fsm_state33;
            end else if (((grp_read_fu_282_p2 == 8'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state32;
        end
        ap_ST_fsm_state5 : begin
            if (((grp_cfu_hls_Pipeline_HANN_LOOP_fu_485_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            if (((grp_cfu_hls_Pipeline_BITREV_LOOP_fu_497_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            if (((grp_cfu_hls_Pipeline_FFT_STAGE_FFT_BUTTERFLY_fu_505_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            if (((grp_cfu_hls_Pipeline_POWER_LOOP_fu_517_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        ap_ST_fsm_state12 : begin
            if (((icmp_ln129_fu_565_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state12))) begin
                ap_NS_fsm = ap_ST_fsm_state32;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            if (((grp_cfu_hls_Pipeline_MEL_ACCUM_fu_527_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state16))) begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state28;
        end
        ap_ST_fsm_state28 : begin
            ap_NS_fsm = ap_ST_fsm_state29;
        end
        ap_ST_fsm_state29 : begin
            ap_NS_fsm = ap_ST_fsm_state30;
        end
        ap_ST_fsm_state30 : begin
            ap_NS_fsm = ap_ST_fsm_state31;
        end
        ap_ST_fsm_state31 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state32 : begin
            ap_NS_fsm = ap_ST_fsm_state34;
        end
        ap_ST_fsm_state33 : begin
            ap_NS_fsm = ap_ST_fsm_state32;
        end
        ap_ST_fsm_state34 : begin
            if (((1'b1 == ap_CS_fsm_state34) & (rslt_o_1_ack_in == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state34;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln129_fu_571_p2 = (m_fu_266 + 6'd1);

assign add_ln151_fu_913_p2 = ($signed(frac_reg_1262) + $signed(32'd4293918720));

assign add_ln152_1_fu_986_p2 = ($signed(add_ln152_reg_1292) + $signed(sext_ln152_2_fu_982_p1));

assign add_ln152_2_fu_1002_p2 = ($signed(add_ln152_1_reg_1297) + $signed(sext_ln152_3_fu_998_p1));

assign add_ln152_3_fu_1018_p2 = ($signed(add_ln152_2_reg_1302) + $signed(sext_ln152_4_fu_1014_p1));

assign add_ln152_fu_970_p2 = ($signed(sub_ln152_reg_1287) + $signed(sext_ln152_1_fu_966_p1));

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state21 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_state22 = ap_CS_fsm[32'd21];

assign ap_CS_fsm_state23 = ap_CS_fsm[32'd22];

assign ap_CS_fsm_state24 = ap_CS_fsm[32'd23];

assign ap_CS_fsm_state25 = ap_CS_fsm[32'd24];

assign ap_CS_fsm_state26 = ap_CS_fsm[32'd25];

assign ap_CS_fsm_state27 = ap_CS_fsm[32'd26];

assign ap_CS_fsm_state28 = ap_CS_fsm[32'd27];

assign ap_CS_fsm_state29 = ap_CS_fsm[32'd28];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state30 = ap_CS_fsm[32'd29];

assign ap_CS_fsm_state31 = ap_CS_fsm[32'd30];

assign ap_CS_fsm_state33 = ap_CS_fsm[32'd32];

assign ap_CS_fsm_state34 = ap_CS_fsm[32'd33];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_condition_588 = ((tmp_29_fu_855_p3 == 1'd0) & (tmp_28_fu_847_p3 == 1'd0) & (tmp_27_fu_839_p3 == 1'd0) & (tmp_26_fu_831_p3 == 1'd0) & (tmp_25_fu_823_p3 == 1'd0) & (tmp_24_fu_815_p3 == 1'd0) & (tmp_23_fu_807_p3 == 1'd0) & (tmp_22_fu_799_p3 == 1'd0) & (tmp_21_fu_791_p3 == 1'd0) & (tmp_20_fu_783_p3 == 1'd0) & (tmp_19_fu_775_p3 == 1'd0) & (tmp_18_fu_767_p3 == 1'd0) & (tmp_17_fu_759_p3 == 1'd0) & (tmp_16_fu_751_p3 == 1'd0) & (tmp_15_fu_743_p3 == 1'd0) & (tmp_14_fu_735_p3 == 1'd0) & (tmp_13_fu_727_p3 == 1'd0) & (tmp_12_fu_719_p3 == 1'd0) & (tmp_11_fu_711_p3 == 1'd0) & (tmp_10_fu_703_p3 == 1'd0) & (tmp_9_fu_695_p3 == 1'd0) & (tmp_8_fu_687_p3 == 1'd0) & (tmp_7_fu_679_p3 == 1'd0) & (tmp_6_fu_671_p3 == 1'd0) & (tmp_5_fu_663_p3 == 1'd0) & (tmp_4_fu_655_p3 == 1'd0) & (tmp_3_fu_647_p3 == 1'd0) & (tmp_2_fu_639_p3 == 1'd0) & (tmp_1_fu_631_p3 == 1'd0) & (tmp_fu_623_p3 == 1'd0));
end

always @ (*) begin
    ap_condition_600 = ((tmp_2_fu_639_p3 == 1'd1) & (tmp_1_fu_631_p3 == 1'd0) & (tmp_fu_623_p3 == 1'd0));
end

always @ (*) begin
    ap_condition_604 = ((tmp_3_fu_647_p3 == 1'd1) & (tmp_2_fu_639_p3 == 1'd0) & (tmp_1_fu_631_p3 == 1'd0) & (tmp_fu_623_p3 == 1'd0));
end

always @ (*) begin
    ap_condition_608 = ((tmp_4_fu_655_p3 == 1'd1) & (tmp_3_fu_647_p3 == 1'd0) & (tmp_2_fu_639_p3 == 1'd0) & (tmp_1_fu_631_p3 == 1'd0) & (tmp_fu_623_p3 == 1'd0));
end

always @ (*) begin
    ap_condition_612 = ((tmp_5_fu_663_p3 == 1'd1) & (tmp_4_fu_655_p3 == 1'd0) & (tmp_3_fu_647_p3 == 1'd0) & (tmp_2_fu_639_p3 == 1'd0) & (tmp_1_fu_631_p3 == 1'd0) & (tmp_fu_623_p3 == 1'd0));
end

always @ (*) begin
    ap_condition_616 = ((tmp_6_fu_671_p3 == 1'd1) & (tmp_5_fu_663_p3 == 1'd0) & (tmp_4_fu_655_p3 == 1'd0) & (tmp_3_fu_647_p3 == 1'd0) & (tmp_2_fu_639_p3 == 1'd0) & (tmp_1_fu_631_p3 == 1'd0) & (tmp_fu_623_p3 == 1'd0));
end

always @ (*) begin
    ap_condition_620 = ((tmp_7_fu_679_p3 == 1'd1) & (tmp_6_fu_671_p3 == 1'd0) & (tmp_5_fu_663_p3 == 1'd0) & (tmp_4_fu_655_p3 == 1'd0) & (tmp_3_fu_647_p3 == 1'd0) & (tmp_2_fu_639_p3 == 1'd0) & (tmp_1_fu_631_p3 == 1'd0) & (tmp_fu_623_p3 == 1'd0));
end

always @ (*) begin
    ap_condition_624 = ((tmp_8_fu_687_p3 == 1'd1) & (tmp_7_fu_679_p3 == 1'd0) & (tmp_6_fu_671_p3 == 1'd0) & (tmp_5_fu_663_p3 == 1'd0) & (tmp_4_fu_655_p3 == 1'd0) & (tmp_3_fu_647_p3 == 1'd0) & (tmp_2_fu_639_p3 == 1'd0) & (tmp_1_fu_631_p3 == 1'd0) & (tmp_fu_623_p3 == 1'd0));
end

always @ (*) begin
    ap_condition_628 = ((tmp_9_fu_695_p3 == 1'd1) & (tmp_8_fu_687_p3 == 1'd0) & (tmp_7_fu_679_p3 == 1'd0) & (tmp_6_fu_671_p3 == 1'd0) & (tmp_5_fu_663_p3 == 1'd0) & (tmp_4_fu_655_p3 == 1'd0) & (tmp_3_fu_647_p3 == 1'd0) & (tmp_2_fu_639_p3 == 1'd0) & (tmp_1_fu_631_p3 == 1'd0) & (tmp_fu_623_p3 == 1'd0));
end

always @ (*) begin
    ap_condition_632 = ((tmp_10_fu_703_p3 == 1'd1) & (tmp_9_fu_695_p3 == 1'd0) & (tmp_8_fu_687_p3 == 1'd0) & (tmp_7_fu_679_p3 == 1'd0) & (tmp_6_fu_671_p3 == 1'd0) & (tmp_5_fu_663_p3 == 1'd0) & (tmp_4_fu_655_p3 == 1'd0) & (tmp_3_fu_647_p3 == 1'd0) & (tmp_2_fu_639_p3 == 1'd0) & (tmp_1_fu_631_p3 == 1'd0) & (tmp_fu_623_p3 == 1'd0));
end

always @ (*) begin
    ap_condition_636 = ((tmp_11_fu_711_p3 == 1'd1) & (tmp_10_fu_703_p3 == 1'd0) & (tmp_9_fu_695_p3 == 1'd0) & (tmp_8_fu_687_p3 == 1'd0) & (tmp_7_fu_679_p3 == 1'd0) & (tmp_6_fu_671_p3 == 1'd0) & (tmp_5_fu_663_p3 == 1'd0) & (tmp_4_fu_655_p3 == 1'd0) & (tmp_3_fu_647_p3 == 1'd0) & (tmp_2_fu_639_p3 == 1'd0) & (tmp_1_fu_631_p3 == 1'd0) & (tmp_fu_623_p3 == 1'd0));
end

always @ (*) begin
    ap_condition_640 = ((tmp_12_fu_719_p3 == 1'd1) & (tmp_11_fu_711_p3 == 1'd0) & (tmp_10_fu_703_p3 == 1'd0) & (tmp_9_fu_695_p3 == 1'd0) & (tmp_8_fu_687_p3 == 1'd0) & (tmp_7_fu_679_p3 == 1'd0) & (tmp_6_fu_671_p3 == 1'd0) & (tmp_5_fu_663_p3 == 1'd0) & (tmp_4_fu_655_p3 == 1'd0) & (tmp_3_fu_647_p3 == 1'd0) & (tmp_2_fu_639_p3 == 1'd0) & (tmp_1_fu_631_p3 == 1'd0) & (tmp_fu_623_p3 == 1'd0));
end

always @ (*) begin
    ap_condition_644 = ((tmp_13_fu_727_p3 == 1'd1) & (tmp_12_fu_719_p3 == 1'd0) & (tmp_11_fu_711_p3 == 1'd0) & (tmp_10_fu_703_p3 == 1'd0) & (tmp_9_fu_695_p3 == 1'd0) & (tmp_8_fu_687_p3 == 1'd0) & (tmp_7_fu_679_p3 == 1'd0) & (tmp_6_fu_671_p3 == 1'd0) & (tmp_5_fu_663_p3 == 1'd0) & (tmp_4_fu_655_p3 == 1'd0) & (tmp_3_fu_647_p3 == 1'd0) & (tmp_2_fu_639_p3 == 1'd0) & (tmp_1_fu_631_p3 == 1'd0) & (tmp_fu_623_p3 == 1'd0));
end

always @ (*) begin
    ap_condition_648 = ((tmp_14_fu_735_p3 == 1'd1) & (tmp_13_fu_727_p3 == 1'd0) & (tmp_12_fu_719_p3 == 1'd0) & (tmp_11_fu_711_p3 == 1'd0) & (tmp_10_fu_703_p3 == 1'd0) & (tmp_9_fu_695_p3 == 1'd0) & (tmp_8_fu_687_p3 == 1'd0) & (tmp_7_fu_679_p3 == 1'd0) & (tmp_6_fu_671_p3 == 1'd0) & (tmp_5_fu_663_p3 == 1'd0) & (tmp_4_fu_655_p3 == 1'd0) & (tmp_3_fu_647_p3 == 1'd0) & (tmp_2_fu_639_p3 == 1'd0) & (tmp_1_fu_631_p3 == 1'd0) & (tmp_fu_623_p3 == 1'd0));
end

always @ (*) begin
    ap_condition_652 = ((tmp_15_fu_743_p3 == 1'd1) & (tmp_14_fu_735_p3 == 1'd0) & (tmp_13_fu_727_p3 == 1'd0) & (tmp_12_fu_719_p3 == 1'd0) & (tmp_11_fu_711_p3 == 1'd0) & (tmp_10_fu_703_p3 == 1'd0) & (tmp_9_fu_695_p3 == 1'd0) & (tmp_8_fu_687_p3 == 1'd0) & (tmp_7_fu_679_p3 == 1'd0) & (tmp_6_fu_671_p3 == 1'd0) & (tmp_5_fu_663_p3 == 1'd0) & (tmp_4_fu_655_p3 == 1'd0) & (tmp_3_fu_647_p3 == 1'd0) & (tmp_2_fu_639_p3 == 1'd0) & (tmp_1_fu_631_p3 == 1'd0) & (tmp_fu_623_p3 == 1'd0));
end

always @ (*) begin
    ap_condition_656 = ((tmp_16_fu_751_p3 == 1'd1) & (tmp_15_fu_743_p3 == 1'd0) & (tmp_14_fu_735_p3 == 1'd0) & (tmp_13_fu_727_p3 == 1'd0) & (tmp_12_fu_719_p3 == 1'd0) & (tmp_11_fu_711_p3 == 1'd0) & (tmp_10_fu_703_p3 == 1'd0) & (tmp_9_fu_695_p3 == 1'd0) & (tmp_8_fu_687_p3 == 1'd0) & (tmp_7_fu_679_p3 == 1'd0) & (tmp_6_fu_671_p3 == 1'd0) & (tmp_5_fu_663_p3 == 1'd0) & (tmp_4_fu_655_p3 == 1'd0) & (tmp_3_fu_647_p3 == 1'd0) & (tmp_2_fu_639_p3 == 1'd0) & (tmp_1_fu_631_p3 == 1'd0) & (tmp_fu_623_p3 == 1'd0));
end

always @ (*) begin
    ap_condition_660 = ((tmp_17_fu_759_p3 == 1'd1) & (tmp_16_fu_751_p3 == 1'd0) & (tmp_15_fu_743_p3 == 1'd0) & (tmp_14_fu_735_p3 == 1'd0) & (tmp_13_fu_727_p3 == 1'd0) & (tmp_12_fu_719_p3 == 1'd0) & (tmp_11_fu_711_p3 == 1'd0) & (tmp_10_fu_703_p3 == 1'd0) & (tmp_9_fu_695_p3 == 1'd0) & (tmp_8_fu_687_p3 == 1'd0) & (tmp_7_fu_679_p3 == 1'd0) & (tmp_6_fu_671_p3 == 1'd0) & (tmp_5_fu_663_p3 == 1'd0) & (tmp_4_fu_655_p3 == 1'd0) & (tmp_3_fu_647_p3 == 1'd0) & (tmp_2_fu_639_p3 == 1'd0) & (tmp_1_fu_631_p3 == 1'd0) & (tmp_fu_623_p3 == 1'd0));
end

always @ (*) begin
    ap_condition_664 = ((tmp_18_fu_767_p3 == 1'd1) & (tmp_17_fu_759_p3 == 1'd0) & (tmp_16_fu_751_p3 == 1'd0) & (tmp_15_fu_743_p3 == 1'd0) & (tmp_14_fu_735_p3 == 1'd0) & (tmp_13_fu_727_p3 == 1'd0) & (tmp_12_fu_719_p3 == 1'd0) & (tmp_11_fu_711_p3 == 1'd0) & (tmp_10_fu_703_p3 == 1'd0) & (tmp_9_fu_695_p3 == 1'd0) & (tmp_8_fu_687_p3 == 1'd0) & (tmp_7_fu_679_p3 == 1'd0) & (tmp_6_fu_671_p3 == 1'd0) & (tmp_5_fu_663_p3 == 1'd0) & (tmp_4_fu_655_p3 == 1'd0) & (tmp_3_fu_647_p3 == 1'd0) & (tmp_2_fu_639_p3 == 1'd0) & (tmp_1_fu_631_p3 == 1'd0) & (tmp_fu_623_p3 == 1'd0));
end

always @ (*) begin
    ap_condition_668 = ((tmp_19_fu_775_p3 == 1'd1) & (tmp_18_fu_767_p3 == 1'd0) & (tmp_17_fu_759_p3 == 1'd0) & (tmp_16_fu_751_p3 == 1'd0) & (tmp_15_fu_743_p3 == 1'd0) & (tmp_14_fu_735_p3 == 1'd0) & (tmp_13_fu_727_p3 == 1'd0) & (tmp_12_fu_719_p3 == 1'd0) & (tmp_11_fu_711_p3 == 1'd0) & (tmp_10_fu_703_p3 == 1'd0) & (tmp_9_fu_695_p3 == 1'd0) & (tmp_8_fu_687_p3 == 1'd0) & (tmp_7_fu_679_p3 == 1'd0) & (tmp_6_fu_671_p3 == 1'd0) & (tmp_5_fu_663_p3 == 1'd0) & (tmp_4_fu_655_p3 == 1'd0) & (tmp_3_fu_647_p3 == 1'd0) & (tmp_2_fu_639_p3 == 1'd0) & (tmp_1_fu_631_p3 == 1'd0) & (tmp_fu_623_p3 == 1'd0));
end

always @ (*) begin
    ap_condition_672 = ((tmp_20_fu_783_p3 == 1'd1) & (tmp_19_fu_775_p3 == 1'd0) & (tmp_18_fu_767_p3 == 1'd0) & (tmp_17_fu_759_p3 == 1'd0) & (tmp_16_fu_751_p3 == 1'd0) & (tmp_15_fu_743_p3 == 1'd0) & (tmp_14_fu_735_p3 == 1'd0) & (tmp_13_fu_727_p3 == 1'd0) & (tmp_12_fu_719_p3 == 1'd0) & (tmp_11_fu_711_p3 == 1'd0) & (tmp_10_fu_703_p3 == 1'd0) & (tmp_9_fu_695_p3 == 1'd0) & (tmp_8_fu_687_p3 == 1'd0) & (tmp_7_fu_679_p3 == 1'd0) & (tmp_6_fu_671_p3 == 1'd0) & (tmp_5_fu_663_p3 == 1'd0) & (tmp_4_fu_655_p3 == 1'd0) & (tmp_3_fu_647_p3 == 1'd0) & (tmp_2_fu_639_p3 == 1'd0) & (tmp_1_fu_631_p3 == 1'd0) & (tmp_fu_623_p3 == 1'd0));
end

always @ (*) begin
    ap_condition_676 = ((tmp_21_fu_791_p3 == 1'd1) & (tmp_20_fu_783_p3 == 1'd0) & (tmp_19_fu_775_p3 == 1'd0) & (tmp_18_fu_767_p3 == 1'd0) & (tmp_17_fu_759_p3 == 1'd0) & (tmp_16_fu_751_p3 == 1'd0) & (tmp_15_fu_743_p3 == 1'd0) & (tmp_14_fu_735_p3 == 1'd0) & (tmp_13_fu_727_p3 == 1'd0) & (tmp_12_fu_719_p3 == 1'd0) & (tmp_11_fu_711_p3 == 1'd0) & (tmp_10_fu_703_p3 == 1'd0) & (tmp_9_fu_695_p3 == 1'd0) & (tmp_8_fu_687_p3 == 1'd0) & (tmp_7_fu_679_p3 == 1'd0) & (tmp_6_fu_671_p3 == 1'd0) & (tmp_5_fu_663_p3 == 1'd0) & (tmp_4_fu_655_p3 == 1'd0) & (tmp_3_fu_647_p3 == 1'd0) & (tmp_2_fu_639_p3 == 1'd0) & (tmp_1_fu_631_p3 == 1'd0) & (tmp_fu_623_p3 == 1'd0));
end

always @ (*) begin
    ap_condition_680 = ((tmp_22_fu_799_p3 == 1'd1) & (tmp_21_fu_791_p3 == 1'd0) & (tmp_20_fu_783_p3 == 1'd0) & (tmp_19_fu_775_p3 == 1'd0) & (tmp_18_fu_767_p3 == 1'd0) & (tmp_17_fu_759_p3 == 1'd0) & (tmp_16_fu_751_p3 == 1'd0) & (tmp_15_fu_743_p3 == 1'd0) & (tmp_14_fu_735_p3 == 1'd0) & (tmp_13_fu_727_p3 == 1'd0) & (tmp_12_fu_719_p3 == 1'd0) & (tmp_11_fu_711_p3 == 1'd0) & (tmp_10_fu_703_p3 == 1'd0) & (tmp_9_fu_695_p3 == 1'd0) & (tmp_8_fu_687_p3 == 1'd0) & (tmp_7_fu_679_p3 == 1'd0) & (tmp_6_fu_671_p3 == 1'd0) & (tmp_5_fu_663_p3 == 1'd0) & (tmp_4_fu_655_p3 == 1'd0) & (tmp_3_fu_647_p3 == 1'd0) & (tmp_2_fu_639_p3 == 1'd0) & (tmp_1_fu_631_p3 == 1'd0) & (tmp_fu_623_p3 == 1'd0));
end

always @ (*) begin
    ap_condition_684 = ((tmp_23_fu_807_p3 == 1'd1) & (tmp_22_fu_799_p3 == 1'd0) & (tmp_21_fu_791_p3 == 1'd0) & (tmp_20_fu_783_p3 == 1'd0) & (tmp_19_fu_775_p3 == 1'd0) & (tmp_18_fu_767_p3 == 1'd0) & (tmp_17_fu_759_p3 == 1'd0) & (tmp_16_fu_751_p3 == 1'd0) & (tmp_15_fu_743_p3 == 1'd0) & (tmp_14_fu_735_p3 == 1'd0) & (tmp_13_fu_727_p3 == 1'd0) & (tmp_12_fu_719_p3 == 1'd0) & (tmp_11_fu_711_p3 == 1'd0) & (tmp_10_fu_703_p3 == 1'd0) & (tmp_9_fu_695_p3 == 1'd0) & (tmp_8_fu_687_p3 == 1'd0) & (tmp_7_fu_679_p3 == 1'd0) & (tmp_6_fu_671_p3 == 1'd0) & (tmp_5_fu_663_p3 == 1'd0) & (tmp_4_fu_655_p3 == 1'd0) & (tmp_3_fu_647_p3 == 1'd0) & (tmp_2_fu_639_p3 == 1'd0) & (tmp_1_fu_631_p3 == 1'd0) & (tmp_fu_623_p3 == 1'd0));
end

always @ (*) begin
    ap_condition_688 = ((tmp_24_fu_815_p3 == 1'd1) & (tmp_23_fu_807_p3 == 1'd0) & (tmp_22_fu_799_p3 == 1'd0) & (tmp_21_fu_791_p3 == 1'd0) & (tmp_20_fu_783_p3 == 1'd0) & (tmp_19_fu_775_p3 == 1'd0) & (tmp_18_fu_767_p3 == 1'd0) & (tmp_17_fu_759_p3 == 1'd0) & (tmp_16_fu_751_p3 == 1'd0) & (tmp_15_fu_743_p3 == 1'd0) & (tmp_14_fu_735_p3 == 1'd0) & (tmp_13_fu_727_p3 == 1'd0) & (tmp_12_fu_719_p3 == 1'd0) & (tmp_11_fu_711_p3 == 1'd0) & (tmp_10_fu_703_p3 == 1'd0) & (tmp_9_fu_695_p3 == 1'd0) & (tmp_8_fu_687_p3 == 1'd0) & (tmp_7_fu_679_p3 == 1'd0) & (tmp_6_fu_671_p3 == 1'd0) & (tmp_5_fu_663_p3 == 1'd0) & (tmp_4_fu_655_p3 == 1'd0) & (tmp_3_fu_647_p3 == 1'd0) & (tmp_2_fu_639_p3 == 1'd0) & (tmp_1_fu_631_p3 == 1'd0) & (tmp_fu_623_p3 == 1'd0));
end

always @ (*) begin
    ap_condition_692 = ((tmp_25_fu_823_p3 == 1'd1) & (tmp_24_fu_815_p3 == 1'd0) & (tmp_23_fu_807_p3 == 1'd0) & (tmp_22_fu_799_p3 == 1'd0) & (tmp_21_fu_791_p3 == 1'd0) & (tmp_20_fu_783_p3 == 1'd0) & (tmp_19_fu_775_p3 == 1'd0) & (tmp_18_fu_767_p3 == 1'd0) & (tmp_17_fu_759_p3 == 1'd0) & (tmp_16_fu_751_p3 == 1'd0) & (tmp_15_fu_743_p3 == 1'd0) & (tmp_14_fu_735_p3 == 1'd0) & (tmp_13_fu_727_p3 == 1'd0) & (tmp_12_fu_719_p3 == 1'd0) & (tmp_11_fu_711_p3 == 1'd0) & (tmp_10_fu_703_p3 == 1'd0) & (tmp_9_fu_695_p3 == 1'd0) & (tmp_8_fu_687_p3 == 1'd0) & (tmp_7_fu_679_p3 == 1'd0) & (tmp_6_fu_671_p3 == 1'd0) & (tmp_5_fu_663_p3 == 1'd0) & (tmp_4_fu_655_p3 == 1'd0) & (tmp_3_fu_647_p3 == 1'd0) & (tmp_2_fu_639_p3 == 1'd0) & (tmp_1_fu_631_p3 == 1'd0) & (tmp_fu_623_p3 == 1'd0));
end

always @ (*) begin
    ap_condition_696 = ((tmp_26_fu_831_p3 == 1'd1) & (tmp_25_fu_823_p3 == 1'd0) & (tmp_24_fu_815_p3 == 1'd0) & (tmp_23_fu_807_p3 == 1'd0) & (tmp_22_fu_799_p3 == 1'd0) & (tmp_21_fu_791_p3 == 1'd0) & (tmp_20_fu_783_p3 == 1'd0) & (tmp_19_fu_775_p3 == 1'd0) & (tmp_18_fu_767_p3 == 1'd0) & (tmp_17_fu_759_p3 == 1'd0) & (tmp_16_fu_751_p3 == 1'd0) & (tmp_15_fu_743_p3 == 1'd0) & (tmp_14_fu_735_p3 == 1'd0) & (tmp_13_fu_727_p3 == 1'd0) & (tmp_12_fu_719_p3 == 1'd0) & (tmp_11_fu_711_p3 == 1'd0) & (tmp_10_fu_703_p3 == 1'd0) & (tmp_9_fu_695_p3 == 1'd0) & (tmp_8_fu_687_p3 == 1'd0) & (tmp_7_fu_679_p3 == 1'd0) & (tmp_6_fu_671_p3 == 1'd0) & (tmp_5_fu_663_p3 == 1'd0) & (tmp_4_fu_655_p3 == 1'd0) & (tmp_3_fu_647_p3 == 1'd0) & (tmp_2_fu_639_p3 == 1'd0) & (tmp_1_fu_631_p3 == 1'd0) & (tmp_fu_623_p3 == 1'd0));
end

always @ (*) begin
    ap_condition_700 = ((tmp_27_fu_839_p3 == 1'd1) & (tmp_26_fu_831_p3 == 1'd0) & (tmp_25_fu_823_p3 == 1'd0) & (tmp_24_fu_815_p3 == 1'd0) & (tmp_23_fu_807_p3 == 1'd0) & (tmp_22_fu_799_p3 == 1'd0) & (tmp_21_fu_791_p3 == 1'd0) & (tmp_20_fu_783_p3 == 1'd0) & (tmp_19_fu_775_p3 == 1'd0) & (tmp_18_fu_767_p3 == 1'd0) & (tmp_17_fu_759_p3 == 1'd0) & (tmp_16_fu_751_p3 == 1'd0) & (tmp_15_fu_743_p3 == 1'd0) & (tmp_14_fu_735_p3 == 1'd0) & (tmp_13_fu_727_p3 == 1'd0) & (tmp_12_fu_719_p3 == 1'd0) & (tmp_11_fu_711_p3 == 1'd0) & (tmp_10_fu_703_p3 == 1'd0) & (tmp_9_fu_695_p3 == 1'd0) & (tmp_8_fu_687_p3 == 1'd0) & (tmp_7_fu_679_p3 == 1'd0) & (tmp_6_fu_671_p3 == 1'd0) & (tmp_5_fu_663_p3 == 1'd0) & (tmp_4_fu_655_p3 == 1'd0) & (tmp_3_fu_647_p3 == 1'd0) & (tmp_2_fu_639_p3 == 1'd0) & (tmp_1_fu_631_p3 == 1'd0) & (tmp_fu_623_p3 == 1'd0));
end

always @ (*) begin
    ap_condition_704 = ((tmp_28_fu_847_p3 == 1'd1) & (tmp_27_fu_839_p3 == 1'd0) & (tmp_26_fu_831_p3 == 1'd0) & (tmp_25_fu_823_p3 == 1'd0) & (tmp_24_fu_815_p3 == 1'd0) & (tmp_23_fu_807_p3 == 1'd0) & (tmp_22_fu_799_p3 == 1'd0) & (tmp_21_fu_791_p3 == 1'd0) & (tmp_20_fu_783_p3 == 1'd0) & (tmp_19_fu_775_p3 == 1'd0) & (tmp_18_fu_767_p3 == 1'd0) & (tmp_17_fu_759_p3 == 1'd0) & (tmp_16_fu_751_p3 == 1'd0) & (tmp_15_fu_743_p3 == 1'd0) & (tmp_14_fu_735_p3 == 1'd0) & (tmp_13_fu_727_p3 == 1'd0) & (tmp_12_fu_719_p3 == 1'd0) & (tmp_11_fu_711_p3 == 1'd0) & (tmp_10_fu_703_p3 == 1'd0) & (tmp_9_fu_695_p3 == 1'd0) & (tmp_8_fu_687_p3 == 1'd0) & (tmp_7_fu_679_p3 == 1'd0) & (tmp_6_fu_671_p3 == 1'd0) & (tmp_5_fu_663_p3 == 1'd0) & (tmp_4_fu_655_p3 == 1'd0) & (tmp_3_fu_647_p3 == 1'd0) & (tmp_2_fu_639_p3 == 1'd0) & (tmp_1_fu_631_p3 == 1'd0) & (tmp_fu_623_p3 == 1'd0));
end

always @ (*) begin
    ap_condition_708 = ((tmp_29_fu_855_p3 == 1'd1) & (tmp_28_fu_847_p3 == 1'd0) & (tmp_27_fu_839_p3 == 1'd0) & (tmp_26_fu_831_p3 == 1'd0) & (tmp_25_fu_823_p3 == 1'd0) & (tmp_24_fu_815_p3 == 1'd0) & (tmp_23_fu_807_p3 == 1'd0) & (tmp_22_fu_799_p3 == 1'd0) & (tmp_21_fu_791_p3 == 1'd0) & (tmp_20_fu_783_p3 == 1'd0) & (tmp_19_fu_775_p3 == 1'd0) & (tmp_18_fu_767_p3 == 1'd0) & (tmp_17_fu_759_p3 == 1'd0) & (tmp_16_fu_751_p3 == 1'd0) & (tmp_15_fu_743_p3 == 1'd0) & (tmp_14_fu_735_p3 == 1'd0) & (tmp_13_fu_727_p3 == 1'd0) & (tmp_12_fu_719_p3 == 1'd0) & (tmp_11_fu_711_p3 == 1'd0) & (tmp_10_fu_703_p3 == 1'd0) & (tmp_9_fu_695_p3 == 1'd0) & (tmp_8_fu_687_p3 == 1'd0) & (tmp_7_fu_679_p3 == 1'd0) & (tmp_6_fu_671_p3 == 1'd0) & (tmp_5_fu_663_p3 == 1'd0) & (tmp_4_fu_655_p3 == 1'd0) & (tmp_3_fu_647_p3 == 1'd0) & (tmp_2_fu_639_p3 == 1'd0) & (tmp_1_fu_631_p3 == 1'd0) & (tmp_fu_623_p3 == 1'd0));
end

assign grp_cfu_hls_Pipeline_BITREV_LOOP_fu_497_ap_start = grp_cfu_hls_Pipeline_BITREV_LOOP_fu_497_ap_start_reg;

assign grp_cfu_hls_Pipeline_FFT_STAGE_FFT_BUTTERFLY_fu_505_ap_start = grp_cfu_hls_Pipeline_FFT_STAGE_FFT_BUTTERFLY_fu_505_ap_start_reg;

assign grp_cfu_hls_Pipeline_HANN_LOOP_fu_485_ap_start = grp_cfu_hls_Pipeline_HANN_LOOP_fu_485_ap_start_reg;

assign grp_cfu_hls_Pipeline_MEL_ACCUM_fu_527_ap_start = grp_cfu_hls_Pipeline_MEL_ACCUM_fu_527_ap_start_reg;

assign grp_cfu_hls_Pipeline_POWER_LOOP_fu_517_ap_start = grp_cfu_hls_Pipeline_POWER_LOOP_fu_517_ap_start_reg;

assign grp_fu_908_p0 = {{sub_ln149_reg_1252}, {16'd0}};

assign grp_read_fu_282_p2 = funct7_i_0_data_reg;

assign icmp_ln129_fu_565_p2 = ((m_fu_266 == 6'd32) ? 1'b1 : 1'b0);

assign icmp_ln140_fu_607_p2 = ((mel_q16_fu_597_p4 == 32'd0) ? 1'b1 : 1'b0);

assign log2_float_fu_930_p2 = (add_ln151_reg_1267 + zext_ln151_fu_926_p1);

assign mel_k_len_fixed_address0 = zext_ln129_fu_577_p1;

assign mel_k_start_fixed_address0 = zext_ln129_reg_1097;

assign mel_q16_1_fu_613_p3 = ((icmp_ln140_reg_1137[0:0] == 1'b1) ? 32'd1 : mel_q16_reg_1132);

assign mel_q16_fu_597_p4 = {{mel_pwr_loc_fu_258[47:16]}};

assign p_shl1_fu_946_p3 = {{log2_float_reg_1272}, {16'd0}};

assign p_shl_fu_939_p3 = {{trunc_ln152_reg_1282}, {18'd0}};

assign rslt_o = rslt_o_1_data_reg;

assign sext_ln152_1_fu_966_p1 = $signed(tmp_31_fu_959_p3);

assign sext_ln152_2_fu_982_p1 = $signed(tmp_32_fu_975_p3);

assign sext_ln152_3_fu_998_p1 = $signed(tmp_33_fu_991_p3);

assign sext_ln152_4_fu_1014_p1 = $signed(tmp_34_fu_1007_p3);

assign sext_ln152_fu_1023_p1 = log2_float_reg_1272;

assign shl_ln149_fu_879_p2 = 32'd1 << zext_ln143_fu_875_p1;

assign shl_ln_fu_918_p3 = {{msb_reg_357}, {16'd0}};

assign sub_ln149_fu_897_p2 = (trunc_ln139_reg_1142 - trunc_ln149_reg_1247);

assign sub_ln152_1_fu_1026_p2 = ($signed(add_ln152_3_reg_1307) - $signed(sext_ln152_fu_1023_p1));

assign sub_ln152_fu_953_p2 = (p_shl_fu_939_p3 - p_shl1_fu_946_p3);

assign tmp_10_fu_703_p3 = mel_q16_1_fu_613_p3[32'd21];

assign tmp_11_fu_711_p3 = mel_q16_1_fu_613_p3[32'd20];

assign tmp_12_fu_719_p3 = mel_q16_1_fu_613_p3[32'd19];

assign tmp_13_fu_727_p3 = mel_q16_1_fu_613_p3[32'd18];

assign tmp_14_fu_735_p3 = mel_q16_1_fu_613_p3[32'd17];

assign tmp_15_fu_743_p3 = mel_q16_1_fu_613_p3[32'd16];

assign tmp_16_fu_751_p3 = mel_q16_1_fu_613_p3[32'd15];

assign tmp_17_fu_759_p3 = mel_q16_1_fu_613_p3[32'd14];

assign tmp_18_fu_767_p3 = mel_q16_1_fu_613_p3[32'd13];

assign tmp_19_fu_775_p3 = mel_q16_1_fu_613_p3[32'd12];

assign tmp_1_fu_631_p3 = mel_q16_1_fu_613_p3[32'd30];

assign tmp_20_fu_783_p3 = mel_q16_1_fu_613_p3[32'd11];

assign tmp_21_fu_791_p3 = mel_q16_1_fu_613_p3[32'd10];

assign tmp_22_fu_799_p3 = mel_q16_1_fu_613_p3[32'd9];

assign tmp_23_fu_807_p3 = mel_q16_1_fu_613_p3[32'd8];

assign tmp_24_fu_815_p3 = mel_q16_1_fu_613_p3[32'd7];

assign tmp_25_fu_823_p3 = mel_q16_1_fu_613_p3[32'd6];

assign tmp_26_fu_831_p3 = mel_q16_1_fu_613_p3[32'd5];

assign tmp_27_fu_839_p3 = mel_q16_1_fu_613_p3[32'd4];

assign tmp_28_fu_847_p3 = mel_q16_1_fu_613_p3[32'd3];

assign tmp_29_fu_855_p3 = mel_q16_1_fu_613_p3[32'd2];

assign tmp_2_fu_639_p3 = mel_q16_1_fu_613_p3[32'd29];

assign tmp_30_fu_863_p3 = mel_q16_1_fu_613_p3[32'd1];

assign tmp_31_fu_959_p3 = {{log2_float_reg_1272}, {9'd0}};

assign tmp_32_fu_975_p3 = {{log2_float_reg_1272}, {7'd0}};

assign tmp_33_fu_991_p3 = {{log2_float_reg_1272}, {5'd0}};

assign tmp_34_fu_1007_p3 = {{log2_float_reg_1272}, {2'd0}};

assign tmp_3_fu_647_p3 = mel_q16_1_fu_613_p3[32'd28];

assign tmp_4_fu_655_p3 = mel_q16_1_fu_613_p3[32'd27];

assign tmp_5_fu_663_p3 = mel_q16_1_fu_613_p3[32'd26];

assign tmp_6_fu_671_p3 = mel_q16_1_fu_613_p3[32'd25];

assign tmp_7_fu_679_p3 = mel_q16_1_fu_613_p3[32'd24];

assign tmp_8_fu_687_p3 = mel_q16_1_fu_613_p3[32'd23];

assign tmp_9_fu_695_p3 = mel_q16_1_fu_613_p3[32'd22];

assign tmp_fu_623_p3 = mel_q16_1_fu_613_p3[32'd31];

assign trunc_ln139_fu_619_p1 = mel_q16_1_fu_613_p3[15:0];

assign trunc_ln149_fu_885_p1 = shl_ln149_fu_879_p2[15:0];

assign trunc_ln152_fu_935_p1 = log2_float_fu_930_p2[29:0];

assign trunc_ln23_1_fu_543_p1 = src1_i_0_data_reg[10:0];

assign trunc_ln23_fu_539_p1 = src1_i_0_data_reg[4:0];

assign weight_idx_4_fu_588_p2 = (weight_idx_fu_262 + zext_ln132_fu_585_p1);

assign zext_ln129_fu_577_p1 = m_fu_266;

assign zext_ln132_fu_585_p1 = k_len_reg_1113;

assign zext_ln143_fu_875_p1 = msb_reg_357;

assign zext_ln147_fu_871_p1 = tmp_30_fu_863_p3;

assign zext_ln151_fu_926_p1 = shl_ln_fu_918_p3;

assign zext_ln161_fu_547_p1 = trunc_ln23_fu_539_p1;

assign zext_ln45_fu_1041_p1 = trunc_ln23_1_reg_1060;

always @ (posedge ap_clk) begin
    funct7_i_0_vld_reg <= 1'b0;
    src1_i_0_vld_reg <= 1'b0;
    src2_i_0_vld_reg <= 1'b0;
    rslt_o_1_vld_reg <= 1'b0;
    zext_ln129_reg_1097[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
    zext_ln143_reg_1242[31:5] <= 27'b000000000000000000000000000;
    sub_ln152_reg_1287[15:0] <= 16'b0000000000000000;
    add_ln152_reg_1292[8:0] <= 9'b000000000;
    add_ln152_1_reg_1297[6:0] <= 7'b0000000;
    add_ln152_2_reg_1302[4:0] <= 5'b00000;
    add_ln152_3_reg_1307[1:0] <= 2'b00;
end

endmodule //cfu_hls
