// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module cfu_hls_cfu_hls_Pipeline_POWER_LOOP (
        ap_clk,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        real_buf_address0,
        real_buf_ce0,
        real_buf_q0,
        imag_buf_address0,
        imag_buf_ce0,
        imag_buf_q0,
        power_buf_address0,
        power_buf_ce0,
        power_buf_we0,
        power_buf_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [10:0] real_buf_address0;
output   real_buf_ce0;
input  [31:0] real_buf_q0;
output  [10:0] imag_buf_address0;
output   imag_buf_ce0;
input  [31:0] imag_buf_q0;
output  [10:0] power_buf_address0;
output   power_buf_ce0;
output   power_buf_we0;
output  [31:0] power_buf_d0;

reg ap_idle;

(* fsm_encoding = "auto" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln118_fu_103_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire   [63:0] zext_ln118_fu_115_p1;
reg   [63:0] zext_ln118_reg_161;
reg   [63:0] zext_ln118_reg_161_pp0_iter1_reg;
reg   [63:0] zext_ln118_reg_161_pp0_iter2_reg;
reg   [63:0] zext_ln118_reg_161_pp0_iter3_reg;
reg   [63:0] zext_ln118_reg_161_pp0_iter4_reg;
reg   [63:0] zext_ln118_reg_161_pp0_iter5_reg;
reg   [63:0] zext_ln118_reg_161_pp0_iter6_reg;
reg   [63:0] zext_ln118_reg_161_pp0_iter7_reg;
reg   [31:0] r_reg_176;
reg   [31:0] im_reg_181;
wire  signed [57:0] sext_ln120_fu_126_p1;
wire  signed [57:0] sext_ln121_fu_131_p1;
wire   [57:0] grp_fu_87_p2;
reg   [57:0] mul_ln122_reg_198;
wire   [57:0] grp_fu_91_p2;
reg   [57:0] mul_ln122_1_reg_203;
reg   [31:0] trunc_ln8_reg_208;
wire    ap_block_pp0_stage0;
reg   [10:0] k_fu_44;
wire   [10:0] add_ln118_fu_109_p2;
wire    ap_loop_init;
reg   [10:0] ap_sig_allocacmp_k_1;
reg    real_buf_ce0_local;
reg    imag_buf_ce0_local;
reg    power_buf_we0_local;
reg    power_buf_ce0_local;
wire  signed [31:0] grp_fu_87_p0;
wire  signed [31:0] grp_fu_87_p1;
wire  signed [31:0] grp_fu_91_p0;
wire  signed [31:0] grp_fu_91_p1;
wire   [57:0] pwr_fu_136_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 k_fu_44 = 11'd0;
#0 ap_done_reg = 1'b0;
end

cfu_hls_mul_32s_32s_58_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 58 ))
mul_32s_32s_58_5_1_U21(
    .clk(ap_clk),
    .reset(1'b0),
    .din0(grp_fu_87_p0),
    .din1(grp_fu_87_p1),
    .ce(1'b1),
    .dout(grp_fu_87_p2)
);

cfu_hls_mul_32s_32s_58_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 58 ))
mul_32s_32s_58_5_1_U22(
    .clk(ap_clk),
    .reset(1'b0),
    .din0(grp_fu_91_p0),
    .din1(grp_fu_91_p1),
    .ce(1'b1),
    .dout(grp_fu_91_p2)
);

cfu_hls_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(1'b0),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    ap_CS_fsm <= ap_NS_fsm;
end

always @ (posedge ap_clk) begin
    if ((ap_continue_int == 1'b1)) begin
        ap_done_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter7_reg == 1'b1))) begin
        ap_done_reg <= 1'b1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_enable_reg_pp0_iter1 <= ap_start_int;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln118_fu_103_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            k_fu_44 <= add_ln118_fu_109_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            k_fu_44 <= 11'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
        ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        im_reg_181 <= imag_buf_q0;
        r_reg_176 <= real_buf_q0;
        zext_ln118_reg_161[10 : 0] <= zext_ln118_fu_115_p1[10 : 0];
        zext_ln118_reg_161_pp0_iter1_reg[10 : 0] <= zext_ln118_reg_161[10 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        mul_ln122_1_reg_203 <= grp_fu_91_p2;
        mul_ln122_reg_198 <= grp_fu_87_p2;
        trunc_ln8_reg_208 <= {{pwr_fu_136_p2[57:26]}};
        zext_ln118_reg_161_pp0_iter2_reg[10 : 0] <= zext_ln118_reg_161_pp0_iter1_reg[10 : 0];
        zext_ln118_reg_161_pp0_iter3_reg[10 : 0] <= zext_ln118_reg_161_pp0_iter2_reg[10 : 0];
        zext_ln118_reg_161_pp0_iter4_reg[10 : 0] <= zext_ln118_reg_161_pp0_iter3_reg[10 : 0];
        zext_ln118_reg_161_pp0_iter5_reg[10 : 0] <= zext_ln118_reg_161_pp0_iter4_reg[10 : 0];
        zext_ln118_reg_161_pp0_iter6_reg[10 : 0] <= zext_ln118_reg_161_pp0_iter5_reg[10 : 0];
        zext_ln118_reg_161_pp0_iter7_reg[10 : 0] <= zext_ln118_reg_161_pp0_iter6_reg[10 : 0];
    end
end

always @ (*) begin
    if (((icmp_ln118_fu_103_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter7_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_k_1 = 11'd0;
    end else begin
        ap_sig_allocacmp_k_1 = k_fu_44;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        imag_buf_ce0_local = 1'b1;
    end else begin
        imag_buf_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1))) begin
        power_buf_ce0_local = 1'b1;
    end else begin
        power_buf_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1))) begin
        power_buf_we0_local = 1'b1;
    end else begin
        power_buf_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        real_buf_ce0_local = 1'b1;
    end else begin
        real_buf_ce0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln118_fu_109_p2 = (ap_sig_allocacmp_k_1 + 11'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign grp_fu_87_p0 = sext_ln120_fu_126_p1;

assign grp_fu_87_p1 = sext_ln120_fu_126_p1;

assign grp_fu_91_p0 = sext_ln121_fu_131_p1;

assign grp_fu_91_p1 = sext_ln121_fu_131_p1;

assign icmp_ln118_fu_103_p2 = ((ap_sig_allocacmp_k_1 == 11'd1025) ? 1'b1 : 1'b0);

assign imag_buf_address0 = zext_ln118_fu_115_p1;

assign imag_buf_ce0 = imag_buf_ce0_local;

assign power_buf_address0 = zext_ln118_reg_161_pp0_iter7_reg;

assign power_buf_ce0 = power_buf_ce0_local;

assign power_buf_d0 = trunc_ln8_reg_208;

assign power_buf_we0 = power_buf_we0_local;

assign pwr_fu_136_p2 = (mul_ln122_1_reg_203 + mul_ln122_reg_198);

assign real_buf_address0 = zext_ln118_fu_115_p1;

assign real_buf_ce0 = real_buf_ce0_local;

assign sext_ln120_fu_126_p1 = $signed(r_reg_176);

assign sext_ln121_fu_131_p1 = $signed(im_reg_181);

assign zext_ln118_fu_115_p1 = ap_sig_allocacmp_k_1;

always @ (posedge ap_clk) begin
    zext_ln118_reg_161[63:11] <= 53'b00000000000000000000000000000000000000000000000000000;
    zext_ln118_reg_161_pp0_iter1_reg[63:11] <= 53'b00000000000000000000000000000000000000000000000000000;
    zext_ln118_reg_161_pp0_iter2_reg[63:11] <= 53'b00000000000000000000000000000000000000000000000000000;
    zext_ln118_reg_161_pp0_iter3_reg[63:11] <= 53'b00000000000000000000000000000000000000000000000000000;
    zext_ln118_reg_161_pp0_iter4_reg[63:11] <= 53'b00000000000000000000000000000000000000000000000000000;
    zext_ln118_reg_161_pp0_iter5_reg[63:11] <= 53'b00000000000000000000000000000000000000000000000000000;
    zext_ln118_reg_161_pp0_iter6_reg[63:11] <= 53'b00000000000000000000000000000000000000000000000000000;
    zext_ln118_reg_161_pp0_iter7_reg[63:11] <= 53'b00000000000000000000000000000000000000000000000000000;
end

endmodule //cfu_hls_cfu_hls_Pipeline_POWER_LOOP
