// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module cfu_hls_cfu_hls_Pipeline_BITREV_LOOP (
        ap_clk,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        real_buf_address0,
        real_buf_ce0,
        real_buf_q0,
        real_buf_address1,
        real_buf_ce1,
        real_buf_we1,
        real_buf_d1,
        real_buf_q1,
        imag_buf_address0,
        imag_buf_ce0,
        imag_buf_q0,
        imag_buf_address1,
        imag_buf_ce1,
        imag_buf_we1,
        imag_buf_d1,
        imag_buf_q1
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_state2 = 3'd2;
parameter    ap_ST_fsm_state3 = 3'd4;

input   ap_clk;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [10:0] real_buf_address0;
output   real_buf_ce0;
input  [31:0] real_buf_q0;
output  [10:0] real_buf_address1;
output   real_buf_ce1;
output   real_buf_we1;
output  [31:0] real_buf_d1;
input  [31:0] real_buf_q1;
output  [10:0] imag_buf_address0;
output   imag_buf_ce0;
input  [31:0] imag_buf_q0;
output  [10:0] imag_buf_address1;
output   imag_buf_ce1;
output   imag_buf_we1;
output  [31:0] imag_buf_d1;
input  [31:0] imag_buf_q1;

reg ap_idle;

(* fsm_encoding = "auto" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_block_state1_pp0_stage0_iter0;
wire   [0:0] icmp_ln63_fu_104_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_CS_fsm_state3;
reg   [0:0] icmp_ln63_reg_159;
wire   [11:0] add_ln63_fu_110_p2;
reg   [11:0] add_ln63_reg_163;
wire   [0:0] icmp_ln79_fu_142_p2;
reg   [0:0] icmp_ln79_reg_168;
reg   [10:0] real_buf_addr_1_reg_172;
reg   [10:0] real_buf_addr_reg_177;
reg   [10:0] imag_buf_addr_1_reg_183;
reg   [10:0] imag_buf_addr_reg_188;
reg   [31:0] tr_reg_194;
wire    ap_CS_fsm_state2;
reg   [31:0] ti_reg_199;
wire   [63:0] zext_ln63_fu_116_p1;
wire   [63:0] zext_ln79_fu_136_p1;
reg   [11:0] i_fu_40;
wire    ap_loop_init;
reg   [11:0] ap_sig_allocacmp_x;
reg    real_buf_ce1_local;
reg   [10:0] real_buf_address1_local;
reg    real_buf_ce0_local;
reg    real_buf_we1_local;
reg   [31:0] real_buf_d1_local;
reg    imag_buf_ce1_local;
reg   [10:0] imag_buf_address1_local;
reg    imag_buf_ce0_local;
reg    imag_buf_we1_local;
reg   [31:0] imag_buf_d1_local;
reg   [10:0] r_fu_126_p4;
wire   [10:0] trunc_ln64_fu_122_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [2:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 3'd1;
#0 i_fu_40 = 12'd0;
#0 ap_done_reg = 1'b0;
end

cfu_hls_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(1'b0),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    ap_CS_fsm <= ap_NS_fsm;
end

always @ (posedge ap_clk) begin
    if ((ap_continue_int == 1'b1)) begin
        ap_done_reg <= 1'b0;
    end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done_reg <= 1'b1;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        i_fu_40 <= 12'd0;
    end else if (((icmp_ln63_reg_159 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        i_fu_40 <= add_ln63_reg_163;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        add_ln63_reg_163 <= add_ln63_fu_110_p2;
        icmp_ln63_reg_159 <= icmp_ln63_fu_104_p2;
        icmp_ln79_reg_168 <= icmp_ln79_fu_142_p2;
        imag_buf_addr_1_reg_183 <= zext_ln63_fu_116_p1;
        imag_buf_addr_reg_188 <= zext_ln79_fu_136_p1;
        real_buf_addr_1_reg_172 <= zext_ln63_fu_116_p1;
        real_buf_addr_reg_177 <= zext_ln79_fu_136_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        ti_reg_199 <= imag_buf_q1;
        tr_reg_194 <= real_buf_q1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1_pp0_stage0_iter0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if (((icmp_ln63_fu_104_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_x = 12'd0;
    end else begin
        ap_sig_allocacmp_x = i_fu_40;
    end
end

always @ (*) begin
    if (((icmp_ln79_reg_168 == 1'd1) & (icmp_ln63_reg_159 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        imag_buf_address1_local = imag_buf_addr_reg_188;
    end else if (((icmp_ln79_reg_168 == 1'd1) & (icmp_ln63_reg_159 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        imag_buf_address1_local = imag_buf_addr_1_reg_183;
    end else if (((icmp_ln79_fu_142_p2 == 1'd1) & (icmp_ln63_fu_104_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        imag_buf_address1_local = zext_ln63_fu_116_p1;
    end else begin
        imag_buf_address1_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        imag_buf_ce0_local = 1'b1;
    end else begin
        imag_buf_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_ln79_fu_142_p2 == 1'd1) & (icmp_ln63_fu_104_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1)) | ((icmp_ln79_reg_168 == 1'd1) & (icmp_ln63_reg_159 == 1'd0) & (1'b1 == ap_CS_fsm_state2)) | ((icmp_ln79_reg_168 == 1'd1) & (icmp_ln63_reg_159 == 1'd0) & (1'b1 == ap_CS_fsm_state3)))) begin
        imag_buf_ce1_local = 1'b1;
    end else begin
        imag_buf_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln79_reg_168 == 1'd1) & (icmp_ln63_reg_159 == 1'd0))) begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            imag_buf_d1_local = ti_reg_199;
        end else if ((1'b1 == ap_CS_fsm_state2)) begin
            imag_buf_d1_local = imag_buf_q0;
        end else begin
            imag_buf_d1_local = 'bx;
        end
    end else begin
        imag_buf_d1_local = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln79_reg_168 == 1'd1) & (icmp_ln63_reg_159 == 1'd0) & (1'b1 == ap_CS_fsm_state2)) | ((icmp_ln79_reg_168 == 1'd1) & (icmp_ln63_reg_159 == 1'd0) & (1'b1 == ap_CS_fsm_state3)))) begin
        imag_buf_we1_local = 1'b1;
    end else begin
        imag_buf_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln79_reg_168 == 1'd1) & (icmp_ln63_reg_159 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        real_buf_address1_local = real_buf_addr_reg_177;
    end else if (((icmp_ln79_reg_168 == 1'd1) & (icmp_ln63_reg_159 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        real_buf_address1_local = real_buf_addr_1_reg_172;
    end else if (((icmp_ln79_fu_142_p2 == 1'd1) & (icmp_ln63_fu_104_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        real_buf_address1_local = zext_ln63_fu_116_p1;
    end else begin
        real_buf_address1_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        real_buf_ce0_local = 1'b1;
    end else begin
        real_buf_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_ln79_fu_142_p2 == 1'd1) & (icmp_ln63_fu_104_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1)) | ((icmp_ln79_reg_168 == 1'd1) & (icmp_ln63_reg_159 == 1'd0) & (1'b1 == ap_CS_fsm_state2)) | ((icmp_ln79_reg_168 == 1'd1) & (icmp_ln63_reg_159 == 1'd0) & (1'b1 == ap_CS_fsm_state3)))) begin
        real_buf_ce1_local = 1'b1;
    end else begin
        real_buf_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln79_reg_168 == 1'd1) & (icmp_ln63_reg_159 == 1'd0))) begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            real_buf_d1_local = tr_reg_194;
        end else if ((1'b1 == ap_CS_fsm_state2)) begin
            real_buf_d1_local = real_buf_q0;
        end else begin
            real_buf_d1_local = 'bx;
        end
    end else begin
        real_buf_d1_local = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln79_reg_168 == 1'd1) & (icmp_ln63_reg_159 == 1'd0) & (1'b1 == ap_CS_fsm_state2)) | ((icmp_ln79_reg_168 == 1'd1) & (icmp_ln63_reg_159 == 1'd0) & (1'b1 == ap_CS_fsm_state3)))) begin
        real_buf_we1_local = 1'b1;
    end else begin
        real_buf_we1_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((icmp_ln63_fu_104_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln63_fu_110_p2 = (ap_sig_allocacmp_x + 12'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_start_int == 1'b0);
end

assign ap_done = ap_done_sig;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign icmp_ln63_fu_104_p2 = ((ap_sig_allocacmp_x == 12'd2048) ? 1'b1 : 1'b0);

assign icmp_ln79_fu_142_p2 = ((trunc_ln64_fu_122_p1 < r_fu_126_p4) ? 1'b1 : 1'b0);

assign imag_buf_address0 = zext_ln79_fu_136_p1;

assign imag_buf_address1 = imag_buf_address1_local;

assign imag_buf_ce0 = imag_buf_ce0_local;

assign imag_buf_ce1 = imag_buf_ce1_local;

assign imag_buf_d1 = imag_buf_d1_local;

assign imag_buf_we1 = imag_buf_we1_local;

integer ap_tvar_int_0;

always @ (ap_sig_allocacmp_x) begin
    for (ap_tvar_int_0 = 11 - 1; ap_tvar_int_0 >= 0; ap_tvar_int_0 = ap_tvar_int_0 - 1) begin
        if (ap_tvar_int_0 > 10 - 0) begin
            r_fu_126_p4[ap_tvar_int_0] = 1'b0;
        end else begin
            r_fu_126_p4[ap_tvar_int_0] = ap_sig_allocacmp_x[10 - ap_tvar_int_0];
        end
    end
end

assign real_buf_address0 = zext_ln79_fu_136_p1;

assign real_buf_address1 = real_buf_address1_local;

assign real_buf_ce0 = real_buf_ce0_local;

assign real_buf_ce1 = real_buf_ce1_local;

assign real_buf_d1 = real_buf_d1_local;

assign real_buf_we1 = real_buf_we1_local;

assign trunc_ln64_fu_122_p1 = ap_sig_allocacmp_x[10:0];

assign zext_ln63_fu_116_p1 = ap_sig_allocacmp_x;

assign zext_ln79_fu_136_p1 = r_fu_126_p4;

endmodule //cfu_hls_cfu_hls_Pipeline_BITREV_LOOP
