// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module cfu_hls_cfu_hls_Pipeline_MEL_ACCUM (
        ap_clk,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        weight_idx,
        weight_idx_2,
        k_start,
        mel_pwr_out,
        mel_pwr_out_ap_vld,
        power_buf_address0,
        power_buf_ce0,
        power_buf_q0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [12:0] weight_idx;
input  [12:0] weight_idx_2;
input  [9:0] k_start;
output  [47:0] mel_pwr_out;
output   mel_pwr_out_ap_vld;
output  [10:0] power_buf_address0;
output   power_buf_ce0;
input  [31:0] power_buf_q0;

reg ap_idle;
reg mel_pwr_out_ap_vld;

(* fsm_encoding = "auto" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln134_fu_134_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [10:0] mel_weights_compact_fixed_address0;
wire   [15:0] mel_weights_compact_fixed_q0;
wire    ap_block_pp0_stage0_11001;
reg   [12:0] weight_idx_3_reg_231;
reg   [0:0] icmp_ln134_reg_236;
reg   [0:0] icmp_ln134_reg_236_pp0_iter1_reg;
reg   [0:0] icmp_ln134_reg_236_pp0_iter2_reg;
reg   [0:0] icmp_ln134_reg_236_pp0_iter3_reg;
reg   [0:0] icmp_ln134_reg_236_pp0_iter4_reg;
reg   [0:0] icmp_ln134_reg_236_pp0_iter5_reg;
reg   [0:0] icmp_ln134_reg_236_pp0_iter6_reg;
reg   [0:0] icmp_ln134_reg_236_pp0_iter7_reg;
wire   [9:0] add_ln136_fu_150_p2;
reg   [9:0] add_ln136_reg_240;
reg  signed [31:0] power_buf_load_reg_255;
reg   [15:0] mel_weights_compact_fixed_load_reg_260;
wire   [47:0] grp_fu_109_p2;
reg   [47:0] mul_ln137_reg_275;
wire   [63:0] zext_ln136_fu_176_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln134_fu_172_p1;
reg   [55:0] mel_pwr_fu_46;
wire   [55:0] mel_pwr_3_fu_199_p2;
wire    ap_loop_init;
reg   [7:0] ii_fu_50;
wire   [7:0] add_ln134_fu_140_p2;
reg   [7:0] ap_sig_allocacmp_ii_1;
reg   [12:0] weight_idx_1_fu_54;
wire   [12:0] add_ln137_fu_156_p2;
reg   [12:0] ap_sig_allocacmp_weight_idx_3;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
wire    ap_block_pp0_stage0_01001;
reg    power_buf_ce0_local;
reg    mel_weights_compact_fixed_ce0_local;
wire   [15:0] grp_fu_109_p0;
wire   [9:0] zext_ln134_1_fu_146_p1;
wire  signed [55:0] sext_ln136_fu_196_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [47:0] grp_fu_109_p00;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 mel_pwr_fu_46 = 56'd0;
#0 ii_fu_50 = 8'd0;
#0 weight_idx_1_fu_54 = 13'd0;
#0 ap_done_reg = 1'b0;
end

cfu_hls_cfu_hls_Pipeline_MEL_ACCUM_mel_weights_compact_fixed_ROM_AUTO_1R #(
    .DataWidth( 16 ),
    .AddressRange( 1958 ),
    .AddressWidth( 11 ))
mel_weights_compact_fixed_U(
    .clk(ap_clk),
    .reset(1'b0),
    .address0(mel_weights_compact_fixed_address0),
    .ce0(mel_weights_compact_fixed_ce0_local),
    .q0(mel_weights_compact_fixed_q0)
);

cfu_hls_mul_16ns_32s_48_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 48 ))
mul_16ns_32s_48_5_1_U27(
    .clk(ap_clk),
    .reset(1'b0),
    .din0(grp_fu_109_p0),
    .din1(power_buf_load_reg_255),
    .ce(1'b1),
    .dout(grp_fu_109_p2)
);

cfu_hls_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(1'b0),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    ap_CS_fsm <= ap_NS_fsm;
end

always @ (posedge ap_clk) begin
    if ((ap_continue_int == 1'b1)) begin
        ap_done_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter8_reg == 1'b1))) begin
        ap_done_reg <= 1'b1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter7_reg == 1'b0))) begin
        ap_loop_exit_ready_pp0_iter8_reg <= 1'b0;
    end else if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln134_fu_134_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            ii_fu_50 <= add_ln134_fu_140_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            ii_fu_50 <= 8'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            mel_pwr_fu_46 <= 56'd0;
        end else if (((ap_enable_reg_pp0_iter8 == 1'b1) & (icmp_ln134_reg_236_pp0_iter7_reg == 1'd0))) begin
            mel_pwr_fu_46 <= mel_pwr_3_fu_199_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln134_fu_134_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            weight_idx_1_fu_54 <= add_ln137_fu_156_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            weight_idx_1_fu_54 <= weight_idx;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln136_reg_240 <= add_ln136_fu_150_p2;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        icmp_ln134_reg_236 <= icmp_ln134_fu_134_p2;
        icmp_ln134_reg_236_pp0_iter1_reg <= icmp_ln134_reg_236;
        weight_idx_3_reg_231 <= ap_sig_allocacmp_weight_idx_3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_enable_reg_pp0_iter1 <= ap_start_int;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
        ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        icmp_ln134_reg_236_pp0_iter2_reg <= icmp_ln134_reg_236_pp0_iter1_reg;
        icmp_ln134_reg_236_pp0_iter3_reg <= icmp_ln134_reg_236_pp0_iter2_reg;
        icmp_ln134_reg_236_pp0_iter4_reg <= icmp_ln134_reg_236_pp0_iter3_reg;
        icmp_ln134_reg_236_pp0_iter5_reg <= icmp_ln134_reg_236_pp0_iter4_reg;
        icmp_ln134_reg_236_pp0_iter6_reg <= icmp_ln134_reg_236_pp0_iter5_reg;
        icmp_ln134_reg_236_pp0_iter7_reg <= icmp_ln134_reg_236_pp0_iter6_reg;
        mel_weights_compact_fixed_load_reg_260 <= mel_weights_compact_fixed_q0;
        mul_ln137_reg_275 <= grp_fu_109_p2;
        power_buf_load_reg_255 <= power_buf_q0;
    end
end

always @ (*) begin
    if (((icmp_ln134_fu_134_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter8_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_ii_1 = 8'd0;
    end else begin
        ap_sig_allocacmp_ii_1 = ii_fu_50;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_weight_idx_3 = weight_idx;
    end else begin
        ap_sig_allocacmp_weight_idx_3 = weight_idx_1_fu_54;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter8_reg == 1'b1) & (icmp_ln134_reg_236_pp0_iter7_reg == 1'd1))) begin
        mel_pwr_out_ap_vld = 1'b1;
    end else begin
        mel_pwr_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        mel_weights_compact_fixed_ce0_local = 1'b1;
    end else begin
        mel_weights_compact_fixed_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        power_buf_ce0_local = 1'b1;
    end else begin
        power_buf_ce0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln134_fu_140_p2 = (ap_sig_allocacmp_ii_1 + 8'd1);

assign add_ln136_fu_150_p2 = (zext_ln134_1_fu_146_p1 + k_start);

assign add_ln137_fu_156_p2 = (ap_sig_allocacmp_weight_idx_3 + 13'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign grp_fu_109_p0 = grp_fu_109_p00;

assign grp_fu_109_p00 = mel_weights_compact_fixed_load_reg_260;

assign icmp_ln134_fu_134_p2 = ((ap_sig_allocacmp_weight_idx_3 == weight_idx_2) ? 1'b1 : 1'b0);

assign mel_pwr_3_fu_199_p2 = ($signed(sext_ln136_fu_196_p1) + $signed(mel_pwr_fu_46));

assign mel_pwr_out = mel_pwr_fu_46[47:0];

assign mel_weights_compact_fixed_address0 = zext_ln134_fu_172_p1;

assign power_buf_address0 = zext_ln136_fu_176_p1;

assign power_buf_ce0 = power_buf_ce0_local;

assign sext_ln136_fu_196_p1 = $signed(mul_ln137_reg_275);

assign zext_ln134_1_fu_146_p1 = ap_sig_allocacmp_ii_1;

assign zext_ln134_fu_172_p1 = weight_idx_3_reg_231;

assign zext_ln136_fu_176_p1 = add_ln136_reg_240;

endmodule //cfu_hls_cfu_hls_Pipeline_MEL_ACCUM
