-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity cfu_hls_cfu_hls_Pipeline_FFT_STAGE_FFT_BUTTERFLY is
port (
    ap_clk : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    real_buf_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    real_buf_ce0 : OUT STD_LOGIC;
    real_buf_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    real_buf_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
    real_buf_ce1 : OUT STD_LOGIC;
    real_buf_we1 : OUT STD_LOGIC;
    real_buf_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    imag_buf_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    imag_buf_ce0 : OUT STD_LOGIC;
    imag_buf_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    imag_buf_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
    imag_buf_ce1 : OUT STD_LOGIC;
    imag_buf_we1 : OUT STD_LOGIC;
    imag_buf_d1 : OUT STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of cfu_hls_cfu_hls_Pipeline_FFT_STAGE_FFT_BUTTERFLY is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_fsm_pp0_stage1 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv14_0 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000000";
    constant ap_const_lv14_2C00 : STD_LOGIC_VECTOR (13 downto 0) := "10110000000000";
    constant ap_const_lv14_1 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000001";
    constant ap_const_lv11_400 : STD_LOGIC_VECTOR (10 downto 0) := "10000000000";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv4_2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_const_lv11_1 : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";
    constant ap_const_lv21_400 : STD_LOGIC_VECTOR (20 downto 0) := "000000000010000000000";
    constant ap_const_lv10_3FF : STD_LOGIC_VECTOR (9 downto 0) := "1111111111";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_2F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "auto";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "auto";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage1 : signal is "auto";
    signal ap_block_pp0_stage1_subdone : BOOLEAN;
    signal ap_enable_reg_pp0_iter0_reg : STD_LOGIC := '0';
    signal icmp_ln88_reg_498 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage1 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal cos_table_fixed_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal cos_table_fixed_q0 : STD_LOGIC_VECTOR (17 downto 0);
    signal sin_table_fixed_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal sin_table_fixed_q0 : STD_LOGIC_VECTOR (16 downto 0);
    signal reg_172 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal ap_block_pp0_stage1_11001 : BOOLEAN;
    signal reg_176 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln88_fu_198_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln88_fu_204_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal add_ln88_reg_502 : STD_LOGIC_VECTOR (13 downto 0);
    signal k_1_load_reg_507 : STD_LOGIC_VECTOR (10 downto 0);
    signal stage_load_reg_512 : STD_LOGIC_VECTOR (3 downto 0);
    signal icmp_ln92_fu_216_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln92_reg_518 : STD_LOGIC_VECTOR (0 downto 0);
    signal stage_13_fu_222_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal stage_13_reg_525 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln88_fu_228_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal select_ln88_reg_531 : STD_LOGIC_VECTOR (10 downto 0);
    signal stage_1_mid1_fu_234_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal stage_1_mid1_reg_536 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln88_2_fu_239_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln88_2_reg_541 : STD_LOGIC_VECTOR (3 downto 0);
    signal half_size_fu_252_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal half_size_reg_546 : STD_LOGIC_VECTOR (10 downto 0);
    signal half_size_reg_546_pp0_iter1_reg : STD_LOGIC_VECTOR (10 downto 0);
    signal half_size_reg_546_pp0_iter2_reg : STD_LOGIC_VECTOR (10 downto 0);
    signal trunc_ln101_fu_274_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln101_reg_551 : STD_LOGIC_VECTOR (9 downto 0);
    signal jj_fu_282_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal jj_reg_556 : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln98_fu_335_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln98_reg_562 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_reg_567 : STD_LOGIC_VECTOR (0 downto 0);
    signal idx_fu_355_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal idx_reg_572 : STD_LOGIC_VECTOR (10 downto 0);
    signal idx_reg_572_pp0_iter2_reg : STD_LOGIC_VECTOR (10 downto 0);
    signal idx_reg_572_pp0_iter3_reg : STD_LOGIC_VECTOR (10 downto 0);
    signal idx_reg_572_pp0_iter4_reg : STD_LOGIC_VECTOR (10 downto 0);
    signal idx_reg_572_pp0_iter5_reg : STD_LOGIC_VECTOR (10 downto 0);
    signal idx2_fu_362_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal idx2_reg_578 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_fu_347_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal mul_ln101_reg_583 : STD_LOGIC_VECTOR (9 downto 0);
    signal real_buf_addr_reg_598 : STD_LOGIC_VECTOR (10 downto 0);
    signal real_buf_addr_reg_598_pp0_iter4_reg : STD_LOGIC_VECTOR (10 downto 0);
    signal real_buf_addr_reg_598_pp0_iter5_reg : STD_LOGIC_VECTOR (10 downto 0);
    signal real_buf_addr_reg_598_pp0_iter6_reg : STD_LOGIC_VECTOR (10 downto 0);
    signal imag_buf_addr_reg_604 : STD_LOGIC_VECTOR (10 downto 0);
    signal imag_buf_addr_reg_604_pp0_iter4_reg : STD_LOGIC_VECTOR (10 downto 0);
    signal imag_buf_addr_reg_604_pp0_iter5_reg : STD_LOGIC_VECTOR (10 downto 0);
    signal imag_buf_addr_reg_604_pp0_iter6_reg : STD_LOGIC_VECTOR (10 downto 0);
    signal wr_reg_610 : STD_LOGIC_VECTOR (17 downto 0);
    signal wi_reg_615 : STD_LOGIC_VECTOR (16 downto 0);
    signal sext_ln107_fu_376_p1 : STD_LOGIC_VECTOR (47 downto 0);
    signal sext_ln107_1_fu_382_p1 : STD_LOGIC_VECTOR (47 downto 0);
    signal sext_ln107_2_fu_387_p1 : STD_LOGIC_VECTOR (47 downto 0);
    signal sext_ln107_3_fu_393_p1 : STD_LOGIC_VECTOR (47 downto 0);
    signal real_buf_addr_1_reg_644 : STD_LOGIC_VECTOR (10 downto 0);
    signal real_buf_addr_1_reg_644_pp0_iter7_reg : STD_LOGIC_VECTOR (10 downto 0);
    signal imag_buf_addr_1_reg_650 : STD_LOGIC_VECTOR (10 downto 0);
    signal imag_buf_addr_1_reg_650_pp0_iter7_reg : STD_LOGIC_VECTOR (10 downto 0);
    signal tr_fu_423_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tr_reg_656 : STD_LOGIC_VECTOR (31 downto 0);
    signal ti_fu_449_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ti_reg_662 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln111_fu_467_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln111_reg_668 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln112_fu_472_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln112_reg_673 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln101_fu_366_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage1 : BOOLEAN;
    signal zext_ln103_fu_371_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln105_fu_398_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal k_1_fu_68 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    signal k_fu_288_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_k_1_load : STD_LOGIC_VECTOR (10 downto 0);
    signal stage_fu_72 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal ap_sig_allocacmp_stage_load : STD_LOGIC_VECTOR (3 downto 0);
    signal indvar_flatten_fu_76 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000000";
    signal ap_sig_allocacmp_indvar_flatten_load : STD_LOGIC_VECTOR (13 downto 0);
    signal cos_table_fixed_ce0_local : STD_LOGIC;
    signal sin_table_fixed_ce0_local : STD_LOGIC;
    signal real_buf_ce0_local : STD_LOGIC;
    signal real_buf_address0_local : STD_LOGIC_VECTOR (10 downto 0);
    signal real_buf_we1_local : STD_LOGIC;
    signal real_buf_d1_local : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln109_fu_455_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal real_buf_ce1_local : STD_LOGIC;
    signal real_buf_address1_local : STD_LOGIC_VECTOR (10 downto 0);
    signal imag_buf_ce0_local : STD_LOGIC;
    signal imag_buf_address0_local : STD_LOGIC_VECTOR (10 downto 0);
    signal imag_buf_we1_local : STD_LOGIC;
    signal imag_buf_d1_local : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln110_fu_461_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal imag_buf_ce1_local : STD_LOGIC;
    signal imag_buf_address1_local : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_fu_156_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_156_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_fu_160_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_160_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_fu_164_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_164_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal grp_fu_168_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_168_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal zext_ln88_2_fu_248_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln88_1_fu_244_p1 : STD_LOGIC_VECTOR (20 downto 0);
    signal trunc_ln89_fu_258_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal table_step_fu_262_p2 : STD_LOGIC_VECTOR (20 downto 0);
    signal trunc_ln92_fu_278_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal sub_fu_268_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln88_1_fu_308_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln92_1_fu_320_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln88_fu_313_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal group_fu_323_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln92_fu_316_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal shl_ln98_fu_329_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal or_ln98_fu_351_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_fu_164_p2 : STD_LOGIC_VECTOR (47 downto 0);
    signal grp_fu_156_p2 : STD_LOGIC_VECTOR (47 downto 0);
    signal trunc_ln6_fu_403_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln107_1_fu_413_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_168_p2 : STD_LOGIC_VECTOR (47 downto 0);
    signal grp_fu_160_p2 : STD_LOGIC_VECTOR (47 downto 0);
    signal trunc_ln7_fu_429_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln108_1_fu_439_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln109_fu_455_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln110_fu_461_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln111_fu_467_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln112_fu_472_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter5_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter6_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_idle_pp0_1to7 : STD_LOGIC;
    signal ap_block_pp0 : BOOLEAN;
    signal ap_enable_operation_75 : BOOLEAN;
    signal ap_enable_state8_pp0_iter3_stage1 : BOOLEAN;
    signal ap_enable_operation_80 : BOOLEAN;
    signal ap_enable_state9_pp0_iter4_stage0 : BOOLEAN;
    signal ap_enable_operation_120 : BOOLEAN;
    signal ap_enable_state15_pp0_iter7_stage0 : BOOLEAN;
    signal ap_enable_operation_128 : BOOLEAN;
    signal ap_enable_state16_pp0_iter7_stage1 : BOOLEAN;
    signal ap_enable_operation_77 : BOOLEAN;
    signal ap_enable_operation_81 : BOOLEAN;
    signal ap_enable_operation_122 : BOOLEAN;
    signal ap_enable_operation_129 : BOOLEAN;
    signal ap_enable_operation_100 : BOOLEAN;
    signal ap_enable_state13_pp0_iter6_stage0 : BOOLEAN;
    signal ap_enable_operation_107 : BOOLEAN;
    signal ap_enable_state14_pp0_iter6_stage1 : BOOLEAN;
    signal ap_enable_operation_102 : BOOLEAN;
    signal ap_enable_operation_108 : BOOLEAN;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component cfu_hls_mul_32s_17s_48_5_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (16 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (47 downto 0) );
    end component;


    component cfu_hls_mul_32s_18s_48_5_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (17 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (47 downto 0) );
    end component;


    component cfu_hls_mul_10s_10s_10_5_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (9 downto 0);
        din1 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (9 downto 0) );
    end component;


    component cfu_hls_cfu_hls_Pipeline_FFT_STAGE_FFT_BUTTERFLY_cos_table_fixed_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (17 downto 0) );
    end component;


    component cfu_hls_cfu_hls_Pipeline_FFT_STAGE_FFT_BUTTERFLY_sin_table_fixed_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (16 downto 0) );
    end component;


    component cfu_hls_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    cos_table_fixed_U : component cfu_hls_cfu_hls_Pipeline_FFT_STAGE_FFT_BUTTERFLY_cos_table_fixed_ROM_AUTO_1R
    generic map (
        DataWidth => 18,
        AddressRange => 1024,
        AddressWidth => 10)
    port map (
        clk => ap_clk,
        reset => ap_const_logic_0,
        address0 => cos_table_fixed_address0,
        ce0 => cos_table_fixed_ce0_local,
        q0 => cos_table_fixed_q0);

    sin_table_fixed_U : component cfu_hls_cfu_hls_Pipeline_FFT_STAGE_FFT_BUTTERFLY_sin_table_fixed_ROM_AUTO_1R
    generic map (
        DataWidth => 17,
        AddressRange => 1024,
        AddressWidth => 10)
    port map (
        clk => ap_clk,
        reset => ap_const_logic_0,
        address0 => sin_table_fixed_address0,
        ce0 => sin_table_fixed_ce0_local,
        q0 => sin_table_fixed_q0);

    mul_32s_17s_48_5_1_U9 : component cfu_hls_mul_32s_17s_48_5_1
    generic map (
        ID => 1,
        NUM_STAGE => 5,
        din0_WIDTH => 32,
        din1_WIDTH => 17,
        dout_WIDTH => 48)
    port map (
        clk => ap_clk,
        reset => ap_const_logic_0,
        din0 => grp_fu_156_p0,
        din1 => grp_fu_156_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_156_p2);

    mul_32s_17s_48_5_1_U10 : component cfu_hls_mul_32s_17s_48_5_1
    generic map (
        ID => 1,
        NUM_STAGE => 5,
        din0_WIDTH => 32,
        din1_WIDTH => 17,
        dout_WIDTH => 48)
    port map (
        clk => ap_clk,
        reset => ap_const_logic_0,
        din0 => grp_fu_160_p0,
        din1 => grp_fu_160_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_160_p2);

    mul_32s_18s_48_5_1_U11 : component cfu_hls_mul_32s_18s_48_5_1
    generic map (
        ID => 1,
        NUM_STAGE => 5,
        din0_WIDTH => 32,
        din1_WIDTH => 18,
        dout_WIDTH => 48)
    port map (
        clk => ap_clk,
        reset => ap_const_logic_0,
        din0 => grp_fu_164_p0,
        din1 => grp_fu_164_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_164_p2);

    mul_32s_18s_48_5_1_U12 : component cfu_hls_mul_32s_18s_48_5_1
    generic map (
        ID => 1,
        NUM_STAGE => 5,
        din0_WIDTH => 32,
        din1_WIDTH => 18,
        dout_WIDTH => 48)
    port map (
        clk => ap_clk,
        reset => ap_const_logic_0,
        din0 => grp_fu_168_p0,
        din1 => grp_fu_168_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_168_p2);

    mul_10s_10s_10_5_1_U13 : component cfu_hls_mul_10s_10s_10_5_1
    generic map (
        ID => 1,
        NUM_STAGE => 5,
        din0_WIDTH => 10,
        din1_WIDTH => 10,
        dout_WIDTH => 10)
    port map (
        clk => ap_clk,
        reset => ap_const_logic_0,
        din0 => jj_reg_556,
        din1 => trunc_ln101_reg_551,
        ce => ap_const_logic_1,
        dout => grp_fu_347_p2);

    flow_control_loop_pipe_sequential_init_U : component cfu_hls_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_const_logic_0,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage1,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            ap_CS_fsm <= ap_NS_fsm;
        end if;
    end process;

    ap_done_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_continue_int = ap_const_logic_1)) then 
                ap_done_reg <= ap_const_logic_0;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_loop_exit_ready_pp0_iter6_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                ap_done_reg <= ap_const_logic_1;
            end if; 
        end if;
    end process;

    ap_enable_reg_pp0_iter1_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage1)) then 
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
            end if; 
        end if;
    end process;

    indvar_flatten_fu_76_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                indvar_flatten_fu_76 <= ap_const_lv14_0;
            elsif (((icmp_ln88_reg_498 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                indvar_flatten_fu_76 <= add_ln88_reg_502;
            end if; 
        end if;
    end process;

    k_1_fu_68_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                k_1_fu_68 <= ap_const_lv11_0;
            elsif (((icmp_ln88_reg_498 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                k_1_fu_68 <= k_fu_288_p2;
            end if; 
        end if;
    end process;

    stage_fu_72_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                stage_fu_72 <= ap_const_lv4_0;
            elsif (((icmp_ln88_reg_498 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                stage_fu_72 <= select_ln88_2_fu_239_p3;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                add_ln111_reg_668 <= add_ln111_fu_467_p2;
                add_ln112_reg_673 <= add_ln112_fu_472_p2;
                add_ln88_reg_502 <= add_ln88_fu_204_p2;
                icmp_ln88_reg_498 <= icmp_ln88_fu_198_p2;
                icmp_ln92_reg_518 <= icmp_ln92_fu_216_p2;
                idx2_reg_578 <= idx2_fu_362_p2;
                imag_buf_addr_1_reg_650 <= zext_ln105_fu_398_p1(11 - 1 downto 0);
                imag_buf_addr_1_reg_650_pp0_iter7_reg <= imag_buf_addr_1_reg_650;
                k_1_load_reg_507 <= ap_sig_allocacmp_k_1_load;
                mul_ln101_reg_583 <= grp_fu_347_p2;
                real_buf_addr_1_reg_644 <= zext_ln105_fu_398_p1(11 - 1 downto 0);
                real_buf_addr_1_reg_644_pp0_iter7_reg <= real_buf_addr_1_reg_644;
                stage_13_reg_525 <= stage_13_fu_222_p2;
                stage_load_reg_512 <= ap_sig_allocacmp_stage_load;
                tmp_reg_567 <= shl_ln98_fu_329_p2(10 downto 10);
                trunc_ln98_reg_562 <= trunc_ln98_fu_335_p1;
                wi_reg_615 <= sin_table_fixed_q0;
                wr_reg_610 <= cos_table_fixed_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then
                ap_enable_reg_pp0_iter0_reg <= ap_start_int;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
                ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
                half_size_reg_546 <= half_size_fu_252_p2;
                half_size_reg_546_pp0_iter1_reg <= half_size_reg_546;
                half_size_reg_546_pp0_iter2_reg <= half_size_reg_546_pp0_iter1_reg;
                idx_reg_572 <= idx_fu_355_p3;
                idx_reg_572_pp0_iter2_reg <= idx_reg_572;
                idx_reg_572_pp0_iter3_reg <= idx_reg_572_pp0_iter2_reg;
                idx_reg_572_pp0_iter4_reg <= idx_reg_572_pp0_iter3_reg;
                idx_reg_572_pp0_iter5_reg <= idx_reg_572_pp0_iter4_reg;
                imag_buf_addr_reg_604 <= zext_ln103_fu_371_p1(11 - 1 downto 0);
                imag_buf_addr_reg_604_pp0_iter4_reg <= imag_buf_addr_reg_604;
                imag_buf_addr_reg_604_pp0_iter5_reg <= imag_buf_addr_reg_604_pp0_iter4_reg;
                imag_buf_addr_reg_604_pp0_iter6_reg <= imag_buf_addr_reg_604_pp0_iter5_reg;
                jj_reg_556 <= jj_fu_282_p2;
                real_buf_addr_reg_598 <= zext_ln103_fu_371_p1(11 - 1 downto 0);
                real_buf_addr_reg_598_pp0_iter4_reg <= real_buf_addr_reg_598;
                real_buf_addr_reg_598_pp0_iter5_reg <= real_buf_addr_reg_598_pp0_iter4_reg;
                real_buf_addr_reg_598_pp0_iter6_reg <= real_buf_addr_reg_598_pp0_iter5_reg;
                select_ln88_2_reg_541 <= select_ln88_2_fu_239_p3;
                select_ln88_reg_531 <= select_ln88_fu_228_p3;
                stage_1_mid1_reg_536 <= stage_1_mid1_fu_234_p2;
                ti_reg_662 <= ti_fu_449_p2;
                tr_reg_656 <= tr_fu_423_p2;
                trunc_ln101_reg_551 <= trunc_ln101_fu_274_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then
                reg_172 <= real_buf_q0;
                reg_176 <= imag_buf_q0;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage1_subdone, ap_block_pp0_stage0_subdone, ap_idle_pp0_1to7, ap_start_int)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                if ((not(((ap_start_int = ap_const_logic_0) and (ap_idle_pp0_1to7 = ap_const_logic_1))) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage1 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                end if;
            when others =>  
                ap_NS_fsm <= "XX";
        end case;
    end process;
    add_ln111_fu_467_p0 <= reg_172;
    add_ln111_fu_467_p2 <= std_logic_vector(unsigned(add_ln111_fu_467_p0) + unsigned(tr_reg_656));
    add_ln112_fu_472_p0 <= reg_176;
    add_ln112_fu_472_p2 <= std_logic_vector(unsigned(add_ln112_fu_472_p0) + unsigned(ti_reg_662));
    add_ln88_fu_204_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten_load) + unsigned(ap_const_lv14_1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
    ap_CS_fsm_pp0_stage1 <= ap_CS_fsm(1);

    ap_block_pp0_assign_proc : process(ap_CS_fsm, ap_block_pp0_stage1_subdone, ap_block_pp0_stage0_subdone)
    begin
                ap_block_pp0 <= (((ap_ST_fsm_pp0_stage1 = ap_CS_fsm) and (ap_const_boolean_1 = ap_block_pp0_stage1_subdone)) or ((ap_ST_fsm_pp0_stage0 = ap_CS_fsm) and (ap_const_boolean_1 = ap_block_pp0_stage0_subdone)));
    end process;

        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage1_assign_proc : process(ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone, ap_enable_reg_pp0_iter0_reg, icmp_ln88_reg_498)
    begin
        if (((icmp_ln88_reg_498 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            ap_condition_exit_pp0_iter0_stage1 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage1 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter6_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_loop_exit_ready_pp0_iter6_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

        ap_enable_operation_100 <= (ap_const_boolean_1 = ap_const_boolean_1);
        ap_enable_operation_102 <= (ap_const_boolean_1 = ap_const_boolean_1);
        ap_enable_operation_107 <= (ap_const_boolean_1 = ap_const_boolean_1);
        ap_enable_operation_108 <= (ap_const_boolean_1 = ap_const_boolean_1);
        ap_enable_operation_120 <= (ap_const_boolean_1 = ap_const_boolean_1);
        ap_enable_operation_122 <= (ap_const_boolean_1 = ap_const_boolean_1);
        ap_enable_operation_128 <= (ap_const_boolean_1 = ap_const_boolean_1);
        ap_enable_operation_129 <= (ap_const_boolean_1 = ap_const_boolean_1);
        ap_enable_operation_75 <= (ap_const_boolean_1 = ap_const_boolean_1);
        ap_enable_operation_77 <= (ap_const_boolean_1 = ap_const_boolean_1);
        ap_enable_operation_80 <= (ap_const_boolean_1 = ap_const_boolean_1);
        ap_enable_operation_81 <= (ap_const_boolean_1 = ap_const_boolean_1);
    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_enable_reg_pp0_iter0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0_reg, ap_start_int)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
            ap_enable_reg_pp0_iter0 <= ap_start_int;
        else 
            ap_enable_reg_pp0_iter0 <= ap_enable_reg_pp0_iter0_reg;
        end if; 
    end process;


    ap_enable_state13_pp0_iter6_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter6)
    begin
                ap_enable_state13_pp0_iter6_stage0 <= ((ap_enable_reg_pp0_iter6 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_enable_state14_pp0_iter6_stage1_assign_proc : process(ap_enable_reg_pp0_iter6, ap_CS_fsm_pp0_stage1)
    begin
                ap_enable_state14_pp0_iter6_stage1 <= ((ap_enable_reg_pp0_iter6 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1));
    end process;


    ap_enable_state15_pp0_iter7_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter7)
    begin
                ap_enable_state15_pp0_iter7_stage0 <= ((ap_enable_reg_pp0_iter7 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_enable_state16_pp0_iter7_stage1_assign_proc : process(ap_enable_reg_pp0_iter7, ap_CS_fsm_pp0_stage1)
    begin
                ap_enable_state16_pp0_iter7_stage1 <= ((ap_enable_reg_pp0_iter7 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1));
    end process;


    ap_enable_state8_pp0_iter3_stage1_assign_proc : process(ap_enable_reg_pp0_iter3, ap_CS_fsm_pp0_stage1)
    begin
                ap_enable_state8_pp0_iter3_stage1 <= ((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1));
    end process;


    ap_enable_state9_pp0_iter4_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter4)
    begin
                ap_enable_state9_pp0_iter4_stage0 <= ((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7)
    begin
        if (((ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_1to7_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7)
    begin
        if (((ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0))) then 
            ap_idle_pp0_1to7 <= ap_const_logic_1;
        else 
            ap_idle_pp0_1to7 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage1;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone, ap_enable_reg_pp0_iter0_reg)
    begin
        if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, indvar_flatten_fu_76)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_indvar_flatten_load <= ap_const_lv14_0;
        else 
            ap_sig_allocacmp_indvar_flatten_load <= indvar_flatten_fu_76;
        end if; 
    end process;


    ap_sig_allocacmp_k_1_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, k_1_fu_68, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_k_1_load <= ap_const_lv11_0;
        else 
            ap_sig_allocacmp_k_1_load <= k_1_fu_68;
        end if; 
    end process;


    ap_sig_allocacmp_stage_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, stage_fu_72)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_stage_load <= ap_const_lv4_0;
        else 
            ap_sig_allocacmp_stage_load <= stage_fu_72;
        end if; 
    end process;

    cos_table_fixed_address0 <= zext_ln101_fu_366_p1(10 - 1 downto 0);

    cos_table_fixed_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter3, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            cos_table_fixed_ce0_local <= ap_const_logic_1;
        else 
            cos_table_fixed_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    group_fu_323_p2 <= std_logic_vector(shift_right(unsigned(zext_ln92_1_fu_320_p1),to_integer(unsigned('0' & zext_ln88_fu_313_p1(12-1 downto 0)))));
    grp_fu_156_p0 <= sext_ln107_2_fu_387_p1(32 - 1 downto 0);
    grp_fu_156_p1 <= sext_ln107_3_fu_393_p1(17 - 1 downto 0);
    grp_fu_160_p0 <= sext_ln107_fu_376_p1(32 - 1 downto 0);
    grp_fu_160_p1 <= sext_ln107_3_fu_393_p1(17 - 1 downto 0);
    grp_fu_164_p0 <= sext_ln107_fu_376_p1(32 - 1 downto 0);
    grp_fu_164_p1 <= sext_ln107_1_fu_382_p1(18 - 1 downto 0);
    grp_fu_168_p0 <= sext_ln107_2_fu_387_p1(32 - 1 downto 0);
    grp_fu_168_p1 <= sext_ln107_1_fu_382_p1(18 - 1 downto 0);
    half_size_fu_252_p2 <= std_logic_vector(shift_left(unsigned(ap_const_lv11_1),to_integer(unsigned('0' & zext_ln88_2_fu_248_p1(11-1 downto 0)))));
    icmp_ln88_fu_198_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten_load = ap_const_lv14_2C00) else "0";
    icmp_ln92_fu_216_p2 <= "1" when (ap_sig_allocacmp_k_1_load = ap_const_lv11_400) else "0";
    idx2_fu_362_p2 <= std_logic_vector(unsigned(idx_reg_572_pp0_iter2_reg) + unsigned(half_size_reg_546_pp0_iter2_reg));
    idx_fu_355_p3 <= (tmp_reg_567 & or_ln98_fu_351_p2);
    imag_buf_address0 <= imag_buf_address0_local;

    imag_buf_address0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter6, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1, zext_ln103_fu_371_p1, zext_ln105_fu_398_p1, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            imag_buf_address0_local <= zext_ln105_fu_398_p1(11 - 1 downto 0);
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            imag_buf_address0_local <= zext_ln103_fu_371_p1(11 - 1 downto 0);
        else 
            imag_buf_address0_local <= "XXXXXXXXXXX";
        end if; 
    end process;

    imag_buf_address1 <= imag_buf_address1_local;

    imag_buf_address1_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter7, ap_CS_fsm_pp0_stage1, imag_buf_addr_reg_604_pp0_iter6_reg, imag_buf_addr_1_reg_650_pp0_iter7_reg, ap_block_pp0_stage1, ap_block_pp0_stage0)
    begin
        if ((ap_enable_reg_pp0_iter7 = ap_const_logic_1)) then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                imag_buf_address1_local <= imag_buf_addr_1_reg_650_pp0_iter7_reg;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                imag_buf_address1_local <= imag_buf_addr_reg_604_pp0_iter6_reg;
            else 
                imag_buf_address1_local <= "XXXXXXXXXXX";
            end if;
        else 
            imag_buf_address1_local <= "XXXXXXXXXXX";
        end if; 
    end process;

    imag_buf_ce0 <= imag_buf_ce0_local;

    imag_buf_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter6, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0_11001, ap_block_pp0_stage1_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            imag_buf_ce0_local <= ap_const_logic_1;
        else 
            imag_buf_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    imag_buf_ce1 <= imag_buf_ce1_local;

    imag_buf_ce1_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter7, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0_11001, ap_block_pp0_stage1_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter7 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter7 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            imag_buf_ce1_local <= ap_const_logic_1;
        else 
            imag_buf_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    imag_buf_d1 <= imag_buf_d1_local;

    imag_buf_d1_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter7, ap_CS_fsm_pp0_stage1, add_ln112_reg_673, ap_block_pp0_stage1, ap_block_pp0_stage0, sub_ln110_fu_461_p2)
    begin
        if ((ap_enable_reg_pp0_iter7 = ap_const_logic_1)) then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                imag_buf_d1_local <= add_ln112_reg_673;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                imag_buf_d1_local <= sub_ln110_fu_461_p2;
            else 
                imag_buf_d1_local <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
            end if;
        else 
            imag_buf_d1_local <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    imag_buf_we1 <= imag_buf_we1_local;

    imag_buf_we1_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter7, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0_11001, ap_block_pp0_stage1_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter7 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter7 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            imag_buf_we1_local <= ap_const_logic_1;
        else 
            imag_buf_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    jj_fu_282_p2 <= (trunc_ln92_fu_278_p1 and sub_fu_268_p2);
    k_fu_288_p2 <= std_logic_vector(unsigned(select_ln88_fu_228_p3) + unsigned(ap_const_lv11_1));
    or_ln98_fu_351_p2 <= (trunc_ln98_reg_562 or jj_reg_556);
    real_buf_address0 <= real_buf_address0_local;

    real_buf_address0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter6, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1, zext_ln103_fu_371_p1, zext_ln105_fu_398_p1, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            real_buf_address0_local <= zext_ln105_fu_398_p1(11 - 1 downto 0);
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            real_buf_address0_local <= zext_ln103_fu_371_p1(11 - 1 downto 0);
        else 
            real_buf_address0_local <= "XXXXXXXXXXX";
        end if; 
    end process;

    real_buf_address1 <= real_buf_address1_local;

    real_buf_address1_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter7, ap_CS_fsm_pp0_stage1, real_buf_addr_reg_598_pp0_iter6_reg, real_buf_addr_1_reg_644_pp0_iter7_reg, ap_block_pp0_stage1, ap_block_pp0_stage0)
    begin
        if ((ap_enable_reg_pp0_iter7 = ap_const_logic_1)) then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                real_buf_address1_local <= real_buf_addr_1_reg_644_pp0_iter7_reg;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                real_buf_address1_local <= real_buf_addr_reg_598_pp0_iter6_reg;
            else 
                real_buf_address1_local <= "XXXXXXXXXXX";
            end if;
        else 
            real_buf_address1_local <= "XXXXXXXXXXX";
        end if; 
    end process;

    real_buf_ce0 <= real_buf_ce0_local;

    real_buf_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter6, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0_11001, ap_block_pp0_stage1_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            real_buf_ce0_local <= ap_const_logic_1;
        else 
            real_buf_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    real_buf_ce1 <= real_buf_ce1_local;

    real_buf_ce1_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter7, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0_11001, ap_block_pp0_stage1_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter7 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter7 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            real_buf_ce1_local <= ap_const_logic_1;
        else 
            real_buf_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    real_buf_d1 <= real_buf_d1_local;

    real_buf_d1_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter7, ap_CS_fsm_pp0_stage1, add_ln111_reg_668, ap_block_pp0_stage1, ap_block_pp0_stage0, sub_ln109_fu_455_p2)
    begin
        if ((ap_enable_reg_pp0_iter7 = ap_const_logic_1)) then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                real_buf_d1_local <= add_ln111_reg_668;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                real_buf_d1_local <= sub_ln109_fu_455_p2;
            else 
                real_buf_d1_local <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
            end if;
        else 
            real_buf_d1_local <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    real_buf_we1 <= real_buf_we1_local;

    real_buf_we1_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter7, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0_11001, ap_block_pp0_stage1_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter7 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter7 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            real_buf_we1_local <= ap_const_logic_1;
        else 
            real_buf_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    select_ln88_1_fu_308_p3 <= 
        stage_1_mid1_reg_536 when (icmp_ln92_reg_518(0) = '1') else 
        stage_13_reg_525;
    select_ln88_2_fu_239_p3 <= 
        stage_13_reg_525 when (icmp_ln92_reg_518(0) = '1') else 
        stage_load_reg_512;
    select_ln88_fu_228_p3 <= 
        ap_const_lv11_0 when (icmp_ln92_reg_518(0) = '1') else 
        k_1_load_reg_507;
        sext_ln107_1_fu_382_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(wr_reg_610),48));

        sext_ln107_2_fu_387_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(reg_176),48));

        sext_ln107_3_fu_393_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(wi_reg_615),48));

        sext_ln107_fu_376_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(reg_172),48));

    shl_ln98_fu_329_p2 <= std_logic_vector(shift_left(unsigned(group_fu_323_p2),to_integer(unsigned('0' & zext_ln92_fu_316_p1(12-1 downto 0)))));
    sin_table_fixed_address0 <= zext_ln101_fu_366_p1(10 - 1 downto 0);

    sin_table_fixed_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter3, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            sin_table_fixed_ce0_local <= ap_const_logic_1;
        else 
            sin_table_fixed_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    stage_13_fu_222_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_stage_load) + unsigned(ap_const_lv4_1));
    stage_1_mid1_fu_234_p2 <= std_logic_vector(unsigned(stage_load_reg_512) + unsigned(ap_const_lv4_2));
    sub_fu_268_p2 <= std_logic_vector(unsigned(trunc_ln89_fu_258_p1) + unsigned(ap_const_lv10_3FF));
    sub_ln109_fu_455_p0 <= reg_172;
    sub_ln109_fu_455_p2 <= std_logic_vector(unsigned(sub_ln109_fu_455_p0) - unsigned(tr_reg_656));
    sub_ln110_fu_461_p0 <= reg_176;
    sub_ln110_fu_461_p2 <= std_logic_vector(unsigned(sub_ln110_fu_461_p0) - unsigned(ti_reg_662));
    table_step_fu_262_p2 <= std_logic_vector(shift_right(unsigned(ap_const_lv21_400),to_integer(unsigned('0' & zext_ln88_1_fu_244_p1(21-1 downto 0)))));
    ti_fu_449_p2 <= std_logic_vector(unsigned(trunc_ln7_fu_429_p4) + unsigned(trunc_ln108_1_fu_439_p4));
    tr_fu_423_p2 <= std_logic_vector(unsigned(trunc_ln6_fu_403_p4) - unsigned(trunc_ln107_1_fu_413_p4));
    trunc_ln101_fu_274_p1 <= table_step_fu_262_p2(10 - 1 downto 0);
    trunc_ln107_1_fu_413_p4 <= grp_fu_156_p2(47 downto 16);
    trunc_ln108_1_fu_439_p4 <= grp_fu_160_p2(47 downto 16);
    trunc_ln6_fu_403_p4 <= grp_fu_164_p2(47 downto 16);
    trunc_ln7_fu_429_p4 <= grp_fu_168_p2(47 downto 16);
    trunc_ln89_fu_258_p1 <= half_size_fu_252_p2(10 - 1 downto 0);
    trunc_ln92_fu_278_p1 <= select_ln88_fu_228_p3(10 - 1 downto 0);
    trunc_ln98_fu_335_p1 <= shl_ln98_fu_329_p2(10 - 1 downto 0);
    zext_ln101_fu_366_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(mul_ln101_reg_583),64));
    zext_ln103_fu_371_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(idx2_reg_578),64));
    zext_ln105_fu_398_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(idx_reg_572_pp0_iter5_reg),64));
    zext_ln88_1_fu_244_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln88_2_fu_239_p3),21));
    zext_ln88_2_fu_248_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln88_2_fu_239_p3),11));
    zext_ln88_fu_313_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln88_2_reg_541),12));
    zext_ln92_1_fu_320_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln88_reg_531),12));
    zext_ln92_fu_316_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln88_1_fu_308_p3),12));
end behav;
