-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity cfu_hls_mel_k_start_fixed_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 10; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of cfu_hls_mel_k_start_fixed_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "0000000001", 1 => "0000001000", 2 => "0000001111", 3 => "0000011000", 
    4 => "0000100001", 5 => "0000101010", 6 => "0000110101", 7 => "0001000000", 
    8 => "0001001100", 9 => "0001011001", 10 => "0001100111", 11 => "0001110110", 
    12 => "0010000111", 13 => "0010011001", 14 => "0010101100", 15 => "0011000001", 
    16 => "0011010111", 17 => "0011101111", 18 => "0100001001", 19 => "0100100101", 
    20 => "0101000100", 21 => "0101100100", 22 => "0110001000", 23 => "0110101110", 
    24 => "0111010111", 25 => "1000000011", 26 => "1000110011", 27 => "1001100111", 
    28 => "1010011111", 29 => "1011011011", 30 => "1100011100", 31 => "1101100011");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

